(ns stylometry.iso-639-b)

(def iso-639-b {"cai" "Central American Indian languages",
                "mdr" "Mandar",
                "chm" "Mari",
                "kor" "Korean",
                "kas" "Kashmiri",
                "chi" "Chinese",
                "nya" "Chichewa; Chewa; Nyanja",
                "mdf" "Moksha",
                "fan" "Fang",
                "pam" "Pampanga; Kapampangan",
                "tib" "Tibetan",
                "dua" "Duala",
                "map" "Austronesian languages",
                "lus" "Lushai",
                "ain" "Ainu",
                "tgl" "Tagalog",
                "kru" "Kurukh",
                "ipk" "Inupiaq",
                "rup" "Aromanian; Arumanian; Macedo-Romanian",
                "ban" "Balinese",
                "byn" "Blin; Bilin",
                "nso" "Pedi; Sepedi; Northern Sotho",
                "gba" "Gbaya",
                "luo" "Luo (Kenya and Tanzania)",
                "tgk" "Tajik",
                "ijo" "Ijo languages",
                "nyn" "Nyankole",
                "lam" "Lamba",
                "slo" "Slovak",
                "und" "Undetermined",
                "znd" "Zande languages",
                "frr" "Northern Frisian",
                "elx" "Elamite",
                "got" "Gothic",
                "tah" "Tahitian",
                "mad" "Madurese",
                "him" "Himachali languages; Western Pahari languages",
                "gil" "Gilbertese",
                "geo" "Georgian",
                "gle" "Irish",
                "grb" "Grebo",
                "pon" "Pohnpeian",
                "kua" "Kuanyama; Kwanyama",
                "min" "Minangkabau",
                "nqo" "N'Ko",
                "nzi" "Nzima",
                "fry" "Western Frisian",
                "nno" "Norwegian Nynorsk; Nynorsk, Norwegian",
                "war" "Waray",
                "tsn" "Tswana",
                "oss" "Ossetian; Ossetic",
                "ger" "German",
                "zxx" "No linguistic content; Not applicable",
                "egy" "Egyptian (Ancient)",
                "kau" "Kanuri",
                "roh" "Romansh",
                "eka" "Ekajuk",
                "sam" "Samaritan Aramaic",
                "sot" "Sotho, Southern",
                "tum" "Tumbuka",
                "hun" "Hungarian",
                "lol" "Mongo",
                "mon" "Mongolian",
                "men" "Mende",
                "sqi" "Albanian",
                "ilo" "Iloko",
                "iku" "Inuktitut",
                "gaa" "Ga",
                "hai" "Haida",
                "paa" "Papuan languages",
                "chr" "Cherokee",
                "ori" "Oriya",
                "rus" "Russian",
                "sco" "Scots",
                "ber" "Berber languages",
                "iba" "Iban",
                "nau" "Nauru",
                "bod" "Tibetan",
                "nde" "Ndebele, North; North Ndebele",
                "krl" "Karelian",
                "jbo" "Lojban",
                "arg" "Aragonese",
                "nor" "Norwegian",
                "sla" "Slavic languages",
                "fij" "Fijian",
                "ave" "Avestan",
                "pal" "Pahlavi",
                "zho" "Chinese",
                "kut" "Kutenai",
                "zun" "Zuni",
                "isl" "Icelandic",
                "tir" "Tigrinya",
                "kmb" "Kimbundu",
                "scn" "Sicilian",
                "arn" "Mapudungun; Mapuche",
                "ach" "Acoli",
                "awa" "Awadhi",
                "kat" "Georgian",
                "grc" "Greek, Ancient (to 1453)",
                "sus" "Susu",
                "cau" "Caucasian languages",
                "baq" "Basque",
                "mlt" "Maltese",
                "amh" "Amharic",
                "sio" "Siouan languages",
                "ada" "Adangme",
                "glg" "Galician",
                "swe" "Swedish",
                "hin" "Hindi",
                "ina" "Interlingua (International Auxiliary Language Association)",
                "lug" "Ganda",
                "mai" "Maithili",
                "vot" "Votic",
                "ceb" "Cebuano",
                "sga" "Irish, Old (to 900)",
                "ypk" "Yupik languages",
                "pau" "Palauan",
                "mac" "Macedonian",
                "cym" "Welsh",
                "ces" "Czech",
                "ine" "Indo-European languages",
                "wak" "Wakashan languages",
                "mwr" "Marwari",
                "bas" "Basa",
                "den" "Slave (Athapascan)",
                "bla" "Siksika",
                "yap" "Yapese",
                "aka" "Akan",
                "glv" "Manx",
                "mos" "Mossi",
                "hmo" "Hiri Motu",
                "frm" "French, Middle (ca.1400-1600)",
                "chk" "Chuukese",
                "sma" "Southern Sami",
                "wal" "Wolaitta; Wolaytta",
                "kok" "Konkani",
                "bua" "Buriat",
                "doi" "Dogri",
                "bak" "Bashkir",
                "mni" "Manipuri",
                "abk" "Abkhazian",
                "oji" "Ojibwa",
                "que" "Quechua",
                "tvl" "Tuvalu",
                "yao" "Yao",
                "asm" "Assamese",
                "ara" "Arabic",
                "sai" "South American Indian languages",
                "mao" "Maori",
                "gla" "Gaelic; Scottish Gaelic",
                "zha" "Zhuang; Chuang",
                "cpp" "Creoles and pidgins, Portuguese-based",
                "tut" "Altaic languages",
                "suk" "Sukuma",
                "kho" "Khotanese; Sakan",
                "sgn" "Sign Languages",
                "tel" "Telugu",
                "lez" "Lezghian",
                "vie" "Vietnamese",
                "san" "Sanskrit",
                "urd" "Urdu",
                "tiv" "Tiv",
                "dum" "Dutch, Middle (ca.1050-1350)",
                "new" "Nepal Bhasa; Newari",
                "mkd" "Macedonian",
                "kal" "Kalaallisut; Greenlandic",
                "dar" "Dargwa",
                "myv" "Erzya",
                "pro" "Provençal, Old (to 1500);Occitan, Old (to 1500)",
                "pra" "Prakrit languages",
                "cad" "Caddo",
                "qaa-qtz" "Reserved for local use",
                "hup" "Hupa",
                "arw" "Arawak",
                "bel" "Belarusian",
                "shn" "Shan",
                "snd" "Sindhi",
                "lun" "Lunda",
                "kpe" "Kpelle",
                "fra" "French",
                "ava" "Avaric",
                "run" "Rundi",
                "fas" "Persian",
                "som" "Somali",
                "btk" "Batak languages",
                "lin" "Lingala",
                "bem" "Bemba",
                "tuk" "Turkmen",
                "rom" "Romany",
                "kab" "Kabyle",
                "tem" "Timne",
                "hau" "Hausa",
                "goh" "German, Old High (ca.750-1050)",
                "srp" "Serbian",
                "alb" "Albanian",
                "eng" "English",
                "nai" "North American Indian languages",
                "mya" "Burmese",
                "pan" "Panjabi; Punjabi",
                "gwi" "Gwich'in",
                "sas" "Sasak",
                "smi" "Sami languages",
                "che" "Chechen",
                "dgr" "Dogrib",
                "yid" "Yiddish",
                "uig" "Uighur; Uyghur",
                "snk" "Soninke",
                "ale" "Aleut",
                "hmn" "Hmong; Mong",
                "phn" "Phoenician",
                "nld" "Dutch; Flemish",
                "sem" "Semitic languages",
                "syr" "Syriac",
                "osa" "Osage",
                "tur" "Turkish",
                "tet" "Tetum",
                "kaw" "Kawi",
                "mnc" "Manchu",
                "khm" "Central Khmer",
                "sme" "Northern Sami",
                "dak" "Dakota",
                "iro" "Iroquoian languages",
                "sux" "Sumerian",
                "zen" "Zenaga",
                "bih" "Bihari languages",
                "hat" "Haitian; Haitian Creole",
                "fil" "Filipino; Pilipino",
                "kbd" "Kabardian",
                "pol" "Polish",
                "oto" "Otomian languages",
                "chp" "Chipewyan; Dene Suline",
                "tig" "Tigre",
                "del" "Delaware",
                "csb" "Kashubian",
                "ind" "Indonesian",
                "rum" "Romanian",
                "sel" "Selkup",
                "sin" "Sinhala; Sinhalese",
                "fao" "Faroese",
                "ido" "Ido",
                "ice" "Icelandic",
                "kik" "Kikuyu; Gikuyu",
                "tlh" "Klingon; tlhIngan-Hol",
                "zbl" "Blissymbols; Blissymbolics; Bliss",
                "orm" "Oromo",
                "was" "Washo",
                "pag" "Pangasinan",
                "loz" "Lozi",
                "bal" "Baluchi",
                "bej" "Beja; Bedawiyet",
                "arp" "Arapaho",
                "ssw" "Swati",
                "man" "Mandingo",
                "mag" "Magahi",
                "mwl" "Mirandese",
                "ewo" "Ewondo",
                "dzo" "Dzongkha",
                "lui" "Luiseno",
                "inc" "Indic languages",
                "mic" "Mi'kmaq; Micmac",
                "smn" "Inari Sami",
                "cre" "Cree",
                "smj" "Lule Sami",
                "aus" "Australian languages",
                "udm" "Udmurt",
                "sit" "Sino-Tibetan languages",
                "kaz" "Kazakh",
                "dyu" "Dyula",
                "slv" "Slovenian",
                "lim" "Limburgan; Limburger; Limburgish",
                "arm" "Armenian",
                "chg" "Chagatai",
                "hil" "Hiligaynon",
                "efi" "Efik",
                "tai" "Tai languages",
                "alt" "Southern Altai",
                "tso" "Tsonga",
                "afr" "Afrikaans",
                "zul" "Zulu",
                "hrv" "Croatian",
                "niu" "Niuean",
                "oci" "Occitan (post 1500)",
                "jrb" "Judeo-Arabic",
                "ven" "Venda",
                "sms" "Skolt Sami",
                "wol" "Wolof",
                "bho" "Bhojpuri",
                "mah" "Marshallese",
                "alg" "Algonquian languages",
                "gmh" "German, Middle High (ca.1050-1500)",
                "bin" "Bini; Edo",
                "tyv" "Tuvinian",
                "wen" "Sorbian languages",
                "spa" "Spanish; Castilian",
                "rap" "Rapanui",
                "ota" "Turkish, Ottoman (1500-1928)",
                "mus" "Creek",
                "cus" "Cushitic languages",
                "kir" "Kirghiz; Kyrgyz",
                "lav" "Latvian",
                "bik" "Bikol",
                "gsw" "Swiss German; Alemannic; Alsatian",
                "ewe" "Ewe",
                "gre" "Greek, Modern ",
                "dra" "Dravidian languages",
                "tog" "Tonga (Nyasa)",
                "nic" "Niger-Kordofanian languages",
                "din" "Dinka",
                "mun" "Munda languages",
                "gez" "Geez",
                "mkh" "Mon-Khmer languages",
                "moh" "Mohawk",
                "ibo" "Igbo",
                "srd" "Sardinian",
                "uzb" "Uzbek",
                "ssa" "Nilo-Saharan languages",
                "ron" "Romanian; Moldavian; Moldovan",
                "mak" "Makasar",
                "crh" "Crimean Tatar; Crimean Turkish",
                "cos" "Corsican",
                "chn" "Chinook jargon",
                "arc" "Official Aramaic (700-300 BCE); Imperial Aramaic (700-300 BCE)",
                "lua" "Luba-Lulua",
                "tkl" "Tokelau",
                "frs" "Eastern Frisian",
                "akk" "Akkadian",
                "cmc" "Chamic languages",
                "nav" "Navajo; Navaho",
                "non" "Norse, Old",
                "cha" "Chamorro",
                "mar" "Marathi",
                "ukr" "Ukrainian",
                "fiu" "Finno-Ugrian languages",
                "bat" "Baltic languages",
                "sal" "Salishan languages",
                "kum" "Kumyk",
                "sun" "Sundanese",
                "per" "Persian",
                "may" "Malay",
                "gem" "Germanic languages",
                "tat" "Tatar",
                "ady" "Adyghe; Adygei",
                "umb" "Umbundu",
                "mul" "Multiple languages",
                "ile" "Interlingue; Occidental",
                "kaa" "Kara-Kalpak",
                "bis" "Bislama",
                "kin" "Kinyarwanda",
                "hye" "Armenian",
                "chy" "Cheyenne",
                "fon" "Fon",
                "div" "Divehi; Dhivehi; Maldivian",
                "tha" "Thai",
                "srn" "Sranan Tongo",
                "ang" "English, Old (ca.450-1100)",
                "bad" "Banda languages",
                "cor" "Cornish",
                "ell" "Greek, Modern (1453-)",
                "lao" "Lao",
                "pap" "Papiamento",
                "roa" "Romance languages",
                "krc" "Karachay-Balkar",
                "smo" "Samoan",
                "tam" "Tamil",
                "tpi" "Tok Pisin",
                "ltz" "Luxembourgish; Letzeburgesch",
                "xal" "Kalmyk; Oirat",
                "vai" "Vai",
                "lat" "Latin",
                "ben" "Bengali",
                "dsb" "Lower Sorbian",
                "mri" "Maori",
                "cpf" "Creoles and pidgins, French-based",
                "zgh" "Standard Moroccan Tamazight",
                "nub" "Nubian languages",
                "srr" "Serer",
                "crp" "Creoles and pidgins",
                "chu"
                "Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic",
                "kon" "Kongo",
                "ful" "Fulah",
                "hit" "Hittite",
                "chb" "Chibcha",
                "epo" "Esperanto",
                "pus" "Pushto; Pashto",
                "kro" "Kru languages",
                "xho" "Xhosa",
                "vol" "Volapük",
                "gor" "Gorontalo",
                "sna" "Shona",
                "car" "Galibi Carib",
                "mno" "Manobo languages",
                "kac" "Kachin; Jingpho",
                "bos" "Bosnian",
                "nog" "Nogai",
                "cpe" "Creoles and pidgins, English based",
                "kos" "Kosraean",
                "cel" "Celtic languages",
                "heb" "Hebrew",
                "mal" "Malayalam",
                "nah" "Nahuatl languages",
                "rar" "Rarotongan; Cook Islands Maori",
                "yor" "Yoruba",
                "sog" "Sogdian",
                "nwc" "Classical Newari; Old Newari; Classical Nepal Bhasa",
                "fin" "Finnish",
                "chv" "Chuvash",
                "khi" "Khoisan languages",
                "sad" "Sandawe",
                "uga" "Ugaritic",
                "fat" "Fanti",
                "bam" "Bambara",
                "pli" "Pali",
                "slk" "Slovak",
                "gay" "Gayo",
                "kar" "Karen languages",
                "anp" "Angika",
                "tup" "Tupi languages",
                "kam" "Kamba",
                "bnt" "Bantu languages",
                "grn" "Guarani",
                "ira" "Iranian languages",
                "myn" "Mayan languages",
                "guj" "Gujarati",
                "afa" "Afro-Asiatic languages",
                "cop" "Coptic",
                "fre" "French",
                "sag" "Sango",
                "bur" "Burmese",
                "kom" "Komi",
                "cho" "Choctaw",
                "nyo" "Nyoro",
                "aym" "Aymara",
                "day" "Land Dayak languages",
                "kha" "Khasi",
                "nbl" "Ndebele, South; South Ndebele",
                "apa" "Apache languages",
                "zza" "Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki",
                "dut" "Dutch; Flemish",
                "bai" "Bamileke languages",
                "ita" "Italian",
                "kur" "Kurdish",
                "cze" "Czech",
                "eus" "Basque",
                "tmh" "Tamashek",
                "inh" "Ingush",
                "ace" "Achinese",
                "ast" "Asturian; Bable; Leonese; Asturleonese",
                "mga" "Irish, Middle (900-1200)",
                "msa" "Malay",
                "deu" "German",
                "mas" "Masai",
                "ter" "Tereno",
                "ton" "Tonga (Tonga Islands)",
                "jpr" "Judeo-Persian",
                "jpn" "Japanese",
                "art" "Artificial languages",
                "raj" "Rajasthani",
                "bul" "Bulgarian",
                "nym" "Nyamwezi",
                "gon" "Gondi",
                "peo" "Persian, Old (ca.600-400 B.C.)",
                "bug" "Buginese",
                "swa" "Swahili",
                "phi" "Philippine languages",
                "wel" "Welsh",
                "cat" "Catalan; Valencian",
                "zap" "Zapotec",
                "tsi" "Tsimshian",
                "est" "Estonian",
                "haw" "Hawaiian",
                "sat" "Santali",
                "dan" "Danish",
                "son" "Songhai languages",
                "lah" "Lahnda",
                "iii" "Sichuan Yi; Nuosu",
                "nds" "Low German; Low Saxon; German, Low; Saxon, Low",
                "ndo" "Ndonga",
                "lit" "Lithuanian",
                "mis" "Uncoded languages",
                "lad" "Ladino",
                "kan" "Kannada",
                "fur" "Friulian",
                "syc" "Classical Syriac",
                "mlg" "Malagasy",
                "her" "Herero",
                "ath" "Athapascan languages",
                "jav" "Javanese",
                "bra" "Braj",
                "twi" "Twi",
                "por" "Portuguese",
                "nia" "Nias",
                "tli" "Tlingit",
                "nep" "Nepali",
                "aar" "Afar",
                "afh" "Afrihili",
                "hsb" "Upper Sorbian",
                "sah" "Yakut",
                "nap" "Neapolitan",
                "fro" "French, Old (842-ca.1400)",
                "nob" "Bokmål, Norwegian; Norwegian Bokmål",
                "sid" "Sidamo",
                "wln" "Walloon",
                "aze" "Azerbaijani",
                "enm" "English, Middle (1100-1500)",
                "bre" "Breton",
                "lub" "Luba-Katanga"
                "gml" "Middle Low German"
                "xno" "Anglo-Norman"
                "p_ine" "Proto Indo-European"
                "p_gmw" "Proto West Germanic"
                "see" "Seneca"})
