"""LinguaScrape ML / neurosymbolic workspace.

Phase 2 of ``NEUROSYMBOLIC_ROADMAP.md``: the first fact->model loop
(triples export, PyKEEN baselines, ProbLog emitter, consistency ratchet)
built on the current corpus scale so later corpus growth is measurable.

Reproducibility is enforced structurally: pinned seeds, committed split
manifests, DVC-tracked datasets, and MLflow-logged runs.
"""

from linguascrape_ml.baselines import (
    BASELINE_SEED,
    DEFAULT_MODELS,
    METRIC_KEYS,
    BaselineOutcome,
    generate_predictions,
    load_split_factories,
    render_baselines_doc,
    train_baseline,
)
from linguascrape_ml.consistency import (
    ANTISYMMETRIC_RELATIONS,
    DESCENT_RELATION,
    SYMMETRIC_RELATIONS,
    ConsistencyReport,
    build_baseline,
    compare_to_baseline,
    evaluate_consistency,
    load_edge_constraints,
    parse_predictions,
    render_predictions,
)
from linguascrape_ml.finetune import (
    FineTuneConfig,
    FineTuneResult,
    assemble_dataset,
    before_after_report,
    build_qa_instruction,
    build_verbalization_instruction,
    evaluate_systems,
    format_prompt,
    format_training_text,
    require_finetune_deps,
    resolve_device,
)
from linguascrape_ml.kgqa import (
    QAExample,
    apply_polish,
    build_graph,
    split_examples,
)
from linguascrape_ml.queries import (
    TARGET_RELATIONS,
    GenStats,
    Query,
    corruption_pool,
    entity_types,
    generate_queries,
    serialize_queries,
)
from linguascrape_ml.scallop import (
    SMOKE_TARGETS,
    RegistryRule,
    SkippedRule,
    TranslatedRule,
    TranslationResult,
    UntranslatableClause,
    build_scl,
    intern_symbols,
    load_registry,
    load_relations,
    reference_derivations,
    transitive_closure,
    translate_clause,
    translate_registry,
    translate_rule,
)
from linguascrape_ml.tracking import (
    DEFAULT_EXPERIMENT,
    default_tracking_uri,
    start_run,
    tracking_uri,
)
from linguascrape_ml.triples import (
    EXCLUDED_RELATIONS,
    Triple,
    build_manifest,
    load_triples,
    split_triples,
)
from linguascrape_ml.verbalize import (
    ATTRIBUTE_TEMPLATES,
    EDGE_TEMPLATES,
    Example,
    NodeInfo,
    build_examples,
    load_edge_rows,
    load_nodes,
    serialize_examples,
)

__all__ = [
    "ANTISYMMETRIC_RELATIONS",
    "ATTRIBUTE_TEMPLATES",
    "BASELINE_SEED",
    "DEFAULT_EXPERIMENT",
    "DEFAULT_MODELS",
    "DESCENT_RELATION",
    "EDGE_TEMPLATES",
    "EXCLUDED_RELATIONS",
    "METRIC_KEYS",
    "SMOKE_TARGETS",
    "SYMMETRIC_RELATIONS",
    "TARGET_RELATIONS",
    "BaselineOutcome",
    "ConsistencyReport",
    "Example",
    "FineTuneConfig",
    "FineTuneResult",
    "GenStats",
    "NodeInfo",
    "QAExample",
    "Query",
    "RegistryRule",
    "SkippedRule",
    "TranslatedRule",
    "TranslationResult",
    "Triple",
    "UntranslatableClause",
    "apply_polish",
    "assemble_dataset",
    "before_after_report",
    "build_baseline",
    "build_examples",
    "build_graph",
    "build_manifest",
    "build_qa_instruction",
    "build_scl",
    "build_verbalization_instruction",
    "compare_to_baseline",
    "corruption_pool",
    "default_tracking_uri",
    "entity_types",
    "evaluate_consistency",
    "evaluate_systems",
    "format_prompt",
    "generate_queries",
    "format_training_text",
    "generate_predictions",
    "intern_symbols",
    "load_edge_constraints",
    "load_edge_rows",
    "load_nodes",
    "load_registry",
    "load_relations",
    "load_split_factories",
    "load_triples",
    "parse_predictions",
    "reference_derivations",
    "render_baselines_doc",
    "render_predictions",
    "require_finetune_deps",
    "resolve_device",
    "serialize_examples",
    "serialize_queries",
    "split_examples",
    "split_triples",
    "transitive_closure",
    "translate_clause",
    "translate_registry",
    "translate_rule",
    "start_run",
    "tracking_uri",
    "train_baseline",
    "__version__",
]

__version__ = "0.1.0"
