"""Rule-guided link prediction — the neurosymbolic pilot's core (Phase 5, US-003).

A **differentiable rule-guided link predictor**: a neural edge scorer (over the
committed PyKEEN entity embeddings) provides soft edge probabilities, and the
corpus's Horn rules propagate that evidence through the graph before the loss is
taken. The pilot's target is ``DESCENDS_FROM`` (with the recursive *ancestor*
transitive-closure rule — the "ancestor chains" of the acceptance criterion) plus
``BORROWED_FROM`` (no sound transitive rule — scored by the neural predicate alone,
documented honestly).

**The model.** For a candidate edge ``(h, r, t)``:

* the neural predicate scores the direct edge, ``p_direct = σ(MLP_r([h; t; h⊙t;
  |h−t|]))`` over the frozen embeddings — the *soft edge probability* the pilot needs;
* the symbolic layer takes the ``train`` base facts of ``r``, each weighted by the
  **same** neural predicate, and propagates them through the ancestor rule under
  Scallop's **min-max-prob** provenance: ``Pr[ancestor(h, t)] = max over paths of
  (min edge probability along the path)`` — the exact bottleneck-/widest-path
  semantics, computed here by :func:`minmax_widths` (a bounded-hop, fully
  differentiable relaxation);
* the rule-guided score is their disjunction, ``score = max(p_direct,
  Pr[ancestor(h, t)])`` — under min-max-prob a rule with two bodies (direct + the
  recursive one) *is* the max of the two.

So the neural scorer learns edge probabilities that are useful **both** directly and
after the rule propagates them across multi-hop descent chains; a held-out edge that
no direct signal reaches can still be scored through a chain of soft train edges.

**Why this is the faithful Scallop program.** The very same rule
(``ancestor(x, y) = descends_from(x, y); descends_from(x, z) and ancestor(z, y)``)
under scallopy's ``minmaxprob`` provenance computes exactly :func:`minmax_widths`, so
the engine-free reference here and the scallopy backend
(:func:`build_scl_program` / the local-only run in
:mod:`linguascrape_ml.train_scallop`) agree by construction — the same discipline
US-001 used to validate the boolean smoke against
:func:`linguascrape_ml.scallop.transitive_closure` when scallopy could not run on
this Linux/py3.11 host. With every edge probability set to ``1.0`` the min-max
reachable set collapses to that boolean transitive closure, which is the tie-in the
tests assert.

Everything here keeps ``torch`` imports **lazy** (module top stays light, so
``import linguascrape_ml`` never pulls the heavy stack — the workspace rule the
baselines/finetune modules follow). The pure pieces — the min-max semantics, the
ranking metrics, the helped/hurt/neutral verdict, the ``.scl`` emission, and the
doc-section renderer — are unit-tested on tiny fixtures in CI; the actual training
run (torch, local) lives in the thin CLI :mod:`linguascrape_ml.train_scallop`.
"""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass, field, fields
from pathlib import Path
from typing import TYPE_CHECKING, Any

from linguascrape_ml.consistency import node_type_of
from linguascrape_ml.triples import Triple

if TYPE_CHECKING:  # pragma: no cover - typing only
    import torch

# The metric keys the pilot reports, matching the PyKEEN baseline doc exactly so the
# two sides of the comparison line up column-for-column.
METRIC_KEYS: tuple[str, ...] = ("mrr", "hits@1", "hits@3", "hits@10")

# Rank cutoffs for the Hits@k above (parsed from METRIC_KEYS' hits@ entries).
_HITS_KS: tuple[int, ...] = (1, 3, 10)

# Doc markers for the comparison block upserted into docs/ml-baselines.md — the same
# cooperating-CLIs discipline as the KGQA tier-3 block (kgqa_eval.DOC_MARK_*), so a
# `train-baselines` rewrite and this pilot never clobber each other's section.
DOC_MARK_START = (
    "<!-- SCALLOP-PILOT:START (generated by linguascrape-train-scallop) -->"
)
DOC_MARK_END = "<!-- SCALLOP-PILOT:END -->"


# --- configuration -----------------------------------------------------------


@dataclass(frozen=True)
class PilotConfig:
    """Config-driven hyperparameters for one rule-guided pilot run.

    Fully describes a run so it is reproducible from the committed
    ``ml/configs/scallop-pilot.json``: which PyKEEN embeddings feed the neural
    predicate, which relations are targeted, which of them get the recursive
    ancestor rule, the min-max propagation depth, and the training knobs. Frozen +
    round-trippable (``from_dict``/``to_dict``) so the config is itself an artifact.
    """

    # The PyKEEN baseline whose entity embeddings feed the neural predicate (and
    # whose committed metrics are the side-by-side baseline). TransE is real-valued;
    # ComplEx/RotatE are complex — the CLI takes the magnitude for those.
    embeddings_model: str = "transe"
    embeddings_path: str = "data/embeddings/{model}/entity_embeddings.npy"
    entities_path: str = "data/triples/entities.tsv"
    triples_dir: str = "data/triples"
    queries_path: str = "data/queries/queries.jsonl"

    # Link-prediction targets and the subset that carry the recursive ancestor rule.
    # Borrowing is not transitively sound, so BORROWED_FROM stays direct-only.
    target_relations: tuple[str, ...] = ("DESCENDS_FROM", "BORROWED_FROM")
    transitive_relations: tuple[str, ...] = ("DESCENDS_FROM",)

    # Min-max propagation depth (paths up to 2**hops long reach a fixpoint on a
    # shallow genealogy; 3 covers the corpus's descent chains with headroom).
    hops: int = 3

    # Neural predicate + training.
    hidden_dim: int = 32
    epochs: int = 40
    learning_rate: float = 0.01
    weight_decay: float = 0.0
    seed: int = 20260713
    device: str | None = None  # None -> cpu (reproducible; MPS/CUDA are non-det)

    # Filtered ranking (exclude other known-true edges when ranking a target) —
    # the realistic protocol PyKEEN's filtered metrics use.
    filtered: bool = True
    # Candidate pool for ranking. False = the FULL entity vocabulary, matching
    # PyKEEN's evaluator so the side-by-side is apples-to-apples (the committed
    # baseline). True = restrict to the schema-type-compatible entities on the
    # ranked end (an easier task — reported separately, never vs the baseline).
    typed_candidates: bool = False

    @classmethod
    def from_dict(cls, data: dict[str, object]) -> PilotConfig:
        known = {f.name for f in fields(cls)}
        unknown = set(data) - known
        if unknown:
            raise ValueError(f"unknown config keys: {sorted(unknown)}")
        payload = dict(data)
        for key in ("target_relations", "transitive_relations"):
            if payload.get(key) is not None:
                payload[key] = tuple(payload[key])  # type: ignore[arg-type]
        return cls(**payload)  # type: ignore[arg-type]

    @classmethod
    def from_json(cls, path: Path | str) -> PilotConfig:
        return cls.from_dict(json.loads(Path(path).read_text(encoding="utf-8")))

    def to_dict(self) -> dict[str, object]:
        data = asdict(self)
        data["target_relations"] = list(self.target_relations)
        data["transitive_relations"] = list(self.transitive_relations)
        return data

    def resolved(self, base: Path) -> PilotConfig:
        """A copy with dataset paths resolved against ``base`` (the ml root)."""
        base = Path(base)

        def _abs(p: str) -> str:
            path = Path(p.format(model=self.embeddings_model))
            return str(path if path.is_absolute() else (base / path))

        return PilotConfig.from_dict(
            {
                **self.to_dict(),
                "embeddings_path": _abs(self.embeddings_path),
                "entities_path": _abs(self.entities_path),
                "triples_dir": _abs(self.triples_dir),
                "queries_path": _abs(self.queries_path),
            }
        )


# --- vocab / entity typing ---------------------------------------------------


def load_entity_index(path: Path | str) -> dict[str, int]:
    """Parse ``entities.tsv`` (``index<TAB>csid``) into ``{csid: index}``.

    The embeddings matrix is row-aligned to this index order (see the baselines
    metadata), so this is the single join between a csid and its embedding row.
    """
    mapping: dict[str, int] = {}
    for line in Path(path).read_text(encoding="utf-8").splitlines():
        if not line:
            continue
        idx, label = line.split("\t")
        mapping[label] = int(idx)
    return mapping


def type_index(entities: list[str]) -> dict[str, list[int]]:
    """Group entity indices by node type (read off the csid) for typed ranking.

    A candidate set restricted to the type allowed on the ranked end keeps the
    ranking honest (the same type-respecting stance as the US-002 negatives) and
    comparable to the schema-constrained corruption pools.
    """
    by_type: dict[str, list[int]] = {}
    for i, csid in enumerate(entities):
        node_type = node_type_of(csid) or "?"
        by_type.setdefault(node_type, []).append(i)
    return by_type


# --- training queries --------------------------------------------------------


@dataclass(frozen=True)
class TrainingQuery:
    """One labelled query for the loss — a positive or type-constrained negative."""

    relation: str
    head: int
    tail: int
    label: int


def load_queries(
    path: Path | str, entity_index: dict[str, int], relations: tuple[str, ...]
) -> list[TrainingQuery]:
    """Load the US-002 queries JSONL into index-space :class:`TrainingQuery`s.

    Records whose endpoints are outside the embedding vocab (never at corpus scale —
    the vocab covers every corpus entity) are skipped so the loss only sees scorable
    pairs. Kept to the pilot's target relations.
    """
    out: list[TrainingQuery] = []
    for line in Path(path).read_text(encoding="utf-8").splitlines():
        if not line:
            continue
        rec = json.loads(line)
        if rec["relation"] not in relations:
            continue
        head = entity_index.get(rec["head"])
        tail = entity_index.get(rec["tail"])
        if head is None or tail is None:
            continue
        out.append(
            TrainingQuery(
                relation=rec["relation"],
                head=head,
                tail=tail,
                label=int(rec["label"]),
            )
        )
    return out


def base_edges(
    train_triples: list[Triple], entity_index: dict[str, int]
) -> dict[str, list[tuple[int, int]]]:
    """Per-relation ``train`` base facts as ``(head_idx, tail_idx)`` pairs.

    These are the observed facts the neural predicate weights and the ancestor rule
    propagates — the Scallop program's base relations.
    """
    grouped: dict[str, set[tuple[int, int]]] = {}
    for t in train_triples:
        head = entity_index.get(t.head)
        tail = entity_index.get(t.tail)
        if head is None or tail is None:
            continue
        grouped.setdefault(t.relation, set()).add((head, tail))
    return {rel: sorted(pairs) for rel, pairs in grouped.items()}


# --- min-max-prob rule propagation (engine-free reference) -------------------


def minmax_widths(
    sources: torch.Tensor,
    edge_src: torch.Tensor,
    edge_dst: torch.Tensor,
    edge_weight: torch.Tensor,
    num_nodes: int,
    hops: int,
) -> torch.Tensor:
    """Bounded-hop min-max (widest-path) reachability from each source node.

    Computes, for each source ``s`` and every node ``v``, the best **bottleneck**
    probability over directed paths ``s -> … -> v`` of length ``<= 2**hops``:
    ``width[s, v] = max over paths (min edge_weight along the path)`` — exactly
    Scallop's ``minmaxprob`` provenance for the recursive rule
    ``reach(x, y) = edge(x, y); edge(x, z) and reach(z, y)``. The self-reach
    ``width[s, s] = 1`` seeds the fixpoint (an empty path has an unbounded
    bottleneck, clamped to the max probability ``1``).

    Fully differentiable w.r.t. ``edge_weight`` (``torch.minimum`` +
    ``scatter_reduce`` amax both carry gradients), so a loss taken on a propagated
    score flows back into the neural predicate that produced the edge weights. The
    edges are directed ``edge_src -> edge_dst``; pass the reversed lists to get
    reachability *into* a node (used for head-corruption ranking).
    """
    import torch

    n_sources = int(sources.shape[0])
    width = torch.zeros(n_sources, num_nodes, dtype=edge_weight.dtype)
    width[torch.arange(n_sources), sources] = 1.0
    if edge_src.numel() == 0:
        return width
    dst_index = edge_dst.unsqueeze(0).expand(n_sources, -1)
    for _ in range(hops):
        # Candidate bottleneck reaching each edge's dst: min(width at its src, w).
        cand = torch.minimum(width[:, edge_src], edge_weight.unsqueeze(0))
        relaxed = width.scatter_reduce(1, dst_index, cand, reduce="amax")
        new_width = torch.maximum(width, relaxed)
        if bool(torch.equal(new_width, width)):
            break
        width = new_width
    return width


def boolean_reachable(
    edges: set[tuple[int, int]], source: int, num_nodes: int, hops: int
) -> set[int]:
    """Nodes reachable from *source* (excl. itself) via :func:`minmax_widths`, w=1.

    The oracle tie-in: with every edge weight ``1.0`` the min-max reachable set is
    the plain boolean transitive closure's successor set, so a test can assert the
    differentiable propagation reduces to the US-001 engine-free
    :func:`linguascrape_ml.scallop.transitive_closure` semantics.
    """
    import torch

    if not edges:
        return set()
    src = torch.tensor([e[0] for e in sorted(edges)], dtype=torch.long)
    dst = torch.tensor([e[1] for e in sorted(edges)], dtype=torch.long)
    weight = torch.ones(len(edges))
    width = minmax_widths(
        torch.tensor([source]), src, dst, weight, num_nodes, hops
    )[0]
    return {v for v in range(num_nodes) if v != source and float(width[v]) > 0.0}


# --- the neural predicate + rule-guided model --------------------------------


def build_model(embeddings: Any, config: PilotConfig) -> Any:
    """Construct the rule-guided model (a ``torch.nn.Module``) over frozen embeddings.

    The neural predicate is a small per-relation MLP over the pair feature
    ``[h; t; h⊙t; |h−t|]``; the embeddings are a frozen buffer (the PyKEEN vectors
    are the fixed representation the pilot builds on, per the roadmap). Defined
    inside the function so ``torch`` stays a lazy import.
    """
    import numpy as np
    import torch
    from torch import nn

    matrix = np.asarray(embeddings)
    if np.iscomplexobj(matrix):
        matrix = np.abs(matrix)  # ComplEx/RotatE -> magnitude (a real feature)
    tensor = torch.as_tensor(np.ascontiguousarray(matrix), dtype=torch.float32)

    class RuleGuidedModel(nn.Module):
        def __init__(self, emb: torch.Tensor) -> None:
            super().__init__()
            self.register_buffer("emb", emb)
            dim = emb.shape[1]
            self.scorers = nn.ModuleDict(
                {
                    rel: nn.Sequential(
                        nn.Linear(4 * dim, config.hidden_dim),
                        nn.ReLU(),
                        nn.Linear(config.hidden_dim, 1),
                    )
                    for rel in config.target_relations
                }
            )

        def _feat(self, head: torch.Tensor, tail: torch.Tensor) -> torch.Tensor:
            h = self.emb[head]
            t = self.emb[tail]
            return torch.cat([h, t, h * t, (h - t).abs()], dim=-1)

        def edge_prob(
            self, relation: str, head: torch.Tensor, tail: torch.Tensor
        ) -> torch.Tensor:
            """σ(MLP) soft edge probability for a batch of (head, tail) index pairs."""
            logit = self.scorers[relation](self._feat(head, tail)).squeeze(-1)
            return torch.sigmoid(logit)

    torch.manual_seed(config.seed)
    model = RuleGuidedModel(tensor)
    return model


def _combine(direct: torch.Tensor, propagated: torch.Tensor) -> torch.Tensor:
    """Disjunction of the direct + rule-propagated bodies (min-max-prob ⇒ max)."""
    import torch

    return torch.maximum(direct, propagated)


def _bce(scores: torch.Tensor, labels: torch.Tensor) -> torch.Tensor:
    """BCE on probabilities (scores are already in [0, 1]; clamp for a safe log)."""
    import torch

    p = scores.clamp(1e-6, 1.0 - 1e-6)
    return -(labels * torch.log(p) + (1.0 - labels) * torch.log(1.0 - p)).mean()


@dataclass
class TrainReport:
    """Per-epoch losses from a training run (for MLflow + the run summary)."""

    losses: list[float] = field(default_factory=list)


def train(
    model: Any,
    queries: list[TrainingQuery],
    base: dict[str, list[tuple[int, int]]],
    config: PilotConfig,
) -> TrainReport:  # pragma: no cover - exercised by the CI smoke via train_smoke
    """Train the neural predicate end-to-end through the rule layer (BCE loss).

    Delegates to :func:`run_training`, which the CI smoke drives on a fixture.
    """
    return run_training(model, queries, base, config)


def run_training(
    model: Any,
    queries: list[TrainingQuery],
    base: dict[str, list[tuple[int, int]]],
    config: PilotConfig,
    *,
    epochs: int | None = None,
) -> TrainReport:
    """The differentiable training loop — neural predicate + min-max rule layer.

    For each epoch: recompute every base edge's neural probability, propagate them
    with :func:`minmax_widths` to get ``Pr[ancestor(h, t)]`` for the transitive
    relations, combine with the direct edge probability, and take BCE against the
    query labels. Gradients flow through the rule layer into the scorer. Runs on
    CPU under a pinned seed (reproducible); ``epochs`` overrides the config for the
    CI smoke.
    """
    import torch

    n_epochs = config.epochs if epochs is None else epochs
    optimizer = torch.optim.Adam(
        model.parameters(),
        lr=config.learning_rate,
        weight_decay=config.weight_decay,
    )
    num_nodes = int(model.emb.shape[0])
    transitive = set(config.transitive_relations)
    report = TrainReport()

    # Group queries by relation; precompute the distinct heads (for reuse of the
    # per-head width row) for the transitive relations.
    by_rel: dict[str, list[TrainingQuery]] = {}
    for q in queries:
        by_rel.setdefault(q.relation, []).append(q)

    for _ in range(n_epochs):
        optimizer.zero_grad()
        total = torch.zeros(())
        counted = 0
        for relation, rel_queries in by_rel.items():
            heads = torch.tensor([q.head for q in rel_queries], dtype=torch.long)
            tails = torch.tensor([q.tail for q in rel_queries], dtype=torch.long)
            labels = torch.tensor([float(q.label) for q in rel_queries])
            direct = model.edge_prob(relation, heads, tails)

            if relation in transitive and base.get(relation):
                edges = base[relation]
                esrc = torch.tensor([a for a, _ in edges], dtype=torch.long)
                edst = torch.tensor([b for _, b in edges], dtype=torch.long)
                eweight = model.edge_prob(relation, esrc, edst)
                distinct = sorted({q.head for q in rel_queries})
                pos = {h: i for i, h in enumerate(distinct)}
                widths = minmax_widths(
                    torch.tensor(distinct, dtype=torch.long),
                    esrc,
                    edst,
                    eweight,
                    num_nodes,
                    config.hops,
                )
                rows = torch.tensor([pos[q.head] for q in rel_queries])
                propagated = widths[rows, tails]
                scores = _combine(direct, propagated)
            else:
                scores = direct

            total = total + _bce(scores, labels) * len(rel_queries)
            counted += len(rel_queries)

        loss = total / max(counted, 1)
        loss.backward()
        optimizer.step()
        report.losses.append(float(loss.detach()))
    return report


# --- ranking evaluation ------------------------------------------------------


@dataclass
class RankingMetrics:
    """Filtered link-prediction metrics (matching the PyKEEN baseline doc keys)."""

    mrr: float
    hits: dict[int, float]
    num_ranks: int

    def as_metrics(self) -> dict[str, float]:
        out = {"mrr": self.mrr}
        for k, v in self.hits.items():
            out[f"hits@{k}"] = v
        return out


def _all_scores(
    model: Any,
    relation: str,
    fixed: int,
    candidates: torch.Tensor,
    *,
    corrupt_head: bool,
    widths_row: torch.Tensor | None,
) -> torch.Tensor:
    """Rule-guided scores of ``fixed`` paired with every candidate on one end."""
    import torch

    fixed_col = torch.full_like(candidates, fixed)
    if corrupt_head:
        direct = model.edge_prob(relation, candidates, fixed_col)
    else:
        direct = model.edge_prob(relation, fixed_col, candidates)
    if widths_row is None:
        return direct
    propagated = widths_row[candidates]
    return _combine(direct, propagated)


def evaluate_ranking(
    model: Any,
    test_triples: list[Triple],
    base: dict[str, list[tuple[int, int]]],
    entity_index: dict[str, int],
    config: PilotConfig,
    *,
    known: set[tuple[str, int, int]] | None = None,
) -> RankingMetrics:  # pragma: no cover - exercised by the CI smoke on a fixture
    """Filtered MRR/Hits@k over the held-out ``test`` split, typed candidate sets.

    For every test triple both the tail query ``(h, r, ?)`` and the head query
    ``(?, r, t)`` are ranked against the type-compatible candidate set; filtered
    ranking removes other known-true edges (``known``) so a true edge that happens
    to also be predicted does not inflate the rank. Averaged over both directions.
    Delegates to :func:`run_ranking` (CI-smoke-driven).
    """
    return run_ranking(
        model, test_triples, base, entity_index, config, known=known
    )


def run_ranking(
    model: Any,
    test_triples: list[Triple],
    base: dict[str, list[tuple[int, int]]],
    entity_index: dict[str, int],
    config: PilotConfig,
    *,
    known: set[tuple[str, int, int]] | None = None,
) -> RankingMetrics:
    import torch

    entities = [csid for csid, _ in sorted(entity_index.items(), key=lambda kv: kv[1])]
    by_type = type_index(entities)
    num_nodes = len(entities)
    transitive = set(config.transitive_relations)
    known = known or set()

    ranks: list[int] = []
    with torch.no_grad():
        for relation in config.target_relations:
            rel_tests = [t for t in test_triples if t.relation == relation]
            if not rel_tests:
                continue
            head_cand, tail_cand = _candidate_pools(
                rel_tests, by_type, num_nodes, config.typed_candidates
            )

            # Forward + reverse width rows keyed by the fixed node of each query.
            fwd: dict[int, torch.Tensor] = {}
            rev: dict[int, torch.Tensor] = {}
            if relation in transitive and base.get(relation):
                edges = base[relation]
                esrc = torch.tensor([a for a, _ in edges], dtype=torch.long)
                edst = torch.tensor([b for _, b in edges], dtype=torch.long)
                eweight = model.edge_prob(relation, esrc, edst)
                heads = sorted({entity_index[t.head] for t in rel_tests})
                tails = sorted({entity_index[t.tail] for t in rel_tests})
                fwd_w = minmax_widths(
                    torch.tensor(heads, dtype=torch.long),
                    esrc, edst, eweight, num_nodes, config.hops,
                )
                rev_w = minmax_widths(
                    torch.tensor(tails, dtype=torch.long),
                    edst, esrc, eweight, num_nodes, config.hops,
                )
                fwd = {h: fwd_w[i] for i, h in enumerate(heads)}
                rev = {t: rev_w[i] for i, t in enumerate(tails)}

            for t in rel_tests:
                h = entity_index[t.head]
                tl = entity_index[t.tail]
                # Tail query (h, r, ?): rank tl among tail candidates.
                tail_scores = _all_scores(
                    model, relation, h, tail_cand,
                    corrupt_head=False, widths_row=fwd.get(h),
                )
                ranks.append(
                    _filtered_rank(
                        tail_scores, tail_cand, tl, relation, h,
                        corrupt_head=False, known=known, filtered=config.filtered,
                    )
                )
                # Head query (?, r, t): rank h among head candidates.
                head_scores = _all_scores(
                    model, relation, tl, head_cand,
                    corrupt_head=True, widths_row=rev.get(tl),
                )
                ranks.append(
                    _filtered_rank(
                        head_scores, head_cand, h, relation, tl,
                        corrupt_head=True, known=known, filtered=config.filtered,
                    )
                )

    return _metrics_from_ranks(ranks)


def _filtered_rank(
    scores: torch.Tensor,
    candidates: torch.Tensor,
    target: int,
    relation: str,
    fixed: int,
    *,
    corrupt_head: bool,
    known: set[tuple[str, int, int]],
    filtered: bool,
) -> int:
    """1-based rank of *target* among candidates, other known-trues filtered out.

    Ties are broken *pessimistically* (a candidate scoring equal to the target
    ranks ahead of it) so an untrained/degenerate model that scores everything the
    same gets the honest worst-case rank, never an accidental rank 1.
    """
    target_pos = (candidates == target).nonzero(as_tuple=True)[0]
    if target_pos.numel() == 0:
        return len(candidates) + 1  # target not in the typed pool — worst case
    target_score = scores[target_pos[0]]

    higher = scores > target_score
    equal = scores == target_score
    # Pessimistic tie-break: count equal-scoring candidates (minus the target).
    rank = int(higher.sum().item()) + int(equal.sum().item())  # target counted once
    if filtered:
        # Remove other known-true candidates that outrank/tie the target.
        cand_list = candidates.tolist()
        for pos, cand in enumerate(cand_list):
            if cand == target:
                continue
            triple = (
                (relation, cand, fixed) if corrupt_head else (relation, fixed, cand)
            )
            if triple in known and (bool(higher[pos]) or bool(equal[pos])):
                rank -= 1
    return max(rank, 1)


def _candidate_pools(
    rel_tests: list[Triple],
    by_type: dict[str, list[int]],
    num_nodes: int,
    typed: bool,
) -> tuple[torch.Tensor, torch.Tensor]:
    """Head/tail candidate index tensors — full vocab, or type-restricted."""
    import torch

    if not typed:
        allc = torch.arange(num_nodes, dtype=torch.long)
        return allc, allc
    head_types = sorted({node_type_of(t.head) or "?" for t in rel_tests})
    tail_types = sorted({node_type_of(t.tail) or "?" for t in rel_tests})
    head_pool = sorted({i for ty in head_types for i in by_type.get(ty, [])})
    tail_pool = sorted({i for ty in tail_types for i in by_type.get(ty, [])})
    return (
        torch.tensor(head_pool, dtype=torch.long),
        torch.tensor(tail_pool, dtype=torch.long),
    )


def _metrics_from_ranks(ranks: list[int]) -> RankingMetrics:
    """Mean reciprocal rank + Hits@k from a list of 1-based ranks."""
    if not ranks:
        return RankingMetrics(mrr=0.0, hits={k: 0.0 for k in _HITS_KS}, num_ranks=0)
    mrr = sum(1.0 / r for r in ranks) / len(ranks)
    hits = {
        k: sum(1 for r in ranks if r <= k) / len(ranks) for k in _HITS_KS
    }
    return RankingMetrics(mrr=mrr, hits=hits, num_ranks=len(ranks))


def top_completions(
    model: Any,
    test_triples: list[Triple],
    base: dict[str, list[tuple[int, int]]],
    entity_index: dict[str, int],
    config: PilotConfig,
) -> list[Triple]:  # pragma: no cover - exercised via the CLI (torch, local)
    """The model's top-1 head- and tail-completions of each test query.

    The same predictions-file shape the PyKEEN baselines feed the logical-consistency
    ratchet (:mod:`linguascrape_ml.consistency`), so the pilot's predictions run
    through the identical tier-2 check. Sorted + deduplicated.
    """
    import torch

    entities = [csid for csid, _ in sorted(entity_index.items(), key=lambda kv: kv[1])]
    by_type = type_index(entities)
    num_nodes = len(entities)
    transitive = set(config.transitive_relations)
    preds: set[Triple] = set()

    with torch.no_grad():
        for relation in config.target_relations:
            rel_tests = [t for t in test_triples if t.relation == relation]
            if not rel_tests:
                continue
            head_cand, tail_cand = _candidate_pools(
                rel_tests, by_type, num_nodes, config.typed_candidates
            )
            fwd: dict[int, torch.Tensor] = {}
            rev: dict[int, torch.Tensor] = {}
            if relation in transitive and base.get(relation):
                edges = base[relation]
                esrc = torch.tensor([a for a, _ in edges], dtype=torch.long)
                edst = torch.tensor([b for _, b in edges], dtype=torch.long)
                eweight = model.edge_prob(relation, esrc, edst)
                heads = sorted({entity_index[t.head] for t in rel_tests})
                tails = sorted({entity_index[t.tail] for t in rel_tests})
                fwd_w = minmax_widths(
                    torch.tensor(heads, dtype=torch.long),
                    esrc, edst, eweight, num_nodes, config.hops)
                rev_w = minmax_widths(
                    torch.tensor(tails, dtype=torch.long),
                    edst, esrc, eweight, num_nodes, config.hops)
                fwd = {h: fwd_w[i] for i, h in enumerate(heads)}
                rev = {t: rev_w[i] for i, t in enumerate(tails)}
            for t in rel_tests:
                h = entity_index[t.head]
                tl = entity_index[t.tail]
                tail_scores = _all_scores(
                    model, relation, h, tail_cand,
                    corrupt_head=False, widths_row=fwd.get(h))
                best_tail = int(tail_cand[int(tail_scores.argmax())])
                preds.add(Triple(relation, entities[h], entities[best_tail]))
                head_scores = _all_scores(
                    model, relation, tl, head_cand,
                    corrupt_head=True, widths_row=rev.get(tl))
                best_head = int(head_cand[int(head_scores.argmax())])
                preds.add(Triple(relation, entities[best_head], entities[tl]))
    return sorted(preds)


# --- scallopy backend (local-only — the faithful engine program) -------------


def build_scl_program(transitive_relations: tuple[str, ...]) -> str:
    """The Scallop ``.scl`` the pilot's rule layer implements, under ``minmaxprob``.

    A pure function of the relation names, committed-doc-friendly and asserted by a
    test. Each transitive relation gets the recursive ancestor closure whose
    ``minmaxprob`` extension is exactly :func:`minmax_widths`. Mirrors the
    US-001 translation surface (``ancestor(x, y) = descends_from(x, y); …``).
    """
    lines = [
        "// Rule-guided link-prediction program (NEUROSYMBOLIC_ROADMAP Phase 5,",
        "// US-003). Base edge probabilities are supplied by the neural predicate;",
        "// provenance = minmaxprob (Pr[ancestor] = max-path of min-edge-prob).",
        "",
    ]
    for rel in transitive_relations:
        head = f"ancestor_{rel.lower()}"
        lines += [
            f"type {rel.lower()}(String, String)",
            f"rel {head}(x, y) = {rel.lower()}(x, y)",
            f"rel {head}(x, y) = {rel.lower()}(x, z) and {head}(z, y)",
            "",
        ]
    return "\n".join(lines).rstrip("\n") + "\n"


def run_scallop_ancestor(
    base_pairs: list[tuple[str, str]],
    base_probs: list[float],
    relation: str,
) -> dict[tuple[str, str], float]:  # pragma: no cover - local-only (scallopy macOS)
    """Answer ``ancestor/2`` under ``minmaxprob`` in real scallopy.

    The engine counterpart of :func:`minmax_widths`: loads the probabilistic base
    facts, runs the recursive rule under ``minmaxprob`` provenance, and returns the
    derived ancestor probabilities. Local-only (scallopy's sole wheel is
    macOS/arm64 — see :func:`linguascrape_ml.export_scallop.require_scallop_deps`);
    a local test asserts it agrees with :func:`minmax_widths` on a fixture.
    """
    from linguascrape_ml.export_scallop import require_scallop_deps

    require_scallop_deps()
    import scallopy

    ctx = scallopy.ScallopContext(provenance="minmaxprob")
    rel = relation.lower()
    head = f"ancestor_{rel}"
    ctx.add_relation(rel, (str, str))
    ctx.add_facts(
        rel,
        [(prob, pair) for pair, prob in zip(base_pairs, base_probs, strict=True)],
    )
    ctx.add_rule(f"{head}(x, y) = {rel}(x, y)")
    ctx.add_rule(f"{head}(x, y) = {rel}(x, z) and {head}(z, y)")
    ctx.run()
    return {(h, t): float(p) for (p, (h, t)) in ctx.relation(head)}


# --- comparison + verdict (pure) ---------------------------------------------

# A relative MRR change below this magnitude is "neutral" (noise at this corpus
# scale, where the baseline MRR is ~1e-2); above it, "helped"/"hurt".
NEUTRAL_REL_TOLERANCE = 0.05


def classify_effect(
    baseline_mrr: float, rule_mrr: float, *, tolerance: float = NEUTRAL_REL_TOLERANCE
) -> str:
    """Whether rule guidance ``helped`` / ``hurt`` / was ``neutral`` on MRR.

    Relative to the baseline MRR so it is scale-free; within ``tolerance`` (or both
    ~zero) is ``neutral``. The single headline verdict the acceptance asks for.
    """
    if baseline_mrr <= 0.0 and rule_mrr <= 0.0:
        return "neutral"
    denom = baseline_mrr if baseline_mrr > 0.0 else rule_mrr
    rel = (rule_mrr - baseline_mrr) / denom
    if rel > tolerance:
        return "helped"
    if rel < -tolerance:
        return "hurt"
    return "neutral"


@dataclass
class Comparison:
    """The pilot result: rule-guided vs a direct-only ablation vs the PyKEEN baseline.

    ``verdict`` is the **ablation** — rule-guided vs the identical neural predicate
    with the rule turned off, both scored through the *same* harness, so it isolates
    the rule's contribution without the cross-harness confound of comparing to
    PyKEEN's own evaluator. ``baseline_metrics`` are the committed pure-PyKEEN
    numbers (`docs/ml-baselines.md`), shown as the reference floor the acceptance
    asks for the side-by-side against.
    """

    baseline_model: str
    baseline_metrics: dict[str, float]
    direct_metrics: dict[str, float]
    rule_metrics: dict[str, float]
    verdict: str
    direct_consistency: dict[str, int] | None = None
    rule_consistency: dict[str, int] | None = None
    num_ranks: int = 0

    def as_dict(self) -> dict[str, object]:
        return {
            "baselineModel": self.baseline_model,
            "baselineMetrics": self.baseline_metrics,
            "directMetrics": self.direct_metrics,
            "ruleMetrics": self.rule_metrics,
            "verdict": self.verdict,
            "directConsistency": self.direct_consistency,
            "ruleConsistency": self.rule_consistency,
            "numRanks": self.num_ranks,
        }


def _fmt(value: float) -> str:
    return f"{value:.4f}"


def render_comparison_section(comparison: Comparison, config: PilotConfig) -> str:
    """Render the marker-wrapped comparison block for ``docs/ml-baselines.md``.

    A **pure** function of the numbers (no wall-clock), so a re-run is a byte-stable
    diff and the block can be committed. Reports the headline verdict, the
    side-by-side link-prediction table, and (when supplied) the tier-2 consistency
    of the pilot's own predictions vs the baseline.
    """
    verdict_phrase = {
        "helped": "**helped** — the rule raised MRR over the direct-only ablation",
        "hurt": "**hurt** — the rule lowered MRR vs the direct-only ablation",
        "neutral": "**neutral** — no material MRR change vs the direct-only ablation",
    }[comparison.verdict]
    lines = [
        DOC_MARK_START,
        "",
        "## Rule-guided link prediction (Phase 5, US-003)",
        "",
        "The neurosymbolic pilot: a neural edge predicate over the "
        f"**{comparison.baseline_model}** embeddings, with the corpus's *ancestor* "
        "transitive-closure rule propagating its soft edge probabilities under "
        "Scallop's `minmaxprob` provenance (`Pr[ancestor] = max-path of "
        "min-edge-prob`), trained on the US-002 queries and evaluated on the same "
        "held-out `test` split as the baselines. The headline verdict is the "
        "**ablation** (rule on vs the identical predicate with the rule off, one "
        "harness); the PyKEEN row is the committed floor, measured by its own "
        "evaluator.",
        "",
        f"> **Verdict:** rule guidance {verdict_phrase}.",
        "",
        "| System | MRR | Hits@1 | Hits@3 | Hits@10 |",
        "| --- | --- | --- | --- | --- |",
    ]
    b, d, r = (
        comparison.baseline_metrics,
        comparison.direct_metrics,
        comparison.rule_metrics,
    )
    lines.append(
        f"| PyKEEN {comparison.baseline_model} (baseline floor) | {_fmt(b['mrr'])} | "
        f"{_fmt(b['hits@1'])} | {_fmt(b['hits@3'])} | {_fmt(b['hits@10'])} |"
    )
    lines.append(
        f"| Neural predicate, rule OFF (ablation) | {_fmt(d['mrr'])} | "
        f"{_fmt(d['hits@1'])} | {_fmt(d['hits@3'])} | {_fmt(d['hits@10'])} |"
    )
    lines.append(
        f"| Rule-guided (neural + ancestor rule) | {_fmt(r['mrr'])} | "
        f"{_fmt(r['hits@1'])} | {_fmt(r['hits@3'])} | {_fmt(r['hits@10'])} |"
    )
    lines += [
        "",
        f"Filtered ranks over {comparison.num_ranks} head/tail queries "
        f"(seed {config.seed}, {config.epochs} epochs, {config.hops}-hop min-max "
        "propagation, CPU). The neural-vs-PyKEEN gap reflects a different scorer "
        "*and* a different evaluator; the rule's own effect is the ablation rows.",
        "",
    ]
    if comparison.direct_consistency and comparison.rule_consistency:
        lines += [
            "### Logical consistency of the pilot's predictions (tier 2)",
            "",
            "Each system's top-1 completions of the target-relation test queries run "
            "through the same `linguascrape_ml.consistency` checks as the baselines — "
            "rule-off vs rule-on over the identical prediction set, so the rule's "
            "effect on logical consistency is isolated too.",
            "",
            "| System | Descent cycles | Schema type breaches | Asymmetry violations |",
            "| --- | --- | --- | --- |",
        ]
        for label, c in (
            ("Neural predicate, rule OFF", comparison.direct_consistency),
            ("Rule-guided", comparison.rule_consistency),
        ):
            lines.append(
                f"| {label} | {c['descentCycles']} | {c['schemaTypeBreaches']} | "
                f"{c['asymmetryViolations']} |"
            )
        lines.append("")
    lines += [
        "> Reproduce: `cd ml && uv run linguascrape-train-scallop` (needs the "
        "DVC-tracked embeddings + splits + queries; `uv run --project ml dvc pull` "
        "first). The engine-free min-max reference runs anywhere; the equivalent "
        "scallopy `minmaxprob` program (`build_scl_program`) is local-only "
        "(macOS/arm64 wheel). Full runbook: `docs/scallop-pilot.md` §US-003.",
        "",
        DOC_MARK_END,
    ]
    return "\n".join(lines) + "\n"


def extract_marked_section(doc_text: str) -> str | None:
    """The pilot comparison block (incl. markers) in *doc_text*, or ``None``."""
    start = doc_text.find(DOC_MARK_START)
    end = doc_text.find(DOC_MARK_END)
    if start == -1 or end == -1 or end < start:
        return None
    return doc_text[start : end + len(DOC_MARK_END)]


def upsert_marked_section(doc_text: str, section: str) -> str:
    """Insert or replace the pilot comparison block (idempotent; appends if absent)."""
    if not section:
        return doc_text
    existing = extract_marked_section(doc_text)
    body = section if section.endswith("\n") else section + "\n"
    if existing is not None:
        replaced = doc_text.replace(existing, body.rstrip("\n"), 1)
        return replaced if replaced.endswith("\n") else replaced + "\n"
    prefix = doc_text if doc_text.endswith("\n") else doc_text + "\n"
    return f"{prefix}\n{body}"


__all__ = [
    "DOC_MARK_END",
    "DOC_MARK_START",
    "METRIC_KEYS",
    "NEUTRAL_REL_TOLERANCE",
    "Comparison",
    "PilotConfig",
    "RankingMetrics",
    "TrainReport",
    "TrainingQuery",
    "base_edges",
    "boolean_reachable",
    "build_model",
    "build_scl_program",
    "classify_effect",
    "evaluate_ranking",
    "extract_marked_section",
    "load_entity_index",
    "load_queries",
    "minmax_widths",
    "render_comparison_section",
    "run_ranking",
    "run_scallop_ancestor",
    "run_training",
    "top_completions",
    "train",
    "type_index",
    "upsert_marked_section",
]
