"""pinakes ML / neurosymbolic workspace.

Phase 2 of the neurosymbolic roadmap: the first fact->model loop
(triples export, PyKEEN baselines, ProbLog emitter, consistency ratchet)
built on the current corpus scale so later corpus growth is measurable.

Reproducibility is enforced structurally: pinned seeds, committed split
manifests, git-ignored datasets, and MLflow-logged runs.
"""

from pinakes_ml.baselines import (
    BASELINE_SEED,
    DEFAULT_MODELS,
    METRIC_KEYS,
    BaselineOutcome,
    generate_predictions,
    load_split_factories,
    render_baselines_doc,
    train_baseline,
)
from pinakes_ml.consistency import (
    ANTISYMMETRIC_RELATIONS,
    DESCENT_RELATION,
    SYMMETRIC_RELATIONS,
    ConsistencyReport,
    build_baseline,
    compare_to_baseline,
    evaluate_consistency,
    load_edge_constraints,
    parse_predictions,
    render_predictions,
)
from pinakes_ml.deepproblog_pilot import (
    FeasibilityConfig,
    FeasResult,
    ScalePoint,
    count_paths,
    evaluate_program,
    ground_size,
    has_cycle,
    minmax_chain_width,
    problog_chain_marginal,
    problog_two_path_marginal,
    proof_multiplicity,
    reachable_multihop_pairs,
    render_deepproblog_program,
    render_probe_table,
    render_problog_program,
    require_deepproblog_deps,
    scale_probe,
    tractable_subgraph,
)
from pinakes_ml.finetune import (
    FineTuneConfig,
    FineTuneResult,
    assemble_dataset,
    before_after_report,
    build_qa_instruction,
    build_verbalization_instruction,
    evaluate_systems,
    format_prompt,
    format_training_text,
    require_finetune_deps,
    resolve_device,
)
from pinakes_ml.kgqa import (
    QAExample,
    apply_polish,
    build_graph,
    split_examples,
)
from pinakes_ml.queries import (
    TARGET_RELATIONS,
    GenStats,
    Query,
    corruption_pool,
    entity_types,
    generate_queries,
    serialize_queries,
)
from pinakes_ml.scallop import (
    SMOKE_TARGETS,
    RegistryRule,
    SkippedRule,
    TranslatedRule,
    TranslationResult,
    UntranslatableClause,
    build_scl,
    intern_symbols,
    load_registry,
    load_relations,
    reference_derivations,
    transitive_closure,
    translate_clause,
    translate_registry,
    translate_rule,
)
from pinakes_ml.scallop_train import (
    Comparison,
    PilotConfig,
    RankingMetrics,
    TrainingQuery,
    base_edges,
    boolean_reachable,
    build_model,
    build_scl_program,
    classify_effect,
    load_entity_index,
    load_queries,
    minmax_widths,
    render_comparison_section,
    run_ranking,
    run_training,
)
from pinakes_ml.tracking import (
    DEFAULT_EXPERIMENT,
    default_tracking_uri,
    start_run,
    tracking_uri,
)
from pinakes_ml.triples import (
    EXCLUDED_RELATIONS,
    Triple,
    build_manifest,
    load_triples,
    split_triples,
)
from pinakes_ml.verbalize import (
    ATTRIBUTE_TEMPLATES,
    EDGE_TEMPLATES,
    Example,
    NodeInfo,
    build_examples,
    load_edge_rows,
    load_nodes,
    serialize_examples,
)

__all__ = [
    "ANTISYMMETRIC_RELATIONS",
    "ATTRIBUTE_TEMPLATES",
    "BASELINE_SEED",
    "DEFAULT_EXPERIMENT",
    "DEFAULT_MODELS",
    "DESCENT_RELATION",
    "EDGE_TEMPLATES",
    "EXCLUDED_RELATIONS",
    "METRIC_KEYS",
    "SMOKE_TARGETS",
    "SYMMETRIC_RELATIONS",
    "TARGET_RELATIONS",
    "BaselineOutcome",
    "Comparison",
    "ConsistencyReport",
    "Example",
    "FeasResult",
    "FeasibilityConfig",
    "FineTuneConfig",
    "FineTuneResult",
    "GenStats",
    "ScalePoint",
    "NodeInfo",
    "PilotConfig",
    "QAExample",
    "Query",
    "RankingMetrics",
    "RegistryRule",
    "SkippedRule",
    "TranslatedRule",
    "TrainingQuery",
    "TranslationResult",
    "Triple",
    "UntranslatableClause",
    "apply_polish",
    "assemble_dataset",
    "base_edges",
    "before_after_report",
    "boolean_reachable",
    "build_baseline",
    "build_examples",
    "build_graph",
    "build_manifest",
    "build_model",
    "build_qa_instruction",
    "build_scl",
    "build_scl_program",
    "build_verbalization_instruction",
    "classify_effect",
    "compare_to_baseline",
    "corruption_pool",
    "count_paths",
    "default_tracking_uri",
    "entity_types",
    "evaluate_program",
    "ground_size",
    "has_cycle",
    "minmax_chain_width",
    "problog_chain_marginal",
    "problog_two_path_marginal",
    "proof_multiplicity",
    "reachable_multihop_pairs",
    "render_deepproblog_program",
    "render_probe_table",
    "render_problog_program",
    "require_deepproblog_deps",
    "scale_probe",
    "tractable_subgraph",
    "load_entity_index",
    "load_queries",
    "minmax_widths",
    "render_comparison_section",
    "run_ranking",
    "run_training",
    "evaluate_consistency",
    "evaluate_systems",
    "format_prompt",
    "generate_queries",
    "format_training_text",
    "generate_predictions",
    "intern_symbols",
    "load_edge_constraints",
    "load_edge_rows",
    "load_nodes",
    "load_registry",
    "load_relations",
    "load_split_factories",
    "load_triples",
    "parse_predictions",
    "reference_derivations",
    "render_baselines_doc",
    "render_predictions",
    "require_finetune_deps",
    "resolve_device",
    "serialize_examples",
    "serialize_queries",
    "split_examples",
    "split_triples",
    "transitive_closure",
    "translate_clause",
    "translate_registry",
    "translate_rule",
    "start_run",
    "tracking_uri",
    "train_baseline",
    "__version__",
]

__version__ = "0.1.0"
