"""CLI: the logical-consistency ratchet (ml US-005).

Recomputes the descent-acyclicity / canonical-schema-type / antisymmetry violation
counts from the **committed** per-model prediction files
(``ml/predictions/<model>.tsv``) and gates them against the committed baseline
``ml/manifests/consistency-baseline.json`` — a monotone ratchet, exactly like the
TS-side ``docs/convergence-qa-baseline.json`` drift gate.

This CLI is **pure Python** (no torch/pykeen), so it runs in CI over the committed
artifacts without the heavy statistical stack::

    uv run pinakes-check-consistency            # gate (exit 1 on regression)
    uv run pinakes-check-consistency --write-baseline   # deliberate re-baseline

The prediction files themselves are (re)generated by the local-only training CLI
:mod:`pinakes_ml.train_baselines`, which also writes the baseline; this CLI's
``--write-baseline`` is the escape hatch for a deliberate, reviewed re-baseline that
does not require retraining (the checks are pure over the committed predictions).
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from pinakes_ml.consistency import (
    build_baseline,
    compare_to_baseline,
    evaluate_consistency,
    load_edge_constraints,
    parse_predictions,
)

_ML_ROOT = Path(__file__).resolve().parents[2]
_REPO_ROOT = _ML_ROOT.parent

DEFAULT_PREDICTIONS_DIR = _ML_ROOT / "predictions"
DEFAULT_BASELINE = _ML_ROOT / "manifests" / "consistency-baseline.json"
DEFAULT_SCHEMA = _REPO_ROOT / "contracts" / "canonical-schema.json"

# The three baselines, lower-cased to match the committed prediction filenames.
DEFAULT_MODELS = ("transe", "complex", "rotate")


def _reports(predictions_dir: Path, schema: Path, models: list[str]):
    constraints = load_edge_constraints(schema)
    reports = []
    for model in models:
        path = predictions_dir / f"{model.lower()}.tsv"
        if not path.exists():
            raise FileNotFoundError(
                f"predictions not found: {path}\n"
                "Regenerate with `uv run pinakes-train-baselines` (local-only)."
            )
        triples = parse_predictions(path)
        reports.append(evaluate_consistency(model, triples, constraints))
    return reports


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--predictions-dir", type=Path, default=DEFAULT_PREDICTIONS_DIR)
    parser.add_argument("--baseline", type=Path, default=DEFAULT_BASELINE)
    parser.add_argument("--schema", type=Path, default=DEFAULT_SCHEMA)
    parser.add_argument(
        "--models", nargs="+", default=list(DEFAULT_MODELS),
        help="Model prediction files to check (default: transe complex rotate).",
    )
    parser.add_argument(
        "--write-baseline",
        action="store_true",
        help="Rewrite the committed baseline from the current predictions "
        "(a deliberate, reviewed re-baseline).",
    )
    args = parser.parse_args(argv)

    reports = _reports(args.predictions_dir, args.schema, args.models)

    if args.write_baseline:
        baseline = build_baseline(reports)
        args.baseline.parent.mkdir(parents=True, exist_ok=True)
        args.baseline.write_text(
            json.dumps(baseline, indent=2, sort_keys=True) + "\n", encoding="utf-8"
        )
        print(f"wrote consistency baseline -> {args.baseline}")
        return 0

    if not args.baseline.exists():
        parser.error(f"baseline not found: {args.baseline} (--write-baseline first)")

    baseline = json.loads(args.baseline.read_text(encoding="utf-8"))
    for report in reports:
        c = report.counts
        print(
            f"{report.model:<8} predictions={report.num_predictions:<5} "
            f"cycles={c['descentCycles']} type_breaches={c['schemaTypeBreaches']} "
            f"asymmetry={c['asymmetryViolations']}"
        )

    regressions = compare_to_baseline(reports, baseline)
    if regressions:
        print("\nCONSISTENCY RATCHET REGRESSION — predictions violate more rules "
              "than the committed baseline allows:")
        for reg in regressions:
            print(f"  {reg}")
        print(
            "\nIf this is a deliberate, reviewed change, re-baseline with "
            "`uv run pinakes-check-consistency --write-baseline` and document it."
        )
        return 1

    print("\nconsistency ratchet OK — no model exceeds its baseline.")
    return 0


if __name__ == "__main__":  # pragma: no cover - CLI entry
    raise SystemExit(main())
