"""CLI: merge → GGUF → Q4_K_M → llama.cpp parity check (slm-pilot US-004).

Reproducer for the pilot's deployment leg. From ``ml/``::

    uv run pinakes-export-gguf --contract-only    # the prompt contract (pure)
    uv run pinakes-export-gguf --check            # the contract freeze gate
    uv run pinakes-export-gguf --dry-run          # the conversion plan, no model
    uv pip install llama-cpp-python gguf          # the undeclared runtime
    uv run pinakes-export-gguf                    # the full conversion + parity

It reads the US-003 config and its run summary, merges that run's adapter into
the base weights, converts to GGUF, quantizes to the quant Insimul deploys, then
scores the quantized model with the **tier-4 adherence harness on the frozen eval
set** — rebuilt in process exactly as the training pipeline does, and refused if
its sha256 does not match the eval set the HF column was scored on. Comparing two
columns measured on different eval sets is not a parity check.

``--dry-run`` and ``--contract-only`` need no model, no llama.cpp and no
undeclared dependency: they are the CI-safe smokes, the same role ``--stub``
plays for ``pinakes-train-slm``.

Runbook: ``docs/slm-pilot-runbook.md`` §US-004.
Contract: ``docs/slm-prompt-contract.md``.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
import time
from pathlib import Path

from pinakes_ml.export_insimul_datasets import DEFAULT_CANDIDATES, DEFAULT_WORLDS
from pinakes_ml.slm_finetune import SlmPilotConfig, build_pilot_data, score_model
from pinakes_ml.slm_gguf import (
    DEFAULT_QUANT,
    MODEL_SUBDIR,
    MODELS_DIRNAME,
    build_parity_report,
    build_plan,
    build_prompt_contract,
    convert_command,
    llama_cpp_dir,
    quantize_command,
    render_parity_section,
    require_llama_cpp_tools,
    upsert_marked_section,
)
from pinakes_ml.train_slm import eval_set_matches_manifest, read_data_floor

_ML_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_CONFIG = _ML_ROOT / "configs" / "slm-pilot-3b.json"
CONTRACT_PATH = _ML_ROOT / "manifests" / "slm-prompt-contract.json"
DEFAULT_DOC = _ML_ROOT.parent / "docs" / "slm-pilot-report.md"

REPORT_FILE = "parity-report.json"
SUMMARY_FILE = "run-summary.json"

#: What a fresh ``docs/slm-pilot-report.md`` is seeded with. US-006 writes the
#: report proper *around* the marked block this CLI owns — the same cooperating
#: -CLIs discipline as ``docs/ml-baselines.md``.
REPORT_STUB = """# SLM pilot — report

**Phase D, the Insimul bridge spec §6.** The verdict section is
[US-006](../tasks/chief/30-slm-pilot.json)'s; the quantization-parity block below
is generated by `pinakes-export-gguf` (slm-pilot US-004) and is upserted between
its markers, so writing the rest of this document around it is safe.

"""


def render_contract() -> str:
    """The committed contract manifest's bytes — house style, sorted + newline."""
    payload = build_prompt_contract()
    return json.dumps(payload, indent=2, sort_keys=True, ensure_ascii=False) + "\n"


def _resolve_adapter(config: SlmPilotConfig, explicit: Path | None) -> Path:
    """The adapter to convert: the flag, else repeat-1, else the flat run dir.

    A repeated US-003 run writes ``repeat-N/adapter``; a single run writes
    ``adapter``. The deliverable is repeat 1 by convention — the repeats share a
    seed, and the report records which one it was rather than merging them.
    """
    if explicit is not None:
        return explicit
    output = Path(config.output_dir)
    for candidate in (output / "repeat-1" / "adapter", output / "adapter"):
        if candidate.exists():
            return candidate
    return output / "adapter"


def _hf_scores(summary_path: Path, eval_sha256: str) -> tuple[dict, str]:
    """The HF column, read from the run summary that produced the adapter.

    Hard-fails when the summary scored a *different* eval set: the protocol's
    "a run that cannot name the eval set it scored is not a comparison point"
    applied to a two-column table, where it matters twice as much.
    """
    if not summary_path.exists():
        raise SystemExit(
            f"no HF run summary at {summary_path}. Run the US-003 baseline first "
            "(`uv run pinakes-train-slm --config configs/slm-pilot-3b.json`), or "
            "pass --summary."
        )
    summary = json.loads(summary_path.read_text(encoding="utf-8"))
    recorded = (summary.get("dataset") or {}).get("evalSetSha256", "")
    if recorded != eval_sha256:
        raise SystemExit(
            "the HF run scored a different eval set than this run rebuilt "
            f"({recorded[:12]}… vs {eval_sha256[:12]}…). A parity check across "
            "two eval sets is not a parity check — pass the matching --summary "
            "or rerun the baseline with this config."
        )
    scores = (summary.get("scores") or {}).get("finetuned")
    if not scores:
        raise SystemExit(f"{summary_path} carries no `finetuned` scores to compare.")
    return dict(scores), _repo_relative(summary_path)


def _repo_relative(path: Path) -> str:
    """Repo-relative when possible — an absolute path is one operator's machine.

    The parity block is committed; recording ``/Users/<someone>/…`` in it is
    provenance nobody else can act on.
    """
    try:
        return str(path.resolve().relative_to(_ML_ROOT.parent))
    except ValueError:
        return str(path)


def _run(command: list[str], label: str) -> None:  # pragma: no cover - local-only
    print(f"$ {' '.join(command)}")
    result = subprocess.run(command, check=False)
    if result.returncode != 0:
        raise SystemExit(f"{label} failed (exit {result.returncode}).")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", type=Path, default=DEFAULT_CONFIG)
    parser.add_argument("--base-dir", type=Path, default=_ML_ROOT)
    parser.add_argument(
        "--adapter", type=Path, default=None,
        help="The LoRA adapter to merge (default: the config run's repeat-1).",
    )
    parser.add_argument(
        "--summary", type=Path, default=None,
        help="The HF-stack run summary the parity check compares against.",
    )
    parser.add_argument(
        "--models-dir", type=Path, default=None,
        help=f"Where the deliverable GGUF lands (default: ml/{MODELS_DIRNAME}/"
             f"{MODEL_SUBDIR}, its own DVC pointer).",
    )
    parser.add_argument("--work-dir", type=Path, default=None)
    parser.add_argument("--quant", default=DEFAULT_QUANT)
    parser.add_argument("--llama-cpp-dir", type=Path, default=None)
    parser.add_argument(
        "--world", type=Path, action="append", dest="worlds",
        help="A CanonicalWorldExport file (repeatable; overrides the config).",
    )
    parser.add_argument(
        "--candidates", type=Path, action="append", dest="candidates",
    )
    parser.add_argument(
        "--skip-convert", action="store_true",
        help="Reuse an existing GGUF (re-score only).",
    )
    parser.add_argument(
        "--dry-run", action="store_true",
        help="Print the conversion plan and the exact commands; touch nothing.",
    )
    parser.add_argument(
        "--contract-only", action="store_true",
        help="Write the prompt-template contract manifest and stop (pure).",
    )
    parser.add_argument(
        "--check", action="store_true",
        help="Freeze gate: verify the committed contract manifest, write nothing.",
    )
    parser.add_argument("--doc", type=Path, default=DEFAULT_DOC)
    parser.add_argument("--no-doc", action="store_true")
    parser.add_argument("--no-mlflow", action="store_true")
    args = parser.parse_args(argv)

    contract = render_contract()
    if args.check:
        current = (
            CONTRACT_PATH.read_text(encoding="utf-8") if CONTRACT_PATH.exists() else ""
        )
        if current != contract:
            print(
                f"DRIFT  {CONTRACT_PATH} does not match a fresh build of the "
                "prompt-template contract. The strings Insimul sends have "
                "changed — regenerate with `pinakes-export-gguf --contract-only` "
                "and treat the diff as a breaking change (bump CONTRACT_VERSION)."
            )
            return 1
        print(f"ok       {CONTRACT_PATH} matches a fresh build")
        return 0

    CONTRACT_PATH.parent.mkdir(parents=True, exist_ok=True)
    CONTRACT_PATH.write_text(contract, encoding="utf-8")
    print(f"contract -> {CONTRACT_PATH}")
    if args.contract_only:
        return 0

    config = SlmPilotConfig.from_json(args.config).resolved(args.base_dir)
    adapter = _resolve_adapter(config, args.adapter)
    work_dir = args.work_dir or (Path(config.output_dir) / "gguf")
    models_dir = args.models_dir or (
        Path(args.base_dir) / MODELS_DIRNAME / MODEL_SUBDIR
    )
    plan = build_plan(
        config.base_model, adapter, work_dir, models_dir,
        run_name=config.run_name, quant=args.quant,
    )

    root = llama_cpp_dir(args.llama_cpp_dir)
    if args.dry_run:
        print(json.dumps(plan.as_dict(), indent=2, sort_keys=True))
        converter = root / "convert_hf_to_gguf.py"
        quantizer = root / "build" / "bin" / "llama-quantize"
        print("$ " + " ".join(convert_command(sys.executable, converter, plan)))
        print("$ " + " ".join(quantize_command(quantizer, plan)))
        print("dry run — nothing written beyond the contract manifest.")
        return 0

    worlds = [Path(p) for p in (args.worlds or config.worlds or DEFAULT_WORLDS)]
    candidates = [
        Path(p)
        for p in (
            args.candidates
            or config.candidates
            or [p for p in DEFAULT_CANDIDATES if p.exists()]
        )
    ]
    for path in [*worlds, *candidates]:
        if not path.exists():
            parser.error(f"input not found: {path}")

    data = build_pilot_data(config, worlds, candidates)
    if not data.eval_set:
        parser.error("the frozen eval set is empty — pass two or more worlds.")
    summary_path = args.summary or (adapter.parent / SUMMARY_FILE)
    hf_scores, hf_source = _hf_scores(summary_path, data.eval_sha256)

    started = time.monotonic()
    if not args.skip_convert:  # pragma: no cover - local-only, heavy
        if not adapter.exists():
            parser.error(f"adapter not found: {adapter}")
        converter, quantizer = require_llama_cpp_tools(root)
        from pinakes_ml.slm_gguf import merge_adapter

        print(f"merge    {adapter} -> {plan.merged_dir}")
        merge_adapter(plan)
        plan.f16_gguf.parent.mkdir(parents=True, exist_ok=True)
        plan.quantized_gguf.parent.mkdir(parents=True, exist_ok=True)
        _run(convert_command(sys.executable, converter, plan), "GGUF conversion")
        _run(quantize_command(quantizer, plan), "quantization")

    if not plan.quantized_gguf.exists():
        raise SystemExit(f"no GGUF at {plan.quantized_gguf} — drop --skip-convert.")

    from pinakes_ml.slm_gguf import (  # pragma: no cover - local-only
        LlamaCppRuleModel,
        llama_cpp_runtime_info,
    )

    model = LlamaCppRuleModel(  # pragma: no cover
        plan.quantized_gguf, seed=config.seed, max_new_tokens=config.max_new_tokens
    )
    gguf_scores = score_model(  # pragma: no cover
        model, data.eval_set, data.world_contexts, config.arms
    )
    report = build_parity_report(  # pragma: no cover
        plan,
        hf_scores,
        gguf_scores,
        dataset={
            "evalSetSha256": data.eval_sha256,
            "ruleSftSha256": data.sft_sha256,
            "matchesFrozenEvalSet": eval_set_matches_manifest(
                Path(config.eval_manifest), data.eval_sha256
            ),
            "evalPromptsScored": len(data.eval_set),
            "heldOutWorlds": list(data.held_out_worlds),
        },
        data_floor=read_data_floor(Path(config.eval_manifest)),
        runtime={
            **llama_cpp_runtime_info(root),
            "quant": plan.quant,
            "nCtx": model.n_ctx,
        },
        wall_clock_seconds=round(time.monotonic() - started, 3),
        hf_source=hf_source,
    )
    report_path = Path(config.output_dir) / REPORT_FILE  # pragma: no cover
    report_path.parent.mkdir(parents=True, exist_ok=True)  # pragma: no cover
    report_path.write_text(  # pragma: no cover
        json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    _print_report(report, report_path)  # pragma: no cover
    if not args.no_doc:  # pragma: no cover
        _write_doc(args.doc, report)
    if not args.no_mlflow:  # pragma: no cover
        _log_to_mlflow(report)
    return 0  # pragma: no cover


def _write_doc(doc: Path, report: dict) -> None:  # pragma: no cover - local-only
    existing = doc.read_text(encoding="utf-8") if doc.exists() else REPORT_STUB
    doc.parent.mkdir(parents=True, exist_ok=True)
    doc.write_text(
        upsert_marked_section(existing, render_parity_section(report)),
        encoding="utf-8",
    )
    print(f"doc      -> {doc}")


def _print_report(report: dict, path: Path) -> None:  # pragma: no cover - local-only
    artifact = report["artifact"]
    size = artifact.get("sizeBytes") or 0
    print(f"gguf     = {artifact['path']} ({size / 1e9:.2f} GB)")
    for arm in sorted(report["deltas"]):
        for stack in ("hf", "gguf"):
            scores = report["scores"][stack][arm]
            print(f"  {stack:<5} {arm:<11} parse={scores['parseRate']:.3f} "
                  f"schema={scores['schemaValidity']:.3f} "
                  f"fullyValid={scores['fullyValid']:.3f} "
                  f"loss={scores['evalLoss']}")
        deltas = report["deltas"][arm]
        print(f"  delta {arm:<11} parse={deltas['parseRate']:+.3f} "
              f"fullyValid={deltas['fullyValid']:+.3f}")
    budget = report["budget"]
    observed = budget["observedPp"]
    print(f"budget   = {budget['metric']} degradation "
          f"{'—' if observed is None else f'{observed:+.1f}pp'} vs the frozen "
          f"≤{budget['allowedPp']}pp -> {budget['verdict']}")
    print(f"report   -> {path}")


def _log_to_mlflow(report: dict) -> None:  # pragma: no cover - local-only
    import mlflow

    from pinakes_ml import start_run

    dataset = report["dataset"]
    with start_run(run_name=f"{report['plan']['quant']}-parity"):
        mlflow.log_param("reportVersion", report["reportVersion"])
        mlflow.log_param("protocolVersion", report["protocolVersion"])
        mlflow.log_param("contractVersion", report["contractVersion"])
        mlflow.log_param("baseModel", report["plan"]["baseModel"])
        mlflow.log_param("quant", report["plan"]["quant"])
        mlflow.log_param("ggufSha256", report["artifact"]["sha256"])
        mlflow.log_param("evalSetSha256", dataset.get("evalSetSha256", ""))
        mlflow.log_param("matchesFrozenEvalSet", dataset.get("matchesFrozenEvalSet"))
        mlflow.log_param("budgetVerdict", report["budget"]["verdict"])
        for key, value in report["runtime"].items():
            mlflow.log_param(key, value)
        for stack, arms in report["scores"].items():
            for arm, scores in arms.items():
                for key, value in scores.items():
                    if isinstance(value, int | float):
                        mlflow.log_metric(f"{stack}_{arm}_{key}", float(value))
        for arm, deltas in report["deltas"].items():
            for key, value in deltas.items():
                mlflow.log_metric(f"delta_{arm}_{key}", float(value))
        if report["budget"]["observedPp"] is not None:
            mlflow.log_metric("budgetObservedPp", float(report["budget"]["observedPp"]))


if __name__ == "__main__":  # pragma: no cover - CLI entry
    raise SystemExit(main())
