"""Rule-adherence eval tier — the VESPACE port (insimul-bridge US-004).

The **fourth** eval tier, alongside link-prediction metrics (tier 1), logical
consistency (tier 2) and KGQA accuracy (tier 3): *can a generated Prolog rule
ever fire in the world it was authored for?*

Given a set of candidate rules (LLM output, or a world's own rule set) plus a
**world context** distilled from a ``CanonicalWorldExport`` (US-003's bridge-2
artifact), it reports five families of numbers:

``parseRate``
    Fraction of candidate rules whose Prolog text parses into clauses.
``structuralValidity``
    Fraction free of the mechanical authoring failures the Insimul rule
    validator catches (sentence atoms, literal actor atoms, family-prefix
    predicates, opaque effect payloads, a body that never touches a head var).
``schemaValidity``
    Fraction whose every body goal names a predicate the world's vocabulary
    actually declares — the *predicate-invention* rate, inverted.
``referentialIntegrity``
    Fraction whose entity-position atoms all resolve to entities in the world.
``reachabilityCharitable`` / ``reachabilityStrict`` / ``fireabilityIndex``
    The VESPACE reachability model: are a rule's conditions producible at all,
    given the character-creation layer and the action set?

Self-contained + PURE (stdlib only), like ``consistency.py``: it does **not**
import Insimul code. The metric definitions are reimplemented from Insimul's
``reachability-analyzer.ts`` / ``insimul-reachability-analyzer.ts`` and its
validator stack; every formula and constant is cited in
:doc:`../../../docs/rule-adherence-tier.md`. Everything is a pure function of
(rules, world context), sorted and wall-clock-free, so :func:`build_report` is
byte-reproducible — the same inputs yield the same committed baseline (a git
no-op), the same ratchet shape as the other eval tiers.
"""

from __future__ import annotations

import json
import math
import re
import unicodedata
from collections.abc import Iterable, Mapping, Sequence
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

__all__ = [
    "ANALYZER_VERSION",
    "DEFAULT_ACTION_LAMBDA",
    "DEFAULT_INTRINSIC_LAMBDA",
    "DOC_MARK_END",
    "DOC_MARK_START",
    "AdherenceReport",
    "Clause",
    "Goal",
    "ParseError",
    "RuleCandidate",
    "RuleRow",
    "WorldContext",
    "build_report",
    "build_world_context",
    "classify_key",
    "evaluate_rule",
    "evaluate_rules",
    "extract_marked_section",
    "goal_predicate_key",
    "load_rules",
    "load_world_context",
    "parse_clause",
    "parse_goal",
    "parse_prolog_source",
    "render_adherence_section",
    "sanitize_atom",
    "split_clauses",
    "split_conjunction",
    "strip_comments",
    "upsert_marked_section",
]

#: Versions the reimplemented metric definitions so a baseline is attributable
#: to the exact scoring rules it was measured against (a formula change bumps
#: this).
ANALYZER_VERSION = "1"

#: Decay per intrinsic condition in the fireability index. Insimul's default —
#: intrinsic conditions only narrow the actor pool, so they are cheap.
DEFAULT_INTRINSIC_LAMBDA = 0.05
#: Decay per action-derived condition. Each one demands a runtime action
#: sequence to satisfy, so it is expensive.
DEFAULT_ACTION_LAMBDA = 0.25

DOC_MARK_START = (
    "<!-- RULE-ADHERENCE:START (generated by pinakes-eval-rule-adherence) -->"
)
DOC_MARK_END = "<!-- RULE-ADHERENCE:END -->"


# --- atoms --------------------------------------------------------------------


_NON_ATOM_RE = re.compile(r"[^a-z0-9]+")


def sanitize_atom(text: str) -> str:
    """Lower a display string to a Prolog atom (accents folded, ``_``-joined).

    ``"Marie Angélique Bernard"`` → ``marie_angelique_bernard``. Used to derive
    the alternative atoms a world entity can legitimately be referenced by.
    """
    folded = unicodedata.normalize("NFKD", text)
    ascii_only = "".join(c for c in folded if not unicodedata.combining(c))
    return _NON_ATOM_RE.sub("_", ascii_only.casefold()).strip("_")


# --- minimal Prolog parser ----------------------------------------------------
#
# A port of Insimul's ``insimul-prolog-parser.ts``: the analyser only has to
# recognise ``head :- body.`` clauses, split the body's top-level conjunction,
# and read each goal's name + arity. Operator priorities, lists and arithmetic
# are read literally.


class ParseError(ValueError):
    """A candidate rule's Prolog text could not be split into clauses."""


_OPEN = "([{"
_CLOSE = ")]}"


def strip_comments(source: str) -> str:
    """Drop ``% line`` and ``/* block */`` comments, preserving quoted atoms."""
    out: list[str] = []
    i = 0
    n = len(source)
    in_str: str | None = None
    while i < n:
        ch = source[i]
        if in_str is not None:
            out.append(ch)
            if ch == in_str and (i == 0 or source[i - 1] != "\\"):
                in_str = None
            i += 1
            continue
        if ch in ("'", '"'):
            in_str = ch
            out.append(ch)
            i += 1
            continue
        if ch == "%":
            while i < n and source[i] != "\n":
                i += 1
            continue
        if ch == "/" and i + 1 < n and source[i + 1] == "*":
            i += 2
            while i < n - 1 and not (source[i] == "*" and source[i + 1] == "/"):
                i += 1
            i += 2
            continue
        out.append(ch)
        i += 1
    if in_str is not None:
        raise ParseError("unterminated quoted atom")
    return "".join(out)


def split_clauses(source: str) -> list[str]:
    """Split comment-stripped Prolog into clauses on top-level ``.`` + space.

    Raises :class:`ParseError` on unbalanced delimiters or a trailing fragment
    with no terminating period — the two failure modes that make a generated
    rule unusable rather than merely wrong.
    """
    clauses: list[str] = []
    buf: list[str] = []
    depth = 0
    in_str: str | None = None
    n = len(source)
    for i, ch in enumerate(source):
        if in_str is not None:
            buf.append(ch)
            if ch == in_str and (i == 0 or source[i - 1] != "\\"):
                in_str = None
            continue
        if ch in ("'", '"'):
            in_str = ch
            buf.append(ch)
            continue
        if ch in _OPEN:
            depth += 1
            buf.append(ch)
            continue
        if ch in _CLOSE:
            depth -= 1
            if depth < 0:
                raise ParseError(f"unbalanced '{ch}'")
            buf.append(ch)
            continue
        if depth == 0 and ch == "." and (i + 1 >= n or source[i + 1].isspace()):
            text = "".join(buf).strip()
            if text:
                clauses.append(text)
            buf = []
            continue
        buf.append(ch)
    if in_str is not None:
        raise ParseError("unterminated quoted atom")
    if depth != 0:
        raise ParseError("unbalanced parentheses")
    tail = "".join(buf).strip()
    if tail:
        raise ParseError("clause is missing its terminating period")
    if not clauses:
        raise ParseError("no clauses found")
    return clauses


def split_conjunction(body: str) -> list[str]:
    """Split a body (or an argument list) on top-level ``,`` / ``;``."""
    parts: list[str] = []
    buf: list[str] = []
    depth = 0
    in_str: str | None = None
    for i, ch in enumerate(body):
        if in_str is not None:
            buf.append(ch)
            if ch == in_str and (i == 0 or body[i - 1] != "\\"):
                in_str = None
            continue
        if ch in ("'", '"'):
            in_str = ch
            buf.append(ch)
            continue
        if ch in _OPEN:
            depth += 1
            buf.append(ch)
            continue
        if ch in _CLOSE:
            depth -= 1
            buf.append(ch)
            continue
        if depth == 0 and ch in (",", ";"):
            text = "".join(buf).strip()
            if text:
                parts.append(text)
            buf = []
            continue
        buf.append(ch)
    tail = "".join(buf).strip()
    if tail:
        parts.append(tail)
    return parts


@dataclass(frozen=True)
class Goal:
    """One body goal: raw text plus its predicate name / arity classification."""

    raw: str
    name: str
    arity: int
    negated: bool
    is_comparison: bool
    args: tuple[str, ...] = ()


@dataclass(frozen=True)
class Clause:
    """One parsed clause — ``head :- body.`` (``body`` empty for a fact)."""

    head: str
    body: str
    goals: tuple[Goal, ...]
    head_predicate: str | None = None
    rule_atom: str | None = None


_COMPARISON_RE = re.compile(
    r"^([^()]+?)\s*(?:>=|=<|<=|=\\=|=:=|>|<|=)\s*([^()]+?)$"
)
_CALL_RE = re.compile(r"^([a-z_]\w*)\s*\((.*)\)\s*$", re.DOTALL)
_ATOM_RE = re.compile(r"^([a-z_]\w*)\s*$")
_NEGATION_RE = re.compile(r"^\\\+\s*(.*)$", re.DOTALL)

#: Head predicates that carry a rule's *name* in their first argument.
_RULE_WRAPPERS = frozenset(
    {
        "rule_applies",
        "rule_active",
        "rule_priority",
        "rule_likelihood",
        "rule_category",
        "rule_type",
        "rule_effect",
    }
)


def _unwrap_parens(text: str) -> str:
    """Drop one redundant outer paren pair — ``(goal(X))`` → ``goal(X)``.

    Only unwraps when the opening paren's partner is the final character, so a
    call like ``goal(X)`` (whose leading token is a name, not a paren) and a
    conjunction like ``(a(X)), b(Y)`` are both left alone.
    """
    stripped = text.strip()
    if not stripped.startswith("(") or not stripped.endswith(")"):
        return stripped
    depth = 0
    for i, ch in enumerate(stripped):
        if ch in _OPEN:
            depth += 1
        elif ch in _CLOSE:
            depth -= 1
            if depth == 0:
                return stripped[1:-1].strip() if i == len(stripped) - 1 else stripped
    return stripped


def parse_goal(token: str) -> Goal:
    """Parse one goal token into name / arity / classification.

    Negation as failure (``\\+ goal(X)`` / ``\\+(goal(X))``) is unwrapped and the
    inner goal is still scored — it names a predicate that must be *definable*
    for the negation to mean anything, even though the rule does not need it true.
    """
    raw = token.strip()
    scan = raw
    negated = False
    neg = _NEGATION_RE.match(scan)
    if neg:
        negated = True
        scan = _unwrap_parens(neg.group(1))
    if _COMPARISON_RE.match(scan):
        return Goal(raw, "", 0, negated, True)
    call = _CALL_RE.match(scan)
    if call:
        name, args_str = call.group(1), call.group(2)
        args = tuple(split_conjunction(args_str))
        return Goal(raw, name, len(args), negated, False, args)
    atom = _ATOM_RE.match(scan)
    if atom:
        return Goal(raw, atom.group(1), 0, negated, False)
    # Anything else (a bare variable, a leftover parenthesised group) — surfaced
    # raw with no classification; the scorer skips it rather than counting it dead.
    return Goal(raw, "", 0, negated, False)


def _inspect_head(head: str) -> tuple[str | None, str | None]:
    call = _CALL_RE.match(head.strip())
    if not call:
        atom = _ATOM_RE.match(head.strip())
        return (atom.group(1) if atom else None), None
    predicate, args_str = call.group(1), call.group(2)
    if predicate in _RULE_WRAPPERS:
        args = split_conjunction(args_str)
        first = args[0].strip() if args else ""
        if _ATOM_RE.match(first):
            return predicate, first
    return predicate, None


def _find_toplevel_neck(text: str) -> int:
    depth = 0
    in_str: str | None = None
    for i in range(len(text) - 1):
        ch = text[i]
        if in_str is not None:
            if ch == in_str and (i == 0 or text[i - 1] != "\\"):
                in_str = None
            continue
        if ch in ("'", '"'):
            in_str = ch
            continue
        if ch in _OPEN:
            depth += 1
        elif ch in _CLOSE:
            depth -= 1
        elif depth == 0 and ch == ":" and text[i + 1] == "-":
            return i
    return -1


def parse_clause(clause_text: str) -> Clause:
    """Parse one clause body (no trailing period) into head / body / goals."""
    text = re.sub(r"\.\s*$", "", clause_text.strip())
    idx = _find_toplevel_neck(text)
    if idx >= 0:
        head, body = text[:idx].strip(), text[idx + 2 :].strip()
    else:
        head, body = text, ""
    goals = tuple(parse_goal(t) for t in split_conjunction(body)) if body else ()
    predicate, rule_atom = _inspect_head(head)
    return Clause(head, body, goals, predicate, rule_atom)


def parse_prolog_source(source: str) -> list[Clause]:
    """Parse a Prolog source string into clauses. Raises :class:`ParseError`."""
    return [parse_clause(c) for c in split_clauses(strip_comments(source))]


# --- world context ------------------------------------------------------------
#
# The Insimul harness builds two artifacts before scoring: an *intrinsic
# registry* (predicates set at character creation — always producible) and a
# *producibility index* (predicates some action effect can make true). Both are
# derived here from a CanonicalWorldExport instead of from the VESPACE corpus:
# the world's ``prologKb`` facts ARE its character-creation layer, and each
# action's Prolog ``content`` carries the effect terms it produces.

#: Effect-term heads the action layer emits, and the key each one produces.
#: Ported from Insimul's ``effectTermToProducedKeys``.
_EFFECT_PATTERNS: tuple[tuple[re.Pattern[str], str], ...] = (
    (re.compile(r"^modify_network\s*\(\s*[^,]+,\s*[^,]+,\s*([a-z_]\w*)"), "arity3"),
    (re.compile(r"^modify_attribute\s*\(\s*[^,]+,\s*([a-z_]\w*)"), "attribute"),
    (re.compile(r"^(?:add|remove)_(?:status|trait)\s*\(\s*[^,]+,\s*([a-z_]\w*)"),
     "arity1"),
    (re.compile(
        r"^(?:add|remove)_(?:directed_status|relationship)"
        r"\s*\(\s*[^,]+,\s*[^,]+,\s*([a-z_]\w*)"
    ), "arity2"),
    (re.compile(r"^record_event\s*\(\s*[^,]+,\s*[^,]+,\s*([a-z_]\w*)"), "arity2"),
    (re.compile(r"^record_social_event\s*\(\s*[^,]+,\s*[^,]+,\s*([a-z_]\w*)"),
     "social_record"),
    (re.compile(r"^set_intent\s*\("), "intent"),
)

#: Engine / bookkeeping predicates. They are always schema-valid (the authoring
#: guide endorses them) but are NOT world-state conditions, so they are excluded
#: from reachability scoring — an effect payload is not something to satisfy.
_ENGINE_PREDICATES = frozenset(
    {
        "rule_applies/3",
        "rule_active/1",
        "rule_priority/2",
        "rule_likelihood/2",
        "rule_category/2",
        "rule_type/2",
        "rule_effect/4",
        "action_accept/3",
        "action_reject/3",
        "action_outcome/3",
        "can_perform/3",
        "modify_network/5",
        "modify_attribute/4",
        "add_status/2",
        "remove_status/2",
        "add_trait/2",
        "remove_trait/2",
        "add_directed_status/3",
        "remove_directed_status/3",
        "add_relationship/3",
        "remove_relationship/3",
        "record_event/3",
        "record_social_event/3",
        "set_intent/4",
    }
)

#: Argument atoms that never denote a world entity (engine placeholders and
#: effect-payload direction tokens). Ported from Insimul's referential linter.
_RESERVED_ATOMS = frozenset(
    {
        "player", "none", "any", "anyone", "anywhere", "nobody", "nothing",
        "self", "true", "false", "up", "down", "unknown", "world", "global",
    }
)

#: World fields whose values are enum-ish *value* atoms, not entity references.
_VALUE_FIELDS = (
    "settlementType", "terrain", "buildingType", "businessType", "occupation",
    "status", "gender", "entryType", "timeSeason", "ruleType", "category",
    "worldType", "actionType", "targetType", "source",
)


def effect_term_keys(term: str) -> list[str]:
    """The predicate keys a structured effect term causes to be true."""
    trimmed = term.strip()
    for pattern, kind in _EFFECT_PATTERNS:
        m = pattern.match(trimmed)
        if not m:
            continue
        if kind == "intent":
            return ["intent/4"]
        token = m.group(1)
        if kind == "attribute":
            return [f"attribute:{token}"]
        if kind == "social_record":
            return [f"social_record:{token}"]
        return [f"{token}/{kind[-1]}"]
    return []


@dataclass(frozen=True)
class WorldContext:
    """Vocabulary + entity snapshot + action set distilled from a world export."""

    world_id: str
    contract_version: str
    #: ``name/arity`` (and ``family:type``) keys set at character creation.
    intrinsic_keys: frozenset[str] = frozenset()
    #: Keys some action effect can produce at runtime.
    producible_keys: frozenset[str] = frozenset()
    #: How many action effects produce each producible key (diagnostic).
    producer_counts: Mapping[str, int] = field(default_factory=dict)
    #: Atoms that resolve to a world entity (ids + sanitized names).
    entity_atoms: frozenset[str] = frozenset()
    #: Enum-ish value atoms the world declares (terrain, occupation, …).
    value_atoms: frozenset[str] = frozenset()
    #: Actions read from the export (count only — diagnostic).
    action_count: int = 0

    @property
    def vocabulary(self) -> frozenset[str]:
        """Every predicate key a rule may legitimately name."""
        return self.intrinsic_keys | self.producible_keys | _ENGINE_PREDICATES

    def as_dict(self) -> dict[str, Any]:
        return {
            "worldId": self.world_id,
            "contractVersion": self.contract_version,
            "actions": self.action_count,
            "intrinsicPredicates": len(self.intrinsic_keys),
            "produciblePredicates": len(self.producible_keys),
            "entityAtoms": len(self.entity_atoms),
            "valueAtoms": len(self.value_atoms),
        }


def _collection(export: Mapping[str, Any], *path: str) -> list[Mapping[str, Any]]:
    node: Any = export.get("ir") if "ir" in export else export
    for key in path:
        if not isinstance(node, Mapping):
            return []
        node = node.get(key)
    if not isinstance(node, list):
        return []
    return [item for item in node if isinstance(item, Mapping)]


def _intrinsic_keys_from_kb(prolog_kb: str) -> set[str]:
    """The character-creation layer: every FACT (bodyless clause) in the KB.

    Insimul seeds its intrinsic registry from the trait / profession / clothing /
    attribute conditions of the source corpus. A CanonicalWorldExport carries the
    same information more directly — the KB's ground facts are exactly the state
    that exists before any action runs.
    """
    keys: set[str] = set()
    if not prolog_kb.strip():
        return keys
    try:
        clauses = parse_prolog_source(prolog_kb)
    except ParseError:
        return keys
    for clause in clauses:
        if clause.body:
            continue
        call = _CALL_RE.match(clause.head.strip())
        if not call:
            atom = _ATOM_RE.match(clause.head.strip())
            if atom:
                keys.add(f"{atom.group(1)}/0")
            continue
        name = call.group(1)
        args = split_conjunction(call.group(2))
        if name == "attribute" and len(args) == 3 and _ATOM_RE.match(args[1].strip()):
            keys.add(f"attribute:{args[1].strip()}")
        keys.add(f"{name}/{len(args)}")
    return keys


def _effect_terms_of_action(content: str) -> list[str]:
    """The effect terms in an action's Prolog — the bodies of its outcome heads."""
    try:
        clauses = parse_prolog_source(content)
    except ParseError:
        return []
    terms: list[str] = []
    for clause in clauses:
        if clause.head_predicate not in (
            "action_accept",
            "action_reject",
            "action_outcome",
        ):
            continue
        terms.extend(goal.raw for goal in clause.goals if goal.name)
    return terms


def _entity_atoms(export: Mapping[str, Any]) -> tuple[set[str], set[str]]:
    atoms: set[str] = set()
    values: set[str] = set()
    groups = (
        ("entities", "characters"),
        ("entities", "buildings"),
        ("entities", "businesses"),
        ("entities", "npcs"),
        ("geography", "settlements"),
        ("geography", "countries"),
        ("geography", "states"),
        ("systems", "quests"),
        ("systems", "items"),
        ("systems", "truths"),
    )
    for path in groups:
        for record in _collection(export, *path):
            _harvest_entity(record, atoms, values)
            for lot in record.get("lots", []) if isinstance(
                record.get("lots"), list
            ) else []:
                if isinstance(lot, Mapping):
                    _harvest_entity(lot, atoms, values)
    for path in (("systems", "actions"), ("systems", "baseActions"),
                 ("systems", "rules"), ("systems", "baseRules")):
        for record in _collection(export, *path):
            for key in _VALUE_FIELDS:
                raw = record.get(key)
                if isinstance(raw, str) and raw.strip():
                    values.add(sanitize_atom(raw))
    atoms.discard("")
    values.discard("")
    return atoms, values


def _harvest_entity(
    record: Mapping[str, Any], atoms: set[str], values: set[str]
) -> None:
    for key in ("id", "name", "title", "address"):
        raw = record.get(key)
        if isinstance(raw, str) and raw.strip():
            atoms.add(sanitize_atom(raw))
    first, last = record.get("firstName"), record.get("lastName")
    if isinstance(first, str) and isinstance(last, str) and first and last:
        atoms.add(sanitize_atom(f"{first} {last}"))
    for key in _VALUE_FIELDS:
        raw = record.get(key)
        if isinstance(raw, str) and raw.strip():
            values.add(sanitize_atom(raw))
    tags = record.get("tags")
    if isinstance(tags, list):
        values.update(sanitize_atom(t) for t in tags if isinstance(t, str))
    skills = record.get("skills")
    if isinstance(skills, Mapping):
        values.update(sanitize_atom(str(k)) for k in skills)


def build_world_context(export: Mapping[str, Any]) -> WorldContext:
    """Distil a ``CanonicalWorldExport`` mapping into a :class:`WorldContext`."""
    kb = export.get("prologKb")
    intrinsic = _intrinsic_keys_from_kb(kb if isinstance(kb, str) else "")

    producible: set[str] = set()
    counts: dict[str, int] = {}
    actions = [
        *_collection(export, "systems", "actions"),
        *_collection(export, "systems", "baseActions"),
    ]
    for action in actions:
        content = action.get("content")
        if not isinstance(content, str):
            continue
        for term in _effect_terms_of_action(content):
            for key in effect_term_keys(term):
                producible.add(key)
                counts[key] = counts.get(key, 0) + 1

    atoms, values = _entity_atoms(export)
    meta = export.get("ir", {})
    meta = meta.get("meta", {}) if isinstance(meta, Mapping) else {}
    world_id = export.get("worldId") or (
        meta.get("worldId") if isinstance(meta, Mapping) else None
    )
    return WorldContext(
        world_id=str(world_id or ""),
        contract_version=str(export.get("contractVersion") or ""),
        intrinsic_keys=frozenset(intrinsic),
        producible_keys=frozenset(producible),
        producer_counts=dict(sorted(counts.items())),
        entity_atoms=frozenset(atoms),
        value_atoms=frozenset(values),
        action_count=len(actions),
    )


def load_world_context(path: Path | str) -> WorldContext:
    """Read a ``CanonicalWorldExport`` JSON file into a :class:`WorldContext`."""
    data = json.loads(Path(path).read_text(encoding="utf-8"))
    if not isinstance(data, Mapping):
        raise ValueError(f"{path}: not a CanonicalWorldExport object")
    return build_world_context(data)


# --- candidate rules ----------------------------------------------------------


@dataclass(frozen=True)
class RuleCandidate:
    """One rule to score: a name plus its Prolog text."""

    name: str
    content: str
    active: bool = True


def _candidate_from(record: Mapping[str, Any], index: int) -> RuleCandidate | None:
    content = record.get("content") or record.get("prolog") or record.get("rule")
    if not isinstance(content, str) or not content.strip():
        return None
    name = record.get("name") or record.get("id") or f"rule_{index + 1:03d}"
    active = record.get("isActive")
    return RuleCandidate(str(name), content, True if active is None else bool(active))


def load_rules(path: Path | str) -> list[RuleCandidate]:
    """Load candidate rules from JSON, JSONL, or a ``CanonicalWorldExport``.

    Accepted shapes — a generated-rule file (``{"rules": [...]}`` or a bare
    list), a JSONL of one rule object per line (raw model output), or a world
    export (its ``systems.rules`` + ``systems.baseRules``, so a converted world
    can be scored against its own vocabulary).
    """
    text = Path(path).read_text(encoding="utf-8")
    try:
        data = json.loads(text)
    except json.JSONDecodeError:
        records: list[Any] = [
            json.loads(line) for line in text.splitlines() if line.strip()
        ]
        data = records
    if isinstance(data, Mapping):
        if "ir" in data or "prologKb" in data:
            records = [
                *_collection(data, "systems", "rules"),
                *_collection(data, "systems", "baseRules"),
            ]
        else:
            raw = data.get("rules")
            records = list(raw) if isinstance(raw, list) else []
    elif isinstance(data, list):
        records = list(data)
    else:
        raise ValueError(f"{path}: unrecognised rule-file shape")
    out: list[RuleCandidate] = []
    for i, record in enumerate(records):
        if not isinstance(record, Mapping):
            continue
        candidate = _candidate_from(record, i)
        if candidate is not None:
            out.append(candidate)
    return out


# --- structural validation ----------------------------------------------------
#
# The mechanical authoring failures Insimul's ``prolog-rule-validator.ts``
# catches, reimplemented. Each check yields a short, stable ``check_id`` so the
# committed baseline stays legible (the prose feedback strings are a retry-prompt
# concern, not an eval concern).

_MAX_RULE_ATOM_LEN = 48
_MAX_RULE_ATOM_WORDS = 6

_LITERAL_ACTOR_ATOMS = frozenset(
    {
        "someone", "other", "self", "person", "actor", "initiator",
        "responder", "first", "second",
    }
)

_FAMILY_PREFIXES = (
    "trait_", "network_", "status_", "mood_", "event_", "directed_status_",
    "relationship_", "bond_", "intent_", "attribute_",
)

_OPAQUE_EFFECT_VALUES = frozenset(
    {
        "unknown", "high", "low", "medium", "some", "none", "positive",
        "negative", "neutral",
    }
)

#: Family-prefixed names that genuinely exist in the engine's bookkeeping layer.
_FAMILY_PREFIX_EXEMPT = frozenset({"event_undirected"})

_STRUCTURAL_CHECKS = (
    "rule_atom_budget",
    "literal_actor_atom",
    "family_prefix_predicate",
    "opaque_effect_payload",
    "body_reaches_head",
)


def _walk_calls(clauses: Sequence[Clause]) -> Iterable[Goal]:
    """Every predicate call in a clause set, including nested effect terms."""
    stack: list[Goal] = []
    for clause in clauses:
        head_goal = parse_goal(clause.head)
        if head_goal.name:
            stack.append(head_goal)
        stack.extend(clause.goals)
    while stack:
        goal = stack.pop()
        if not goal.name:
            continue
        yield goal
        for arg in goal.args:
            nested = parse_goal(arg)
            if nested.name and nested.args:
                stack.append(nested)


def _structural_errors(
    candidate: RuleCandidate, clauses: Sequence[Clause]
) -> list[str]:
    errors: set[str] = set()
    atom = next(
        (c.rule_atom for c in clauses if c.rule_atom),
        None,
    )
    if atom is not None:
        words = len([w for w in atom.split("_") if w])
        if len(atom) > _MAX_RULE_ATOM_LEN or words > _MAX_RULE_ATOM_WORDS:
            errors.add("rule_atom_budget")
    for goal in _walk_calls(clauses):
        for arg in goal.args:
            token = arg.strip()
            if not token or "(" in token:
                continue
            if token[0].isupper() or token[0] == "_":
                continue
            if token[0].isdigit() or token[0] in "-'\"":
                continue
            if token in _LITERAL_ACTOR_ATOMS:
                errors.add("literal_actor_atom")
        name = goal.name
        if name not in _FAMILY_PREFIX_EXEMPT and not name.startswith("rule_"):
            for prefix in _FAMILY_PREFIXES:
                if name.startswith(prefix) and len(name) > len(prefix):
                    errors.add("family_prefix_predicate")
                    break
        if name == "effect" and goal.arity == 2:
            payload = goal.args[-1].strip()
            if payload in _OPAQUE_EFFECT_VALUES:
                errors.add("opaque_effect_payload")
    for clause in clauses:
        if clause.head_predicate != "rule_applies" or not clause.body:
            continue
        call = _CALL_RE.match(clause.head.strip())
        if not call:
            continue
        head_args = split_conjunction(call.group(2))[1:]
        head_vars = [
            a.strip() for a in head_args if a.strip()[:1].isupper() or
            a.strip().startswith("_")
        ]
        if head_vars and not any(v in clause.body for v in head_vars):
            errors.add("body_reaches_head")
    return sorted(errors)


# --- scoring ------------------------------------------------------------------


def goal_predicate_key(goal: Goal) -> str | None:
    """The predicate key a goal resolves to, or ``None`` when it is not scorable.

    Comparisons (``V > 5``) and unparseable goals return ``None`` so they are
    excluded from scoring without inflating the dead count. The parameterised
    ``attribute(_, Type, _)`` family keys on its ``Type`` argument, so
    ``attribute:charisma`` and ``attribute:sophistication`` classify separately.
    """
    if goal.is_comparison or not goal.name:
        return None
    if goal.name == "attribute" and goal.arity == 3:
        token = goal.args[1].strip()
        if _ATOM_RE.match(token):
            return f"attribute:{token}"
        return "attribute/3"
    return f"{goal.name}/{goal.arity}"


def classify_key(key: str, context: WorldContext) -> str:
    """``intrinsic`` / ``producible`` / ``dead`` for one predicate key."""
    if key in context.intrinsic_keys:
        return "intrinsic"
    if key in context.producible_keys:
        return "producible"
    return "dead"


@dataclass(frozen=True)
class RuleRow:
    """The per-rule scorecard — the Python shape of ``RuleReachabilityRow``."""

    rule_name: str
    parsed: bool
    parse_error: str | None
    structural_errors: tuple[str, ...]
    unknown_predicates: tuple[str, ...]
    missing_references: tuple[str, ...]
    total_conditions: int
    intrinsic_conditions: int
    action_conditions: int
    action_conditions_producible: int
    dead_conditions: int
    dead_condition_keys: tuple[str, ...]
    reachability_charitable: float
    reachability_strict: float
    complexity: int
    fireability_index: float

    @property
    def structurally_valid(self) -> bool:
        return self.parsed and not self.structural_errors

    @property
    def schema_valid(self) -> bool:
        return self.parsed and not self.unknown_predicates

    @property
    def referentially_valid(self) -> bool:
        return self.parsed and not self.missing_references

    def as_dict(self) -> dict[str, Any]:
        return {
            "ruleName": self.rule_name,
            "parsed": self.parsed,
            "parseError": self.parse_error,
            "structuralErrors": list(self.structural_errors),
            "unknownPredicates": list(self.unknown_predicates),
            "missingReferences": list(self.missing_references),
            "totalConditions": self.total_conditions,
            "intrinsicConditions": self.intrinsic_conditions,
            "actionConditions": self.action_conditions,
            "actionConditionsProducible": self.action_conditions_producible,
            "deadConditions": self.dead_conditions,
            "deadConditionKeys": list(self.dead_condition_keys),
            "reachabilityCharitable": round(self.reachability_charitable, 6),
            "reachabilityStrict": round(self.reachability_strict, 6),
            "complexity": self.complexity,
            "fireabilityIndex": round(self.fireability_index, 6),
        }


def _missing_references(
    clauses: Sequence[Clause], context: WorldContext, rule_atom: str | None
) -> list[str]:
    """Entity-position atoms that do not resolve to a world entity.

    An argument is an entity reference when it is a lowercase snake_case atom
    that is not a reserved placeholder, not a vocabulary keyword (a predicate
    name or a declared value token such as a terrain or occupation), and not the
    rule's own handle. Ported from Insimul's referential-integrity validator,
    with the keyword sets derived from the world export rather than hard-coded.

    Engine predicates are skipped wholesale — Insimul's linter declares entity
    positions per predicate (``PREDICATE_ARG_KINDS``), and no argument slot of a
    wrapper or effect term (``rule_effect(_, C, occupation, salonniere)``,
    ``modify_network(X, Y, affinity, '+', 5)``) names an entity. Atoms the
    structural checks already own (literal actor labels, opaque effect payloads)
    are skipped too, so one authoring mistake is not counted twice.
    """
    predicate_names = {key.split("/")[0] for key in context.vocabulary if "/" in key}
    family_types = {
        key.split(":", 1)[1] for key in context.vocabulary if ":" in key
    }
    skip = _RESERVED_ATOMS | _LITERAL_ACTOR_ATOMS | _OPAQUE_EFFECT_VALUES
    missing: set[str] = set()
    for goal in _walk_calls(clauses):
        if f"{goal.name}/{goal.arity}" in _ENGINE_PREDICATES:
            continue
        for arg in goal.args:
            token = arg.strip()
            if not token or "(" in token:
                continue
            if not _ATOM_RE.match(token):
                continue
            if token in skip or token == rule_atom:
                continue
            if token in predicate_names or token in family_types:
                continue
            if token in context.value_atoms:
                continue
            if token in context.entity_atoms:
                continue
            missing.add(token)
    return sorted(missing)


def evaluate_rule(
    candidate: RuleCandidate,
    context: WorldContext,
    *,
    intrinsic_lambda: float = DEFAULT_INTRINSIC_LAMBDA,
    action_lambda: float = DEFAULT_ACTION_LAMBDA,
) -> RuleRow:
    """Score one candidate rule against a world context."""
    try:
        clauses = parse_prolog_source(candidate.content)
    except ParseError as exc:
        return RuleRow(
            rule_name=candidate.name,
            parsed=False,
            parse_error=str(exc),
            structural_errors=(),
            unknown_predicates=(),
            missing_references=(),
            total_conditions=0,
            intrinsic_conditions=0,
            action_conditions=0,
            action_conditions_producible=0,
            dead_conditions=0,
            dead_condition_keys=(),
            reachability_charitable=0.0,
            reachability_strict=0.0,
            complexity=0,
            fireability_index=0.0,
        )

    rule_atom = next((c.rule_atom for c in clauses if c.rule_atom), None)
    keys: list[str] = []
    unknown: set[str] = set()
    for clause in clauses:
        for goal in clause.goals:
            key = goal_predicate_key(goal)
            if key is None:
                continue
            if key in _ENGINE_PREDICATES:
                continue
            keys.append(key)
            if key not in context.vocabulary:
                unknown.add(key)

    intrinsic = sum(1 for k in keys if classify_key(k, context) == "intrinsic")
    total = len(keys)
    action = total - intrinsic
    action_producible = sum(
        1 for k in keys if classify_key(k, context) == "producible"
    )
    dead_keys = tuple(
        sorted({k for k in keys if classify_key(k, context) == "dead"})
    )
    dead = sum(1 for k in keys if classify_key(k, context) == "dead")

    charitable = (intrinsic + action_producible) / total if total else 0.0
    strict = action_producible / action if action else 1.0
    fireability = charitable * math.exp(
        -intrinsic * intrinsic_lambda - action * action_lambda
    )

    return RuleRow(
        rule_name=candidate.name,
        parsed=True,
        parse_error=None,
        structural_errors=tuple(_structural_errors(candidate, clauses)),
        unknown_predicates=tuple(sorted(unknown)),
        missing_references=tuple(_missing_references(clauses, context, rule_atom)),
        total_conditions=total,
        intrinsic_conditions=intrinsic,
        action_conditions=action,
        action_conditions_producible=action_producible,
        dead_conditions=dead,
        dead_condition_keys=dead_keys,
        reachability_charitable=charitable,
        reachability_strict=strict,
        complexity=total,
        fireability_index=fireability,
    )


# --- aggregate ----------------------------------------------------------------


def _median(values: Sequence[float]) -> float:
    if not values:
        return 0.0
    ordered = sorted(values)
    mid = len(ordered) // 2
    if len(ordered) % 2 == 0:
        return (ordered[mid - 1] + ordered[mid]) / 2
    return float(ordered[mid])


def _mean(values: Sequence[float]) -> float:
    return sum(values) / len(values) if values else 0.0


def _stats(values: Sequence[float]) -> dict[str, float]:
    if not values:
        return {"mean": 0.0, "median": 0.0, "min": 0.0, "max": 0.0}
    return {
        "mean": round(_mean(values), 6),
        "median": round(_median(values), 6),
        "min": round(min(values), 6),
        "max": round(max(values), 6),
    }


_HISTOGRAM_BUCKETS = (
    "[0.00, 0.25)",
    "[0.25, 0.50)",
    "[0.50, 0.75)",
    "[0.75, 1.00)",
    "[1.00, 1.00]",
)


def _bucket(value: float) -> str:
    if value < 0.25:
        return _HISTOGRAM_BUCKETS[0]
    if value < 0.5:
        return _HISTOGRAM_BUCKETS[1]
    if value < 0.75:
        return _HISTOGRAM_BUCKETS[2]
    if value < 1:
        return _HISTOGRAM_BUCKETS[3]
    return _HISTOGRAM_BUCKETS[4]


@dataclass(frozen=True)
class AdherenceReport:
    """Aggregate + per-rule rule-adherence result over a candidate rule set."""

    context: WorldContext
    rows: tuple[RuleRow, ...]
    intrinsic_lambda: float = DEFAULT_INTRINSIC_LAMBDA
    action_lambda: float = DEFAULT_ACTION_LAMBDA

    @property
    def parsed_rows(self) -> tuple[RuleRow, ...]:
        return tuple(r for r in self.rows if r.parsed)

    def counts(self) -> dict[str, int]:
        parsed = self.parsed_rows
        return {
            "rules": len(self.rows),
            "parsed": len(parsed),
            "structurallyValid": sum(1 for r in parsed if r.structurally_valid),
            "schemaValid": sum(1 for r in parsed if r.schema_valid),
            "referentiallyValid": sum(1 for r in parsed if r.referentially_valid),
            "fullyValid": sum(
                1
                for r in parsed
                if r.structurally_valid and r.schema_valid and r.referentially_valid
            ),
        }

    def rates(self) -> dict[str, float]:
        counts = self.counts()
        total = counts["rules"] or 1
        parsed = counts["parsed"] or 1
        return {
            "parse": round(counts["parsed"] / total, 6),
            "structuralValidity": round(counts["structurallyValid"] / parsed, 6),
            "schemaValidity": round(counts["schemaValid"] / parsed, 6),
            "referentialIntegrity": round(counts["referentiallyValid"] / parsed, 6),
            "fullyValid": round(counts["fullyValid"] / parsed, 6),
        }

    def reachability(self) -> dict[str, Any]:
        rows = self.parsed_rows
        charitable = [r.reachability_charitable for r in rows]
        histogram = dict.fromkeys(_HISTOGRAM_BUCKETS, 0)
        for value in charitable:
            histogram[_bucket(value)] += 1
        conditions = [float(r.total_conditions) for r in rows]
        return {
            "totalConditions": sum(r.total_conditions for r in rows),
            "meanConditionsPerRule": round(_mean(conditions), 6),
            "medianConditionsPerRule": round(_median(conditions), 6),
            "charitable": _stats(charitable),
            "strict": _stats([r.reachability_strict for r in rows]),
            "fireability": _stats([r.fireability_index for r in rows]),
            "histogram": histogram,
            "fullyReachableRules": sum(
                1 for r in rows if r.reachability_charitable >= 1
            ),
            "rulesWithDeadConditions": sum(1 for r in rows if r.dead_conditions > 0),
            "fullyDeadActionSlice": sum(
                1
                for r in rows
                if r.action_conditions > 0 and r.action_conditions_producible == 0
            ),
        }

    def top_dead_conditions(self) -> list[dict[str, Any]]:
        tally: dict[str, int] = {}
        for row in self.parsed_rows:
            for key in set(row.dead_condition_keys):
                tally[key] = tally.get(key, 0) + 1
        ranked = sorted(tally.items(), key=lambda kv: (-kv[1], kv[0]))
        return [{"key": k, "rulesAffected": n} for k, n in ranked]

    def as_dict(self) -> dict[str, Any]:
        """Deterministic report body — the committable baseline."""
        unknown = sorted(
            {k for r in self.parsed_rows for k in r.unknown_predicates}
        )
        missing = sorted(
            {a for r in self.parsed_rows for a in r.missing_references}
        )
        return {
            "analyzerVersion": ANALYZER_VERSION,
            "lambdas": {
                "intrinsic": self.intrinsic_lambda,
                "action": self.action_lambda,
            },
            "world": self.context.as_dict(),
            "counts": self.counts(),
            "rates": self.rates(),
            "reachability": self.reachability(),
            "topDeadConditions": self.top_dead_conditions(),
            "unknownPredicates": unknown,
            "missingReferences": missing,
            "rules": [r.as_dict() for r in self.rows],
        }


def evaluate_rules(
    candidates: Sequence[RuleCandidate],
    context: WorldContext,
    *,
    intrinsic_lambda: float = DEFAULT_INTRINSIC_LAMBDA,
    action_lambda: float = DEFAULT_ACTION_LAMBDA,
) -> AdherenceReport:
    """Score a candidate rule set. Rows keep input order (a stable, given list)."""
    rows = tuple(
        evaluate_rule(
            c,
            context,
            intrinsic_lambda=intrinsic_lambda,
            action_lambda=action_lambda,
        )
        for c in candidates
    )
    return AdherenceReport(context, rows, intrinsic_lambda, action_lambda)


def build_report(
    candidates: Sequence[RuleCandidate],
    context: WorldContext,
    *,
    intrinsic_lambda: float = DEFAULT_INTRINSIC_LAMBDA,
    action_lambda: float = DEFAULT_ACTION_LAMBDA,
) -> dict[str, Any]:
    """The deterministic, committable report dict for a rule set + world."""
    return evaluate_rules(
        candidates,
        context,
        intrinsic_lambda=intrinsic_lambda,
        action_lambda=action_lambda,
    ).as_dict()


# --- docs/ml-baselines.md block ----------------------------------------------


def _pct(value: float) -> str:
    return f"{value * 100:.1f}%"


def render_adherence_section(report: Mapping[str, Any]) -> str:
    """Render the tier-4 ``docs/ml-baselines.md`` block — a **pure** function."""
    counts = report["counts"]
    rates = report["rates"]
    reach = report["reachability"]
    world = report["world"]
    lines: list[str] = [
        DOC_MARK_START,
        "",
        "## Prolog rule adherence (tier 4, insimul-bridge US-004)",
        "",
        "The fourth eval tier scores **generated Prolog rules against the world"
        " they",
        "were authored for** — a port of Insimul's VESPACE reachability analyser"
        " and",
        "validator stack (metric definitions cited in"
        " [`docs/rule-adherence-tier.md`](rule-adherence-tier.md);",
        "no Insimul code is imported). Deterministic + offline, so the numbers"
        " below",
        "are a byte-reproducible floor committed to"
        " `ml/manifests/rule-adherence-baseline.json`.",
        "",
        f"- World `{world['worldId']}` (`{world['contractVersion']}`):"
        f" **{world['intrinsicPredicates']}** intrinsic +"
        f" **{world['produciblePredicates']}** action-producible predicates"
        f" over **{world['actions']}** actions;"
        f" **{world['entityAtoms']}** entity atoms.",
        f"- Candidate rules: **{counts['rules']}**"
        f" ({counts['parsed']} parsed).",
        "",
        "| Check | Rate | Rules |",
        "| --- | --- | --- |",
        f"| Parse | {_pct(rates['parse'])} | {counts['parsed']}"
        f"/{counts['rules']} |",
        f"| Structural validity | {_pct(rates['structuralValidity'])} |"
        f" {counts['structurallyValid']}/{counts['parsed']} |",
        f"| Schema validity | {_pct(rates['schemaValidity'])} |"
        f" {counts['schemaValid']}/{counts['parsed']} |",
        f"| Referential integrity | {_pct(rates['referentialIntegrity'])} |"
        f" {counts['referentiallyValid']}/{counts['parsed']} |",
        "",
        "| Reachability metric | Mean | Median | Min | Max |",
        "| --- | --- | --- | --- | --- |",
    ]
    for label, key in (
        ("Charitable", "charitable"),
        ("Strict", "strict"),
        ("Fireability index", "fireability"),
    ):
        stats = reach[key]
        lines.append(
            f"| {label} | {stats['mean']:.3f} | {stats['median']:.3f} |"
            f" {stats['min']:.3f} | {stats['max']:.3f} |"
        )
    lines += [
        "",
        f"> {reach['rulesWithDeadConditions']} of {counts['parsed']} parsed rules"
        f" carry at least one **dead condition** (a predicate no action produces"
        f" and character creation never sets);"
        f" {reach['fullyDeadActionSlice']} have a fully dead action slice."
        " *Charitable* reachability assumes any intrinsic trait could have been"
        " authored onto some character; *strict* isolates the action-driven"
        " slice. The fireability index discounts charitable reachability by"
        " condition count"
        f" (λ_intrinsic = {report['lambdas']['intrinsic']},"
        f" λ_action = {report['lambdas']['action']}), so a long rule that is"
        " nominally reachable still scores low.",
        "",
    ]
    dead = report["topDeadConditions"]
    if dead:
        lines += [
            "| Dead condition key | Rules affected |",
            "| --- | --- |",
        ]
        lines += [f"| `{d['key']}` | {d['rulesAffected']} |" for d in dead]
        lines.append("")
    lines += [
        "Reproduce: `cd ml && uv run pinakes-eval-rule-adherence`"
        " (fixture-driven — no corpus build needed);"
        " `--check` is the retraining-free ratchet gate.",
        "",
        DOC_MARK_END,
    ]
    return "\n".join(lines) + "\n"


def extract_marked_section(doc_text: str) -> str | None:
    """The tier-4 block (incl. markers) currently in the doc, or ``None``."""
    start = doc_text.find(DOC_MARK_START)
    end = doc_text.find(DOC_MARK_END)
    if start == -1 or end == -1 or end < start:
        return None
    return doc_text[start : end + len(DOC_MARK_END)]


def upsert_marked_section(doc_text: str, section: str) -> str:
    """Insert or replace the tier-4 block. Idempotent; appends when absent."""
    if not section:
        return doc_text
    existing = extract_marked_section(doc_text)
    body = section if section.endswith("\n") else section + "\n"
    if existing is not None:
        replaced = doc_text.replace(existing, body.rstrip("\n"), 1)
        return replaced if replaced.endswith("\n") else replaced + "\n"
    prefix = doc_text if doc_text.endswith("\n") else doc_text + "\n"
    return f"{prefix}\n{body}"
