"""GGUF conversion + llama.cpp parity check (slm-pilot US-004).

The pilot's **deployment leg**: take the US-003 fine-tuned adapter, merge it into
the base weights, convert to GGUF, quantize to the exact quant Insimul already
deploys (``Q4_K_M`` via node-llama-cpp), and then answer the only question that
matters about that pipeline — *does the model still behave the same?*

The parity check is deliberately narrow. The GGUF is scored by the **same tier-4
adherence harness** on the **same frozen eval set**, through the **same
:class:`~pinakes_ml.slm_finetune.RuleModel` seam** and the **same ChatML prompt
string** as the HF-stack run, so the only variable between the two columns is the
runtime + quantization. Anything else and a difference could be the harness.

The acceptability judgment is **not made here**: ``docs/slm-pilot-protocol.md`` §5
froze it before any training run — *"Q4_K_M under llama.cpp degrades ``fullyValid``
by ≤ 2pp vs the HF stack on the same eval set"* (:data:`QUANT_BUDGET_PP`). This
module computes the observed degradation and compares it to that frozen number;
US-004 could not pick a threshold after seeing the drop, which was the point.

The third deliverable lives here too and is the one Insimul actually consumes:
:func:`build_prompt_contract` — the **exact strings** ``LocalAIService`` must send.
It is a pure function of the pipeline's own prompt renderers (no fixtures, no
corpus), so the committed ``ml/manifests/slm-prompt-contract.json`` is snapshot-
gated in CI and cannot drift from what the model was trained on. Prose half:
``docs/slm-prompt-contract.md``.

Shape, per ``ml/CLAUDE.md``: pure core (path plans, argv builders, the parity
arithmetic, the contract, the doc block) with **no heavy imports at module load**,
plus lazily-imported conversion/inference that never runs in CI. ``llama-cpp-python``
and the llama.cpp checkout are undeclared, local-only dependencies — same stance as
``trl``/``peft`` (see ``pyproject.toml``).

CLI: :mod:`pinakes_ml.export_gguf`. Runbook: ``docs/slm-pilot-runbook.md`` §US-004.
"""

from __future__ import annotations

import hashlib
import os
import shutil
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from pinakes_ml.slm_finetune import (
    ARM_GROUNDED,
    ARMS,
    IM_END,
    IM_START,
    PIPELINE_VERSION,
    RULE_SYSTEM_PROMPT,
    format_inference_prompt,
    format_training_text,
)
from pinakes_ml.slm_pilot import (
    FROZEN_METRICS,
    GROUNDING_LINE_PREFIXES,
    PROTOCOL_VERSION,
    UNGROUNDED_CONSTRAINT,
)

#: Bumped when the parity report's schema changes.
REPORT_VERSION = "1"

#: Bumped when the prompt-template contract changes. A bump is a **breaking
#: change for Insimul**: the strings below are what its runtime sends.
CONTRACT_VERSION = "1"

#: Insimul's deployed quantization (``scripts/setup-local-ai.sh`` pulls
#: Qwen2.5-3B-Instruct Q4_K_M). The pilot converts to the same one so the parity
#: check measures the runtime the model will actually live in.
DEFAULT_QUANT = "Q4_K_M"

#: The lossless intermediate `convert_hf_to_gguf.py` emits before quantization.
INTERMEDIATE_OUTTYPE = "f16"

#: The frozen quantization budget — ``docs/slm-pilot-protocol.md`` §5, bar 3,
#: written before the first training run so US-004 could not choose it afterwards.
QUANT_BUDGET_METRIC = "fullyValid"
QUANT_BUDGET_PP = 2.0

#: The arm the budget is stated on: the production path (Insimul sends the
#: grounding block). The ungrounded arm is reported alongside, never in the gate.
QUANT_BUDGET_ARM = ARM_GROUNDED

VERDICT_WITHIN = "within-budget"
VERDICT_OVER = "over-budget"
VERDICT_UNMEASURED = "not-measured"

#: Where the deliverable GGUF lands: its own DVC pointer (``ml/models.dvc``),
#: NOT the ``ml/data`` tree — a 2 GB binary has no business re-pinning the
#: dataset tree every time a checkpoint changes.
MODELS_DIRNAME = "models"
MODEL_SUBDIR = "slm-pilot"

DOC_MARK_START = "<!-- SLM-QUANT:START (generated by pinakes-export-gguf) -->"
DOC_MARK_END = "<!-- SLM-QUANT:END -->"

#: Greedy, deterministic, and capped — the same decoding contract the HF-stack
#: model was scored under (:class:`~pinakes_ml.slm_finetune.HFRuleModel` uses
#: ``do_sample=False``). Insimul must send these or the parity number is void.
GENERATION_CONTRACT: dict[str, Any] = {
    "temperature": 0.0,
    "topK": 1,
    "topP": 1.0,
    "maxNewTokens": 96,
    "stop": [IM_END, "<|endoftext|>"],
}


# --- locating the llama.cpp toolchain -------------------------------------------

#: Where a llama.cpp checkout is looked for when neither the flag nor the env var
#: says otherwise. It is a *checkout*, not a package: the converter is a script
#: that ships in the repo and the quantizer is a built binary.
DEFAULT_LLAMA_CPP_DIR = Path.home() / "llama.cpp"

CONVERTER_NAME = "convert_hf_to_gguf.py"
QUANTIZER_NAME = "llama-quantize"

TOOLCHAIN_HELP = (
    "llama.cpp is an undeclared, local-only dependency of this story (like "
    "trl/peft). Get it with:\n"
    "  git clone --depth 1 https://github.com/ggml-org/llama.cpp ~/llama.cpp\n"
    "  cd ~/llama.cpp && cmake -B build -DGGML_METAL=ON -DLLAMA_CURL=OFF \\\n"
    "      -DCMAKE_BUILD_TYPE=Release && cmake --build build "
    "--target llama-quantize -j 8\n"
    # sentencepiece is not optional even for a BPE model: Qwen2Model.set_vocab
    # TRIES the sentencepiece path first and only falls back to gpt2 on
    # FileNotFoundError — a missing module raises ImportError straight through it.
    "  cd <repo>/ml && uv pip install llama-cpp-python gguf sentencepiece\n"
    "Point elsewhere with --llama-cpp-dir or $LLAMA_CPP_DIR."
)


def llama_cpp_dir(explicit: Path | str | None = None) -> Path:
    """The llama.cpp checkout to use: flag > ``$LLAMA_CPP_DIR`` > default."""
    if explicit is not None:
        return Path(explicit)
    from_env = os.environ.get("LLAMA_CPP_DIR")
    return Path(from_env) if from_env else DEFAULT_LLAMA_CPP_DIR


def find_converter(root: Path | str) -> Path | None:
    """``convert_hf_to_gguf.py`` in a llama.cpp checkout, or ``None``."""
    candidate = Path(root) / CONVERTER_NAME
    return candidate if candidate.is_file() else None


def find_quantizer(root: Path | str) -> Path | None:
    """The ``llama-quantize`` binary — built, in-tree, or on ``$PATH``.

    Checked in that order: a cmake build inside the checkout is the common case,
    a packaged install on ``PATH`` is the other one.
    """
    root = Path(root)
    for candidate in (root / "build" / "bin" / QUANTIZER_NAME, root / QUANTIZER_NAME):
        if candidate.is_file() and os.access(candidate, os.X_OK):
            return candidate
    found = shutil.which(QUANTIZER_NAME)
    return Path(found) if found else None


def require_llama_cpp_tools(root: Path | str) -> tuple[Path, Path]:
    """Both tools, or an actionable error naming which one is missing.

    Same discipline as :func:`~pinakes_ml.finetune.require_finetune_deps`: the
    dependency is genuinely optional, so its absence is a clear message rather
    than an ``ImportError`` from three frames down.
    """
    root = Path(root)
    converter, quantizer = find_converter(root), find_quantizer(root)
    missing = [
        name
        for name, tool in ((CONVERTER_NAME, converter), (QUANTIZER_NAME, quantizer))
        if tool is None
    ]
    if missing:
        raise SystemExit(
            f"llama.cpp toolchain incomplete at {root}: missing {', '.join(missing)}."
            f"\n\n{TOOLCHAIN_HELP}"
        )
    assert converter is not None and quantizer is not None  # narrowing
    return converter, quantizer


def require_llama_cpp_python() -> None:
    """Gate on ``llama-cpp-python`` — the runtime the parity column is scored in."""
    try:
        import llama_cpp  # noqa: F401
    except ImportError as exc:
        raise SystemExit(
            "llama-cpp-python is not installed. It is intentionally not a "
            "workspace dependency (it builds a native runtime per platform). "
            "Install it with `uv pip install llama-cpp-python`."
        ) from exc


# --- the conversion plan (pure) -------------------------------------------------


def model_stem(run_name: str, quant: str = DEFAULT_QUANT) -> str:
    """The deliverable's filename stem, e.g. ``slm-pilot-3b-Q4_K_M``."""
    return f"{run_name}-{quant}"


@dataclass(frozen=True)
class ConversionPlan:
    """Every path one conversion touches — computed before anything is written.

    Pure and inspectable, which is what makes ``--dry-run`` a real smoke: the
    plan (and the two argv lists derived from it) can be asserted in CI with no
    adapter, no llama.cpp and no model on disk.
    """

    base_model: str
    adapter_dir: Path
    #: Merged fp16 HF weights — a bulky intermediate, so it stays in the
    #: git-ignored artifacts tree and is never DVC-pinned.
    merged_dir: Path
    #: The lossless GGUF, likewise an intermediate.
    f16_gguf: Path
    #: The deliverable, in the DVC-tracked models tree.
    quantized_gguf: Path
    quant: str = DEFAULT_QUANT

    def as_dict(self) -> dict[str, str]:
        return {
            "baseModel": self.base_model,
            "adapterDir": str(self.adapter_dir),
            "mergedDir": str(self.merged_dir),
            "f16Gguf": str(self.f16_gguf),
            "quantizedGguf": str(self.quantized_gguf),
            "quant": self.quant,
        }


def build_plan(
    base_model: str,
    adapter_dir: Path | str,
    work_dir: Path | str,
    models_dir: Path | str,
    *,
    run_name: str,
    quant: str = DEFAULT_QUANT,
) -> ConversionPlan:
    """Lay out the conversion: adapter → merged → f16 GGUF → quantized GGUF."""
    work, models = Path(work_dir), Path(models_dir)
    return ConversionPlan(
        base_model=base_model,
        adapter_dir=Path(adapter_dir),
        merged_dir=work / "merged",
        f16_gguf=work / f"{run_name}-{INTERMEDIATE_OUTTYPE}.gguf",
        quantized_gguf=models / f"{model_stem(run_name, quant)}.gguf",
        quant=quant,
    )


def convert_command(
    python_exe: str, converter: Path | str, plan: ConversionPlan
) -> list[str]:
    """The ``convert_hf_to_gguf.py`` argv (pure — asserted in CI, run locally)."""
    return [
        str(python_exe),
        str(converter),
        str(plan.merged_dir),
        "--outfile",
        str(plan.f16_gguf),
        "--outtype",
        INTERMEDIATE_OUTTYPE,
    ]


def quantize_command(quantizer: Path | str, plan: ConversionPlan) -> list[str]:
    """The ``llama-quantize`` argv (pure)."""
    return [str(quantizer), str(plan.f16_gguf), str(plan.quantized_gguf), plan.quant]


def file_identity(path: Path | str) -> dict[str, Any]:
    """size + sha256 of a produced artifact, or an empty identity when absent.

    The GGUF is git-ignored and DVC-tracked, so its *identity* is what travels in
    the committed report — "which bytes were scored" is the same discipline the
    protocol applies to the eval set.
    """
    path = Path(path)
    if not path.is_file():
        return {"path": str(path), "exists": False, "sizeBytes": None, "sha256": ""}
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1 << 20), b""):
            digest.update(chunk)
    return {
        "path": str(path),
        "exists": True,
        "sizeBytes": path.stat().st_size,
        "sha256": digest.hexdigest(),
    }


# --- the parity arithmetic (pure) -----------------------------------------------


def parity_deltas(
    hf_scores: Mapping[str, Mapping[str, Any]],
    gguf_scores: Mapping[str, Mapping[str, Any]],
    *,
    metrics: Sequence[str] = FROZEN_METRICS,
) -> dict[str, dict[str, float]]:
    """``gguf − hf`` per arm and frozen metric — negative means the quant lost.

    Only arms and metrics both columns actually carry are emitted: an invented
    zero would read as "no degradation" when the truth is "not measured".

    ``metrics`` is a parameter (defaulting to this pilot's frozen list) so
    another pilot's deployment leg reuses the arithmetic with its own frozen
    metrics instead of forking it — same discipline as
    :func:`~pinakes_ml.slm_baseline.aggregate_repeats`.
    """
    deltas: dict[str, dict[str, float]] = {}
    for arm in sorted(set(hf_scores) & set(gguf_scores)):
        row: dict[str, float] = {}
        for metric in metrics:
            before, after = hf_scores[arm].get(metric), gguf_scores[arm].get(metric)
            if isinstance(before, int | float) and isinstance(after, int | float):
                row[metric] = round(float(after) - float(before), 6)
        deltas[arm] = row
    return deltas


def quant_budget(
    hf_scores: Mapping[str, Mapping[str, Any]],
    gguf_scores: Mapping[str, Mapping[str, Any]],
    *,
    metric: str = QUANT_BUDGET_METRIC,
    arm: str = QUANT_BUDGET_ARM,
    allowed_pp: float = QUANT_BUDGET_PP,
) -> dict[str, Any]:
    """The frozen §5 bar-3 check: is the observed degradation within budget?

    ``observedPp`` is *degradation* — positive when the quantized model scored
    **worse** — so it reads the same way the protocol states the bar. A quant that
    scores higher is reported as a negative degradation, not clamped to zero: at
    two eval prompts that is noise, and hiding it would hide the noise.

    Returns ``not-measured`` (never a pass) when either column lacks the metric.
    """
    before = (hf_scores.get(arm) or {}).get(metric)
    after = (gguf_scores.get(arm) or {}).get(metric)
    if not isinstance(before, int | float) or not isinstance(after, int | float):
        return {
            "metric": metric,
            "arm": arm,
            "allowedPp": allowed_pp,
            "hf": before if isinstance(before, int | float) else None,
            "gguf": after if isinstance(after, int | float) else None,
            "observedPp": None,
            "withinBudget": None,
            "verdict": VERDICT_UNMEASURED,
        }
    observed = round((float(before) - float(after)) * 100.0, 6)
    within = observed <= allowed_pp
    return {
        "metric": metric,
        "arm": arm,
        "allowedPp": allowed_pp,
        "hf": round(float(before), 6),
        "gguf": round(float(after), 6),
        "observedPp": observed,
        "withinBudget": within,
        "verdict": VERDICT_WITHIN if within else VERDICT_OVER,
    }


def build_parity_report(
    plan: ConversionPlan,
    hf_scores: Mapping[str, Mapping[str, Any]],
    gguf_scores: Mapping[str, Mapping[str, Any]],
    *,
    dataset: Mapping[str, Any] | None = None,
    data_floor: Mapping[str, Any] | None = None,
    runtime: Mapping[str, Any] | None = None,
    wall_clock_seconds: float | None = None,
    hf_source: str = "",
) -> dict[str, Any]:
    """The committable US-004 artifact: both columns, the delta, the frozen bar.

    ``data_floor`` is copied **verbatim** from the frozen protocol manifest, the
    same rule US-003's report follows: the sufficiency verdict is a field, not a
    judgment this story is entitled to make.
    """
    return {
        "reportVersion": REPORT_VERSION,
        "protocolVersion": PROTOCOL_VERSION,
        "pipelineVersion": PIPELINE_VERSION,
        "contractVersion": CONTRACT_VERSION,
        "plan": plan.as_dict(),
        "artifact": file_identity(plan.quantized_gguf),
        "dataset": dict(dataset or {}),
        "dataFloor": dict(data_floor) if data_floor else None,
        "hfSource": hf_source,
        "scores": {
            "hf": {arm: dict(scores) for arm, scores in sorted(hf_scores.items())},
            "gguf": {arm: dict(scores) for arm, scores in sorted(gguf_scores.items())},
        },
        "deltas": parity_deltas(hf_scores, gguf_scores),
        "budget": quant_budget(hf_scores, gguf_scores),
        "runtime": dict(runtime or {}),
        "cost": {
            "wallClockSeconds": wall_clock_seconds,
            "usd": 0.0,
            "note": "local Apple-Silicon conversion + llama.cpp scoring",
        },
    }


# --- the prompt-template contract (pure) ----------------------------------------

#: The placeholder the contract's templates carry where the caller substitutes.
USER_PROMPT_SLOT = "{{USER_PROMPT}}"
RULE_SLOT = "{{RULE}}"


def build_prompt_contract() -> dict[str, Any]:
    """The exact strings Insimul's ``LocalAIService`` must send.

    Derived from the pipeline's own renderers rather than transcribed, so the
    committed manifest cannot drift from what the model was trained on — the
    snapshot test is the tripwire. Everything here is a pure function of module
    constants: no fixtures, no corpus, so it is a real CI gate.
    """
    return {
        "contractVersion": CONTRACT_VERSION,
        "protocolVersion": PROTOCOL_VERSION,
        "pipelineVersion": PIPELINE_VERSION,
        "runtime": {
            "target": "Insimul LocalAIService (node-llama-cpp)",
            "quantization": DEFAULT_QUANT,
            "note": (
                "The model is a Qwen2.5-Instruct derivative, so node-llama-cpp's "
                "ChatML wrapper is correct — but send the strings below verbatim "
                "rather than relying on wrapper defaults: the system prompt and "
                "the stop set are part of what was measured."
            ),
        },
        "chatTemplate": {
            "format": "chatml",
            "imStart": IM_START,
            "imEnd": IM_END,
            "turn": f"{IM_START}{{role}}\n{{content}}{IM_END}\n",
            "generationPrefix": f"{IM_START}assistant\n",
        },
        "systemPrompt": RULE_SYSTEM_PROMPT,
        "inferencePromptTemplate": format_inference_prompt(USER_PROMPT_SLOT),
        "trainingTextTemplate": format_training_text(USER_PROMPT_SLOT, RULE_SLOT),
        "userPrompt": {
            "arms": list(ARMS),
            "production": ARM_GROUNDED,
            "groundedLinePrefixes": list(GROUNDING_LINE_PREFIXES),
            "ungroundedConstraint": UNGROUNDED_CONSTRAINT,
            "note": (
                "The system turn carries NO world vocabulary by design — the "
                "grounding block lives in the user turn, which is exactly what "
                "the US-003 ablation strips. Insimul builds the user turn with "
                "insimul_datasets.build_rule_prompt; send the grounded arm."
            ),
        },
        "generation": dict(GENERATION_CONTRACT),
        "response": {
            "extract": (
                "Strip code fences, drop everything before the first "
                "clause-shaped line (^[a-z]\\w*\\s*\\(), and take the clause up "
                "to its terminating period — pinakes_ml.slm_finetune.extract_rule."
            ),
            "parseFailure": (
                "A generation with no clause-shaped line is a PARSE FAILURE and "
                "must be rejected, not coerced: the tier-4 parser would accept "
                '"I cannot help." as a one-atom clause.'
            ),
            "gate": (
                "Score every generation through the tier-4 validator "
                "(pinakes-eval-rule-adherence) before writing it into a world."
            ),
        },
    }


# --- the doc block (pure) -------------------------------------------------------


def _fmt(value: Any, digits: int = 3) -> str:
    return "—" if not isinstance(value, int | float) else f"{value:.{digits}f}"


def _signed(value: Any, digits: int = 3) -> str:
    return "—" if not isinstance(value, int | float) else f"{value:+.{digits}f}"


#: Runtime facts worth committing. ``llamaCppDir`` is deliberately absent: it is
#: a machine-local path, and a committed document should not record where one
#: operator happened to clone a dependency. It stays in the JSON report.
DOC_RUNTIME_KEYS: tuple[str, ...] = (
    "llamaCppCommit",
    "llamaCppPython",
    "quant",
    "nCtx",
)

#: The metrics the markdown table shows; the full frozen list rides in the JSON.
HEADLINE_METRICS: tuple[str, ...] = (
    "parseRate",
    "schemaValidity",
    "referentialIntegrity",
    "fullyValid",
    "reachabilityCharitable",
    "evalLoss",
)


def render_parity_section(report: Mapping[str, Any]) -> str:
    """The ``SLM-QUANT`` marked block for ``docs/slm-pilot-report.md`` (pure).

    Marker-wrapped and upserted idempotently — the same cooperating-CLIs
    discipline as the ``SLM-PILOT`` block in ``docs/ml-baselines.md``, so US-006
    can write the rest of the pilot report around it without clobbering it.
    """
    artifact = report.get("artifact") or {}
    dataset = report.get("dataset") or {}
    budget = report.get("budget") or {}
    plan = report.get("plan") or {}
    floor = (report.get("dataFloor") or {}).get("verdict")
    size = artifact.get("sizeBytes")
    lines = [
        DOC_MARK_START,
        "",
        "## Quantization parity — HF stack vs llama.cpp "
        f"`{plan.get('quant', DEFAULT_QUANT)}` (slm-pilot US-004)",
        "",
        f"`{plan.get('baseModel', '')}` + the US-003 adapter, merged and converted "
        f"to GGUF, then scored by the **same tier-4 adherence harness on the same "
        f"frozen eval set** as the HF column — same prompt strings, same "
        f"`RuleModel` seam, greedy decoding on both sides. The only variable is "
        "the runtime and the quantization.",
        "",
        f"- artifact `{Path(str(artifact.get('path', ''))).name}`"
        + (f", {size / 1e9:.2f} GB" if isinstance(size, int) else "")
        + f", `sha256 {str(artifact.get('sha256', ''))[:12]}…`",
        f"- eval set `sha256 {str(dataset.get('evalSetSha256', ''))[:12]}…`, "
        f"frozen: `{dataset.get('matchesFrozenEvalSet')}` — "
        f"{dataset.get('evalPromptsScored', 0)} prompts",
        f"- HF column read from `{report.get('hfSource', '') or '—'}`",
        "",
    ]
    if floor:
        lines += [
            f"> ⚠️ **`dataFloor.verdict == \"{floor}\"`.** The parity *machinery* is "
            "what this story delivers; at this corpus scale the numbers below "
            "cannot settle whether the quantization is acceptable for production. "
            "The budget check is reported because the threshold was frozen before "
            "training (protocol §5, bar 3) — not because the corpus can support a "
            "verdict.",
            "",
        ]
    header = " | ".join(HEADLINE_METRICS)
    lines += [
        f"| Arm / stack | {header} |",
        "| --- |" + " ---: |" * len(HEADLINE_METRICS),
    ]
    scores = report.get("scores") or {}
    deltas = report.get("deltas") or {}
    for arm in sorted(set(scores.get("hf", {})) | set(scores.get("gguf", {}))):
        for stack, label in (("hf", "HF (fp32)"), ("gguf", "llama.cpp")):
            row = (scores.get(stack) or {}).get(arm)
            if row is None:
                continue
            cells = " | ".join(
                _fmt(row.get(m), 2 if m == "evalLoss" else 3) for m in HEADLINE_METRICS
            )
            lines.append(f"| `{arm}` · {label} | {cells} |")
        if arm in deltas:
            cells = " | ".join(
                _signed(deltas[arm].get(m), 2 if m == "evalLoss" else 3)
                for m in HEADLINE_METRICS
            )
            lines.append(f"| `{arm}` · **Δ (gguf − hf)** | {cells} |")
    lines.append("")
    verdict = budget.get("verdict")
    if verdict:
        observed = budget.get("observedPp")
        lines += [
            "### The frozen quantization budget",
            "",
            f"Protocol §5 bar 3, written before the first training run: "
            f"**`{budget.get('metric')}` on the `{budget.get('arm')}` arm may "
            f"degrade by ≤ {budget.get('allowedPp')} pp**.",
            "",
            "| HF | llama.cpp | degradation | budget | verdict |",
            "| ---: | ---: | ---: | ---: | --- |",
            f"| {_fmt(budget.get('hf'))} | {_fmt(budget.get('gguf'))} | "
            f"{'—' if observed is None else f'{observed:+.1f} pp'} | "
            f"≤ {budget.get('allowedPp')} pp | **{verdict}** |",
            "",
        ]
    runtime = report.get("runtime") or {}
    shown = [(k, runtime[k]) for k in DOC_RUNTIME_KEYS if k in runtime]
    if shown:
        lines += [
            "Runtime: " + ", ".join(f"`{k}={v}`" for k, v in shown) + ".",
            "",
        ]
    lines += [
        "Reproduce: `cd ml && uv pip install llama-cpp-python gguf sentencepiece "
        "&& uv run pinakes-export-gguf` (local-only; `--dry-run` is the CI-safe "
        "plan smoke). Prompt-template contract: "
        "`docs/slm-prompt-contract.md`. Runbook: `docs/slm-pilot-runbook.md`.",
        "",
        DOC_MARK_END,
    ]
    return "\n".join(lines) + "\n"


def extract_marked_section(doc_text: str) -> str | None:
    """The parity block (incl. markers) currently in the doc, or ``None``."""
    start = doc_text.find(DOC_MARK_START)
    end = doc_text.find(DOC_MARK_END)
    if start == -1 or end == -1 or end < start:
        return None
    return doc_text[start : end + len(DOC_MARK_END)]


def upsert_marked_section(doc_text: str, section: str) -> str:
    """Insert or replace the parity block. Idempotent; appends when absent."""
    if not section:
        return doc_text
    existing = extract_marked_section(doc_text)
    body = section if section.endswith("\n") else section + "\n"
    if existing is not None:
        replaced = doc_text.replace(existing, body.rstrip("\n"), 1)
        return replaced if replaced.endswith("\n") else replaced + "\n"
    prefix = doc_text if doc_text.endswith("\n") else doc_text + "\n"
    return f"{prefix}\n{body}"


# --- the heavy legs (lazy imports; local-only, never in CI) ---------------------


def merge_adapter(
    plan: ConversionPlan,
) -> Path:  # pragma: no cover - needs the model + peft, local-only
    """Fold the LoRA adapter into the base weights and save fp16 HF weights.

    ``convert_hf_to_gguf.py`` reads a plain HF checkpoint, not an adapter, so the
    merge is a required step rather than an optimization. fp16 because it is the
    converter's lossless input type — the quantization happens once, downstream,
    where it can be measured.
    """
    import torch
    from peft import PeftModel
    from transformers import AutoModelForCausalLM, AutoTokenizer

    from pinakes_ml.slm_finetune import free_device_memory

    model = AutoModelForCausalLM.from_pretrained(
        plan.base_model, torch_dtype=torch.float16
    )
    merged = PeftModel.from_pretrained(model, str(plan.adapter_dir)).merge_and_unload()
    plan.merged_dir.mkdir(parents=True, exist_ok=True)
    merged.save_pretrained(str(plan.merged_dir), safe_serialization=True)
    # The trainer saved the tokenizer next to the adapter; prefer it, so the GGUF
    # carries the exact vocabulary the run was scored with.
    tokenizer_src = (
        plan.adapter_dir
        if (plan.adapter_dir / "tokenizer_config.json").exists()
        else plan.base_model
    )
    AutoTokenizer.from_pretrained(str(tokenizer_src)).save_pretrained(
        str(plan.merged_dir)
    )
    del merged, model
    free_device_memory()
    return plan.merged_dir


class LlamaCppRuleModel:  # pragma: no cover - needs a GGUF + native runtime
    """A GGUF under llama.cpp behind the :class:`RuleModel` seam.

    Deliberately the *same* seam the HF model is scored through, fed the *same*
    :func:`~pinakes_ml.slm_finetune.format_inference_prompt` string, decoded
    greedily — so the parity delta is the runtime and the quantization, not the
    harness. ``logits_all`` is on because :meth:`eval_loss` needs per-position
    logits; it costs memory but keeps the frozen metric list complete.
    """

    def __init__(
        self,
        gguf_path: Path | str,
        *,
        n_ctx: int = 4096,
        max_new_tokens: int = GENERATION_CONTRACT["maxNewTokens"],
        seed: int = 0,
        n_gpu_layers: int = -1,
        verbose: bool = False,
    ) -> None:
        require_llama_cpp_python()
        from llama_cpp import Llama

        self.gguf_path = str(gguf_path)
        self.max_new_tokens = max_new_tokens
        self.n_ctx = n_ctx
        # Not the tokenizer's chat template: this model is prompted with the pure
        # renderer, which IS the contract. Recorded as unverifiable here rather
        # than claimed — the HF run already asserted the template equality.
        self.chat_template_verified: bool | None = None
        self.llm = Llama(
            model_path=self.gguf_path,
            n_ctx=n_ctx,
            n_gpu_layers=n_gpu_layers,
            logits_all=True,
            seed=seed,
            verbose=verbose,
        )

    def generate(self, prompt: str) -> str:
        out = self.llm.create_completion(
            format_inference_prompt(prompt),
            max_tokens=self.max_new_tokens,
            temperature=float(GENERATION_CONTRACT["temperature"]),
            top_k=int(GENERATION_CONTRACT["topK"]),
            top_p=float(GENERATION_CONTRACT["topP"]),
            stop=list(GENERATION_CONTRACT["stop"]),
        )
        return str(out["choices"][0]["text"])

    def eval_loss(self, pairs: Sequence[tuple[str, str]]) -> float | None:
        """Teacher-forced mean loss on the reference completions.

        The llama.cpp mirror of :meth:`HFRuleModel.eval_loss`: score the full
        training text, then average cross-entropy over the **completion** tokens
        only (the prompt positions are skipped, which is what HF's ``-100``
        masking does). Returns ``None`` if the runtime exposes no logits — an
        absent metric, never a fabricated one.
        """
        import numpy as np

        losses: list[float] = []
        for prompt, reference in pairs:
            prompt_ids = self.llm.tokenize(
                format_inference_prompt(prompt).encode("utf-8"), special=True
            )
            full_ids = self.llm.tokenize(
                format_training_text(prompt, reference).encode("utf-8"), special=True
            )
            if len(full_ids) <= len(prompt_ids) or len(full_ids) > self.n_ctx:
                continue
            self.llm.reset()
            self.llm.eval(full_ids)
            scores = np.asarray(self.llm.scores[: len(full_ids)], dtype=np.float64)
            if scores.ndim != 2 or not scores.any():
                return None
            steps: list[float] = []
            for position in range(len(prompt_ids) - 1, len(full_ids) - 1):
                logits = scores[position]
                shifted = logits - logits.max()
                log_z = float(np.log(np.exp(shifted).sum()))
                steps.append(log_z - float(shifted[full_ids[position + 1]]))
            if steps:
                losses.append(sum(steps) / len(steps))
        return round(sum(losses) / len(losses), 6) if losses else None


def llama_cpp_runtime_info(
    root: Path | str,
) -> dict[str, Any]:  # pragma: no cover - filesystem/VCS dependent
    """What the parity column was scored *in* — recorded, not assumed."""
    import subprocess

    info: dict[str, Any] = {"llamaCppDir": str(root)}
    try:
        info["llamaCppCommit"] = subprocess.run(
            ["git", "-C", str(root), "rev-parse", "--short", "HEAD"],
            capture_output=True, text=True, check=True, timeout=15,
        ).stdout.strip()
    except Exception:  # noqa: BLE001 - provenance is best-effort
        info["llamaCppCommit"] = ""
    try:
        import llama_cpp

        info["llamaCppPython"] = getattr(llama_cpp, "__version__", "")
    except ImportError:
        info["llamaCppPython"] = ""
    return info


__all__ = [
    "CONTRACT_VERSION",
    "CONVERTER_NAME",
    "DEFAULT_LLAMA_CPP_DIR",
    "DEFAULT_QUANT",
    "DOC_MARK_END",
    "DOC_MARK_START",
    "DOC_RUNTIME_KEYS",
    "GENERATION_CONTRACT",
    "HEADLINE_METRICS",
    "INTERMEDIATE_OUTTYPE",
    "MODELS_DIRNAME",
    "MODEL_SUBDIR",
    "QUANTIZER_NAME",
    "QUANT_BUDGET_ARM",
    "QUANT_BUDGET_METRIC",
    "QUANT_BUDGET_PP",
    "REPORT_VERSION",
    "RULE_SLOT",
    "USER_PROMPT_SLOT",
    "VERDICT_OVER",
    "VERDICT_UNMEASURED",
    "VERDICT_WITHIN",
    "ConversionPlan",
    "LlamaCppRuleModel",
    "build_parity_report",
    "build_plan",
    "build_prompt_contract",
    "convert_command",
    "extract_marked_section",
    "file_identity",
    "find_converter",
    "find_quantizer",
    "llama_cpp_dir",
    "llama_cpp_runtime_info",
    "merge_adapter",
    "model_stem",
    "parity_deltas",
    "quant_budget",
    "quantize_command",
    "render_parity_section",
    "require_llama_cpp_python",
    "require_llama_cpp_tools",
    "upsert_marked_section",
]
