"""The 3B baseline's comparison table + repeat aggregation (slm-pilot US-003).

US-002 proved the loop closes on the 0.5B debug model and recorded the finding
that shaped this module: **two identical MPS invocations of the same config gave
different adherence rates with the seed pinned.** So a US-003 number is never a
single draw — every stage is run ``config.repeats`` times at the *same* seed and
reported as a mean with its observed spread. A spread wider than the effect you
are claiming IS the finding.

What lives here (pure unless marked):

* :func:`aggregate_repeats` — mean / min / max / n per stage, arm and frozen
  metric across N repeats of :func:`~pinakes_ml.slm_finetune.run_pipeline`.
* :func:`build_comparison_table` — one row per **frozen** comparison point
  (:data:`~pinakes_ml.slm_pilot.COMPARISON_POINTS`), each either ``measured``
  with its metrics or ``not-measured`` **with a reason**. A comparison point is
  never silently dropped: the protocol froze the list, so an unmeasurable row
  states why (``docs/slm-pilot-protocol.md`` §4).
* :func:`ablation_gaps` — the grounded-minus-ungrounded gap on the fine-tuned
  weights: "did tuning internalise the vocabulary?"
* :func:`gap_closure` — the primary success bar's arithmetic, computed but NOT
  converted into a verdict. The verdict is US-006's, and it is gated on
  ``dataFloor.verdict`` which this report carries forward verbatim.
* :func:`build_baseline_report` / :func:`render_baseline_section` — the committed
  artifacts: a JSON report and the ``SLM-PILOT`` marked block upserted into
  ``docs/ml-baselines.md`` (the same cooperating-CLIs discipline as the
  ``KGQA-EVAL`` / ``SCALLOP-PILOT`` / ``RULE-ADHERENCE`` blocks).
* :class:`GeminiRuleModel` — the ``grounded-gemini`` comparison point behind the
  :class:`~pinakes_ml.slm_finetune.RuleModel` seam. Networked, undeclared
  dependency, local-only: it runs when a key is present and is recorded as
  ``not-measured`` with that reason when it is not.

CLI: ``pinakes-train-slm --repeats N`` (:mod:`pinakes_ml.train_slm`).
Runbook: ``docs/slm-pilot-runbook.md``.
"""

from __future__ import annotations

import os
from collections.abc import Mapping, Sequence
from typing import Any

from pinakes_ml.slm_finetune import (
    ARM_GROUNDED,
    ARM_UNGROUNDED,
    format_inference_prompt,
)
from pinakes_ml.slm_pilot import COMPARISON_POINTS, FROZEN_METRICS, PROTOCOL_VERSION

#: Bumped when the report's schema changes.
REPORT_VERSION = "1"

STAGE_UNTUNED = "untuned"
STAGE_FINETUNED = "finetuned"
#: The production path, scored through the identical harness on the identical
#: eval set — it is a comparison point, not a stage of the pipeline.
STAGE_GEMINI = "gemini"

#: Which (stage, arm) fills each frozen comparison point. The floor row has no
#: source: it is not reachable from pinakes (see :data:`NOT_MEASURED_REASONS`).
COMPARISON_SOURCES: dict[str, tuple[str, str]] = {
    "untuned-qwen2.5-3b-instruct": (STAGE_UNTUNED, ARM_GROUNDED),
    "finetuned-qwen2.5-3b-instruct": (STAGE_FINETUNED, ARM_GROUNDED),
    "finetuned-qwen2.5-3b-instruct-ungrounded": (STAGE_FINETUNED, ARM_UNGROUNDED),
    "grounded-gemini": (STAGE_GEMINI, ARM_GROUNDED),
}

#: Why a frozen comparison point could not be filled. Recorded on the row rather
#: than dropped — an unmeasured comparison point is a caveat on the verdict.
NOT_MEASURED_REASONS: dict[str, str] = {
    "deterministic-translator-floor": (
        "Insimul's VESPACE deterministic translator is not present in the "
        "checkout at ~/Development/workspace/insimul-platform (the repo was "
        "restructured); frozen as not-measured by the protocol, §4."
    ),
    "grounded-gemini": (
        "no GEMINI_API_KEY/GOOGLE_API_KEY in this environment — rerun with a key "
        "and `pinakes-train-slm --gemini` to fill this row."
    ),
}

#: The metrics the doc table shows. The full frozen list rides in the JSON
#: report; a nine-column markdown table is unreadable.
HEADLINE_METRICS: tuple[str, ...] = (
    "parseRate",
    "schemaValidity",
    "referentialIntegrity",
    "fullyValid",
    "reachabilityCharitable",
    "evalLoss",
)

#: The primary success bar (protocol §5) is stated on these two metrics.
GAP_METRICS: tuple[str, ...] = ("parseRate", "schemaValidity")

DOC_MARK_START = "<!-- SLM-PILOT:START (generated by pinakes-train-slm) -->"
DOC_MARK_END = "<!-- SLM-PILOT:END -->"


# --- repeat aggregation ---------------------------------------------------------


def aggregate_values(values: Sequence[float | None]) -> dict[str, Any] | None:
    """mean / min / max / n over the draws that produced a number.

    ``None`` draws are dropped rather than counted as zero (``evalLoss`` is
    ``None`` when a stage has no reference completions), and an all-``None``
    metric aggregates to ``None`` — absent, not 0.0.
    """
    present = [float(v) for v in values if isinstance(v, int | float)]
    if not present:
        return None
    return {
        "mean": round(sum(present) / len(present), 6),
        "min": round(min(present), 6),
        "max": round(max(present), 6),
        "n": len(present),
    }


def aggregate_repeats(
    summaries: Sequence[Mapping[str, Any]],
    *,
    metrics: Sequence[str] = FROZEN_METRICS,
    count_key: str = "prompts",
) -> dict[str, dict[str, dict[str, Any]]]:
    """``{stage: {arm: {metric: aggregate}}}`` over N run summaries.

    The repeats share one seed on purpose: the spread they expose is the
    platform's float nondeterminism (US-002's measured gotcha), not sampling.

    ``metrics``/``count_key`` are parameters so the sibling edit-ops pilot — whose
    frozen metric list differs and which counts ``cases``, not ``prompts`` — reuses
    this aggregation instead of forking it. The defaults are this pilot's.
    """
    stages: dict[str, dict[str, dict[str, Any]]] = {}
    for summary in summaries:
        for stage, arms in (summary.get("scores") or {}).items():
            for arm in arms:
                stages.setdefault(stage, {}).setdefault(arm, {})
    for stage, arms in stages.items():
        for arm in arms:
            draws = [
                (s.get("scores") or {}).get(stage, {}).get(arm, {}) for s in summaries
            ]
            cells: dict[str, Any] = {
                count_key: max(
                    (int(d.get(count_key, 0)) for d in draws if d.get(count_key)),
                    default=0,
                ),
                "repeats": len(draws),
            }
            for metric in metrics:
                cells[metric] = aggregate_values([d.get(metric) for d in draws])
            arms[arm] = cells
    return stages


def aggregate_single(
    arms: Mapping[str, Mapping[str, Any]],
    *,
    metrics: Sequence[str] = FROZEN_METRICS,
    count_key: str = "prompts",
) -> dict[str, dict[str, Any]]:
    """One un-repeated scoring pass, in :func:`aggregate_repeats`' shape.

    The ``grounded-gemini`` row is measured once (it is an API call, not a
    training run), so it joins the table as a single draw with ``n = 1`` rather
    than being folded into the repeat count of the local stages.
    """
    out: dict[str, dict[str, Any]] = {}
    for arm, scores in arms.items():
        cells: dict[str, Any] = {
            count_key: int(scores.get(count_key, 0) or 0),
            "repeats": 1,
        }
        for metric in metrics:
            cells[metric] = aggregate_values([scores.get(metric)])
        out[arm] = cells
    return out


def mean_of(
    aggregated: Mapping[str, Any], stage: str, arm: str, metric: str
) -> float | None:
    """The mean draw of one metric, or ``None`` when it was never measured."""
    cell = (aggregated.get(stage) or {}).get(arm, {}).get(metric)
    return None if cell is None else float(cell["mean"])


def spread_of(
    aggregated: Mapping[str, Any], stage: str, arm: str, metric: str
) -> float | None:
    """max − min across the repeats: how much of a gap is just the platform."""
    cell = (aggregated.get(stage) or {}).get(arm, {}).get(metric)
    return None if cell is None else round(float(cell["max"] - cell["min"]), 6)


# --- the frozen comparison table ------------------------------------------------


def build_comparison_table(
    aggregated: Mapping[str, Any],
    *,
    reasons: Mapping[str, str] = NOT_MEASURED_REASONS,
) -> list[dict[str, Any]]:
    """One row per frozen comparison point, in the frozen order.

    A row is ``measured`` only when the pipeline actually scored that (stage,
    arm); otherwise it carries ``status: "not-measured"`` and a reason. The list
    of rows is the protocol's, never the run's — a row cannot be dropped by
    failing to measure it.
    """
    rows: list[dict[str, Any]] = []
    for point in COMPARISON_POINTS:
        source = COMPARISON_SOURCES.get(point)
        scores = (
            (aggregated.get(source[0]) or {}).get(source[1]) if source else None
        )
        if scores:
            rows.append(
                {
                    "id": point,
                    "status": "measured",
                    "stage": source[0],
                    "arm": source[1],
                    "metrics": dict(scores),
                }
            )
        else:
            rows.append(
                {
                    "id": point,
                    "status": "not-measured",
                    "stage": source[0] if source else None,
                    "arm": source[1] if source else None,
                    "reason": reasons.get(point, "not measured by this run"),
                }
            )
    return rows


def ablation_gaps(aggregated: Mapping[str, Any]) -> dict[str, float]:
    """grounded − ungrounded on the FINE-TUNED weights, per frozen metric.

    Near zero ⇒ tuning internalised the vocabulary and Insimul can shrink the
    grounding block; large ⇒ the block must stay. Explicitly not part of the
    success bar (protocol §5) — informative either way.
    """
    gaps: dict[str, float] = {}
    for metric in FROZEN_METRICS:
        grounded = mean_of(aggregated, STAGE_FINETUNED, ARM_GROUNDED, metric)
        ungrounded = mean_of(aggregated, STAGE_FINETUNED, ARM_UNGROUNDED, metric)
        if grounded is not None and ungrounded is not None:
            gaps[metric] = round(grounded - ungrounded, 6)
    return gaps


def gap_closure(
    untuned: float | None, finetuned: float | None, reference: float | None
) -> float | None:
    """Fraction of the untuned→reference gap the tuned model closed.

    ``None`` when a term is missing or the reference is not above the untuned
    baseline — in which case "closing the gap" is not defined and reporting a
    ratio would invent a result.
    """
    if untuned is None or finetuned is None or reference is None:
        return None
    gap = reference - untuned
    if gap <= 0:
        return None
    return round((finetuned - untuned) / gap, 6)


def bar_inputs(aggregated: Mapping[str, Any]) -> dict[str, Any]:
    """The arithmetic behind the protocol's bars — inputs, never a verdict.

    US-006 owns the verdict and it is gated on ``dataFloor.verdict``; computing
    a pass/fail here would smuggle a judgment into the measurement story.
    """
    closure = {
        metric: gap_closure(
            mean_of(aggregated, STAGE_UNTUNED, ARM_GROUNDED, metric),
            mean_of(aggregated, STAGE_FINETUNED, ARM_GROUNDED, metric),
            mean_of(aggregated, STAGE_GEMINI, ARM_GROUNDED, metric),
        )
        for metric in GAP_METRICS
    }
    tuning_delta = {}
    for metric in FROZEN_METRICS:
        untuned = mean_of(aggregated, STAGE_UNTUNED, ARM_GROUNDED, metric)
        finetuned = mean_of(aggregated, STAGE_FINETUNED, ARM_GROUNDED, metric)
        if untuned is not None and finetuned is not None:
            tuning_delta[metric] = round(finetuned - untuned, 6)
    return {
        "gapClosedVsReference": closure,
        "tuningDelta": tuning_delta,
        "spreadAcrossRepeats": {
            metric: spread_of(aggregated, STAGE_FINETUNED, ARM_GROUNDED, metric)
            for metric in FROZEN_METRICS
        },
    }


# --- the report -----------------------------------------------------------------


def build_baseline_report(
    summaries: Sequence[Mapping[str, Any]],
    *,
    extra_stages: Mapping[str, Mapping[str, Mapping[str, Any]]] | None = None,
    data_floor: Mapping[str, Any] | None = None,
    wall_clock_seconds: float | None = None,
    cost_usd: float = 0.0,
    cost_note: str = "local Apple-Silicon MPS run — no GPU rental",
    reasons: Mapping[str, str] = NOT_MEASURED_REASONS,
) -> dict[str, Any]:
    """The committed US-003 artifact: every comparison point + how it was made.

    ``data_floor`` is copied **verbatim** from the frozen protocol manifest — the
    report never re-derives the sufficiency verdict (US-001's rule).
    """
    if not summaries:
        raise ValueError("a baseline report needs at least one run summary")
    head = summaries[0]
    aggregated = aggregate_repeats(summaries)
    for stage, arms in (extra_stages or {}).items():
        aggregated[stage] = aggregate_single(arms)
    return {
        "reportVersion": REPORT_VERSION,
        "protocolVersion": PROTOCOL_VERSION,
        "runName": head.get("runName", ""),
        "baseModel": head.get("baseModel", ""),
        "repeats": len(summaries),
        "stub": bool((head.get("training") or {}).get("stub")),
        "config": head.get("config", {}),
        "dataset": head.get("dataset", {}),
        "dataFloor": dict(data_floor) if data_floor else None,
        "training": {
            "device": (head.get("training") or {}).get("device", ""),
            "trainLossPerRepeat": [
                (s.get("training") or {}).get("trainLoss") for s in summaries
            ],
            "trainRuntimeSecondsPerRepeat": [
                (s.get("training") or {}).get("trainRuntimeSeconds") for s in summaries
            ],
        },
        "chatTemplateVerified": head.get("chatTemplateVerified"),
        "scores": aggregated,
        "comparison": build_comparison_table(aggregated, reasons=reasons),
        "ablation": ablation_gaps(aggregated),
        "bar": bar_inputs(aggregated),
        "cost": {
            "wallClockSeconds": wall_clock_seconds,
            "usd": cost_usd,
            "note": cost_note,
        },
    }


def _fmt(value: float | None, digits: int = 3) -> str:
    return "—" if value is None else f"{value:.{digits}f}"


def _cell(metrics: Mapping[str, Any], metric: str) -> str:
    agg = metrics.get(metric)
    if agg is None:
        return "—"
    digits = 2 if metric == "evalLoss" else 3
    mean = _fmt(agg["mean"], digits)
    low, high = _fmt(agg["min"], digits), _fmt(agg["max"], digits)
    # Only widen the cell when the repeats disagree *at the printed precision* —
    # "2.46 (2.46–2.46)" claims a disagreement the reader cannot see.
    if agg["n"] > 1 and low != high:
        return f"{mean} ({low}–{high})"
    return mean


def render_baseline_section(report: Mapping[str, Any]) -> str:
    """The ``SLM-PILOT`` marked block for ``docs/ml-baselines.md`` (pure).

    Marker-wrapped and upserted idempotently, so ``pinakes-train-baselines``
    preserves it across its from-scratch rewrite of the doc.
    """
    dataset = report.get("dataset") or {}
    floor = report.get("dataFloor") or {}
    verdict = floor.get("verdict")
    lines = [
        DOC_MARK_START,
        "",
        "## SLM pilot — rule-authoring baseline (Phase D, slm-pilot US-003)",
        "",
        f"Base model `{report['baseModel']}`, QLoRA on the DVC-pinned rule-SFT "
        f"corpus, scored by the **tier-4 adherence harness** on the frozen eval "
        f"set (`docs/slm-pilot-protocol.md`). "
        f"{report['repeats']} repeat(s) at one pinned seed; a cell shows the mean "
        "and, where the repeats disagreed, the observed range.",
        "",
        f"- eval set `sha256 {str(dataset.get('evalSetSha256', ''))[:12]}…`, "
        f"frozen: `{dataset.get('matchesFrozenEvalSet')}` — "
        f"{dataset.get('evalPromptsScored', 0)} prompts, "
        f"held out {', '.join(dataset.get('heldOutWorlds') or []) or 'none'}",
        f"- trained on {dataset.get('trainRecords', 0)} records, "
        f"DVC tree `{str(dataset.get('dvcMd5', '')) or '—'}`",
        f"- device `{(report.get('training') or {}).get('device', '')}`, "
        f"wall clock "
        f"{_fmt((report.get('cost') or {}).get('wallClockSeconds'), 1)} s, "
        f"cost ${(report.get('cost') or {}).get('usd', 0):.2f} "
        f"({(report.get('cost') or {}).get('note', '')})",
        "",
    ]
    if verdict:
        lines += [
            f"> ⚠️ **`dataFloor.verdict == \"{verdict}\"`.** "
            "The numbers below describe a *pipeline that completes the loop*, not "
            "an approach that validated. Per protocol §5 no verdict about the "
            "method may be drawn from them; US-006 reads this field rather than "
            "re-deriving it.",
            "",
        ]
    header = " | ".join(HEADLINE_METRICS)
    lines += [
        f"| Comparison point | {header} |",
        "| --- |" + " ---: |" * len(HEADLINE_METRICS),
    ]
    for row in report.get("comparison", []):
        if row["status"] == "measured":
            cells = " | ".join(
                _cell(row["metrics"], metric) for metric in HEADLINE_METRICS
            )
            lines.append(f"| `{row['id']}` | {cells} |")
        else:
            lines.append(
                f"| `{row['id']}` | " + " | ".join(["—"] * len(HEADLINE_METRICS)) + " |"
            )
    lines.append("")
    unmeasured = [r for r in report.get("comparison", []) if r["status"] != "measured"]
    if unmeasured:
        lines.append("Not measured, and why — a frozen comparison point is never "
                     "dropped, only explained:")
        lines.append("")
        lines += [f"- `{r['id']}` — {r['reason']}" for r in unmeasured]
        lines.append("")
    ablation = report.get("ablation") or {}
    if ablation:
        lines += [
            "### Ablation — does tuning internalise the vocabulary?",
            "",
            "Fine-tuned weights, grounded prompt **minus** the same weights on the "
            "vocabulary-stripped prompt. Not part of the success bar; informative "
            "either way (a small gap means Insimul can shrink the grounding block).",
            "",
            "| Metric | grounded − ungrounded |",
            "| --- | ---: |",
        ]
        lines += [
            f"| `{metric}` | {ablation[metric]:+.3f} |"
            for metric in FROZEN_METRICS
            if metric in ablation
        ]
        lines.append("")
    spread = (report.get("bar") or {}).get("spreadAcrossRepeats") or {}
    widest = max(
        ((v, k) for k, v in spread.items() if isinstance(v, int | float)),
        default=None,
    )
    if widest is not None and report["repeats"] > 1:
        lines += [
            f"Run-to-run spread at a pinned seed peaks at **{widest[0]:.3f}** "
            f"(`{widest[1]}`) — any claimed effect smaller than that is the "
            "platform's float nondeterminism, not the model.",
            "",
        ]
    lines += [
        "Reproduce: `cd ml && uv pip install trl peft accelerate && "
        "uv run pinakes-train-slm --config configs/slm-pilot-3b.json` "
        "(local/GPU-only; `--stub` is the CI-safe wiring smoke). "
        "Runbook: `docs/slm-pilot-runbook.md`.",
        "",
        DOC_MARK_END,
    ]
    return "\n".join(lines) + "\n"


def extract_marked_section(
    doc_text: str, start_mark: str = DOC_MARK_START, end_mark: str = DOC_MARK_END
) -> str | None:
    """The marked block (incl. markers) currently in the doc, or ``None``.

    The marks are parameters so a sibling pilot's block can reuse the same
    idempotent upsert rather than reimplementing it; they default to this
    module's, which is what ``pinakes-train-baselines`` imports.
    """
    start = doc_text.find(start_mark)
    end = doc_text.find(end_mark)
    if start == -1 or end == -1 or end < start:
        return None
    return doc_text[start : end + len(end_mark)]


def upsert_marked_section(
    doc_text: str,
    section: str,
    start_mark: str = DOC_MARK_START,
    end_mark: str = DOC_MARK_END,
) -> str:
    """Insert or replace a marked block. Idempotent; appends when absent."""
    if not section:
        return doc_text
    existing = extract_marked_section(doc_text, start_mark, end_mark)
    body = section if section.endswith("\n") else section + "\n"
    if existing is not None:
        replaced = doc_text.replace(existing, body.rstrip("\n"), 1)
        return replaced if replaced.endswith("\n") else replaced + "\n"
    prefix = doc_text if doc_text.endswith("\n") else doc_text + "\n"
    return f"{prefix}\n{body}"


# --- the grounded-Gemini comparison point (networked, local-only) ---------------

DEFAULT_GEMINI_MODEL = "gemini-2.0-flash"


def gemini_api_key() -> str:
    """The configured key, or ``""`` — which makes the row ``not-measured``."""
    return os.environ.get("GEMINI_API_KEY") or os.environ.get("GOOGLE_API_KEY") or ""


class GeminiRuleModel:  # pragma: no cover - networked, local-only
    """The production path behind the :class:`RuleModel` seam.

    Scored through the *identical* harness on the *identical* eval set as the
    Qwen rows — the protocol's whole point. It is prompted with the same ChatML
    string the local models see (:func:`format_inference_prompt`), so the only
    variable is the model. ``eval_loss`` is ``None``: the API exposes no
    teacher-forced loss, and the protocol already records that ``evalLoss`` is
    not comparable across model families.
    """

    def __init__(self, model_name: str = DEFAULT_GEMINI_MODEL) -> None:
        api_key = gemini_api_key()
        if not api_key:
            raise SystemExit(NOT_MEASURED_REASONS["grounded-gemini"])
        try:
            import google.generativeai as genai
        except ImportError as exc:  # not a declared dep — install on demand
            raise SystemExit(
                "google-generativeai is not installed. It is intentionally not a "
                "workspace dependency (the Gemini comparison point is optional). "
                "Install it with `uv pip install google-generativeai`."
            ) from exc

        genai.configure(api_key=api_key)
        self._genai = genai
        self.model_name = model_name
        self.model = genai.GenerativeModel(model_name)
        self.chat_template_verified = None

    def generate(self, prompt: str) -> str:
        response = self.model.generate_content(
            format_inference_prompt(prompt),
            generation_config={"temperature": 0.0, "max_output_tokens": 256},
        )
        return (getattr(response, "text", "") or "").strip()

    def eval_loss(self, pairs: Sequence[tuple[str, str]]) -> float | None:
        return None


__all__ = [
    "COMPARISON_SOURCES",
    "DOC_MARK_END",
    "DOC_MARK_START",
    "GAP_METRICS",
    "HEADLINE_METRICS",
    "NOT_MEASURED_REASONS",
    "REPORT_VERSION",
    "STAGE_FINETUNED",
    "STAGE_GEMINI",
    "STAGE_UNTUNED",
    "GeminiRuleModel",
    "ablation_gaps",
    "aggregate_repeats",
    "aggregate_single",
    "aggregate_values",
    "bar_inputs",
    "build_baseline_report",
    "build_comparison_table",
    "extract_marked_section",
    "gap_closure",
    "gemini_api_key",
    "mean_of",
    "render_baseline_section",
    "spread_of",
    "upsert_marked_section",
]
