"""Language families and languages, generated by Gemini and written to the corpus.

The port of `server/services/language-family-scraper-tsv.ts`, which
`POST /api/scraping/families` starts and then abandons — the response is a job
id, and everything below happens afterwards.

**This overwrites `families.tsv` and `languages.tsv` in full.** Nothing is
merged: the model's answer *becomes* the two tables, and the ~1,100 languages and
~180 families in the shipped corpus are gone the moment the last write lands.
`existingFamilies` is not a merge either — it is a list of names pasted into the
discovery prompt asking the model not to repeat them, so a successful run
replaces the corpus with **only what it did not already have**. That is what the
TypeScript does, it is what the dashboard's "Start Scraping" button has always
done, and the port reproduces it rather than quietly adding an append mode: the
two backends must not disagree about what that button costs while both are
running. :mod:`pinakes.lexicons.writer` says the same thing from the other end.

Three shapes below are worth reading before changing anything:

* **`clearExisting` is dead.** It is destructured out of the options and never
  read again — the flag the client posts has no effect on either backend.
  Carried as-is so that the parameter list still matches the caller.
* **A failed subtree is silent.** :func:`scrape_family_tree` catches everything,
  including its own key check, and answers ``([], [])``; the loop's own
  `try/except` around it is therefore unreachable. Ported both, because
  *removing* the unreachable one would be a judgement about a file that is
  about to be deleted, not a port of it.
* **Discovery failing is not.** :func:`discover_all_language_families` re-raises,
  so the job fails and neither TSV is touched. The asymmetry is the difference
  between "one branch of the tree is missing" and "there is no tree".
"""

from __future__ import annotations

import logging
import threading
from pathlib import Path
from typing import Any, Final, Protocol

from pinakes.contributions.store import iso_now, js_truthy
from pinakes.ingest import generation, jobs
from pinakes.lexicons import writer

logger = logging.getLogger("pinakes.ingest.family_scraper")

Record = dict[str, Any]


class ProgressCallback(Protocol):
    """``(type, message, data?) => void`` — the reporter the route passes in."""

    def __call__(self, type: str, message: str, data: Any = None) -> None: ...


#: `discoverAllLanguageFamilies`'s `responseSchema`. The REST wire spelling of
#: `SchemaType`, whose members are **lower case** (`SchemaType.OBJECT` is
#: `"object"`) — the SDK forwards them verbatim, so these are the bytes that go
#: over the wire on both backends.
DISCOVERY_SCHEMA: Final[dict[str, Any]] = {
    "type": "object",
    "properties": {
        "families": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": {"type": "string"},
                    "region": {"type": "string"},
                    "description": {"type": "string"},
                    "parentFamily": {"type": "string", "nullable": True},
                },
                "required": ["name", "region", "description"],
            },
        }
    },
    "required": ["families"],
}

#: `scrapeFamilyTree`'s `responseSchema`.
TREE_SCHEMA: Final[dict[str, Any]] = {
    "type": "object",
    "properties": {
        "families": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": {"type": "string"},
                    "taxonomicLevel": {"type": "string"},
                    "region": {"type": "string"},
                    "description": {"type": "string"},
                },
                "required": ["name", "region"],
            },
        },
        "languages": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": {"type": "string"},
                    "nativeName": {"type": "string", "nullable": True},
                    "iso639_1": {"type": "string", "nullable": True},
                    "iso639_2": {"type": "string", "nullable": True},
                    "subfamily": {"type": "string", "nullable": True},
                    "region": {"type": "string"},
                    "countries": {"type": "array", "items": {"type": "string"}},
                    "nativeSpeakers": {"type": "number", "nullable": True},
                    "totalSpeakers": {"type": "number", "nullable": True},
                    "status": {"type": "string"},
                    "writingSystem": {"type": "string", "nullable": True},
                },
                "required": ["name", "region", "status"],
            },
        },
    },
    "required": ["families", "languages"],
}

#: The static class field guarding concurrent runs. Module state here for the
#: same reason `_auth`'s counters are: it has to outlive the request that set it.
_lock = threading.Lock()
_scraping = False


class FamilyScrapeError(RuntimeError):
    """Anything the generator throws. The message reaches a job's `errorMessage`."""


def is_scraping() -> bool:
    """Whether a run currently holds the guard. The test seam."""
    with _lock:
        return _scraping


def reset() -> None:
    """Release the guard. Called in teardown; nothing in the service calls it."""
    global _scraping
    with _lock:
        _scraping = False


def _update_job(job_id: str | None, **updates: Any) -> None:
    """`updateJobStatus` — a no-op with no id, and it swallows its own failure."""
    if not job_id:
        return
    try:
        jobs.update_job(job_id, **updates)
    except Exception:  # noqa: BLE001 - the TypeScript's own catch
        logger.exception("Failed to update job status")


def build_discovery_prompt(existing_families: list[Record]) -> str:
    """The discovery prompt, word for word.

    ``existingFamilies.map(f => f.name.toLowerCase())`` and then the **first
    fifty** of them, comma-joined. Fifty is a prompt-size bound, not a corpus
    bound: a corpus with 180 families still asks the model to avoid only 50 of
    them, and the other 130 come back and are written again.
    """
    names = [str(family["name"]).lower() for family in existing_families]
    exclude = (
        "\n\nIMPORTANT: DO NOT include the following families that we already "
        "have:\n" + ", ".join(names[:50])
        if names
        else ""
    )
    return f"""You are a professional historical linguist. Generate a list of the 40 most significant language families and language isolates in the world.{exclude}

Guidelines:
- Include the MOST IMPORTANT language families by speaker count and historical significance:
  * Indo-European, Sino-Tibetan, Niger-Congo, Afroasiatic, Austronesian, Uralic
  * Dravidian, Altaic, Tai-Kadai, Austroasiatic, Japonic, Koreanic
  * Major American Indigenous families (Uto-Aztecan, Algonquian, Mayan, Quechuan, etc.)
  * Language isolates (Basque, Burushaski, Ainu, etc.)
- Keep descriptions brief (one sentence max)
- Set parentFamily to null for all (we'll get subfamilies later)
- Aim for exactly 40 families to keep response size manageable"""  # noqa: E501 - a prompt is a contract; rewrapping it changes it


def build_tree_prompt(family_name: str) -> str:
    """The per-family prompt. The tabs in the two format lines are real tabs."""
    return f"""You are a professional historical linguist. Generate a comprehensive hierarchical tree for the {family_name} language family.

The output will be written to TSV (Tab-Separated Values) files with these formats:

LANGUAGE FAMILIES TSV FORMAT:
id\tname\tparent_id\tdescription\ttaxonomic_level\tregion\ttotal_speakers\tlanguage_count

Example rows:
uralic\tUralic\t\tUralic language family\tfamily\tNorthern Eurasia\t25000000\t38
uralic__finnic\tFinnic\turalic\tFinnic branch of Uralic\tsubfamily\tNorthern Europe\t7000000\t12

LANGUAGES TSV FORMAT:
id\tname\tnative_name\tiso639_1\tiso639_2\tfamily_id\tregion\tcountries\tnative_speakers\ttotal_speakers\tstatus\twriting_system

Example rows:
fin\tFinnish\tSuomi\tfi\tfin\turalic__finnic\tNorthern Europe\tFinland\t5500000\t6000000\tliving\tLatin
ekk\tEstonian\tEesti\tet\tekk\turalic__finnic\tNorthern Europe\tEstonia\t1100000\t1200000\tliving\tLatin

Guidelines:
- Include major subfamilies (e.g., for Indo-European: Germanic, Romance, Slavic, Indo-Iranian, etc.)
- Include 20-50 major languages from this family
- Provide accurate ISO 639 codes when available (use ISO 639-2/3 for language IDs)
- Include speaker counts when known
- Set subfamily to null for languages that don't fit in a subfamily
- Use accurate native names for languages"""  # noqa: E501 - a prompt is a contract


def discover_all_language_families(
    progress: ProgressCallback | None = None,
    existing_families: list[Record] | None = None,
) -> list[Record]:
    """The forty top-level families, as `LanguageFamily` records.

    Every one is `parentId: null` / `taxonomicLevel: "family"` regardless of what
    the model answered — the schema asks for `parentFamily` and the mapping
    discards it, because the subfamily structure comes from the *second* prompt.

    *progress* is accepted and never called, as over there.
    """
    key = generation.api_key()
    if not js_truthy(key):
        raise FamilyScrapeError(f"{generation.GEMINI_API_KEY_ENV} not set")

    prompt = build_discovery_prompt(existing_families or [])
    try:
        parsed = generation.generate_json(prompt, DISCOVERY_SCHEMA, key)

        families = parsed.get("families") if isinstance(parsed, dict) else None
        if not isinstance(families, list):
            raise FamilyScrapeError("Invalid response structure from Gemini")

        return [
            {
                "id": generation.slugify(family.get("name")),
                "name": family.get("name"),
                "parentId": None,
                "description": _or_none(family.get("description")),
                "taxonomicLevel": "family",
                "region": _or_none(family.get("region")),
                "totalSpeakers": None,
                "languageCount": None,
                "source": "scraped",
            }
            for family in families
        ]
    except Exception:
        # `catch { console.error(...); throw error }` — logged here and again by
        # the caller, which is what the TypeScript does.
        logger.exception("Failed to discover language families")
        raise


def scrape_family_tree(family: Record) -> tuple[list[Record], list[Record]]:
    """One family's subfamilies and languages, or ``([], [])`` on any failure.

    A language is filed under a subfamily only when its declared `subfamily`
    matches one the model generated in the *same* answer, compared through
    :func:`pinakes.ingest.generation.normalize`; an unmatched one falls back to
    the top-level family rather than being dropped. Its id is the ISO 639-2 code
    when there is one and a slug of its name otherwise, so two languages that
    slug alike collide — the writer keeps both rows.
    """
    try:
        key = generation.api_key()
        if not js_truthy(key):
            raise FamilyScrapeError(f"{generation.GEMINI_API_KEY_ENV} not set")

        parsed = generation.generate_json(
            build_tree_prompt(family["name"]), TREE_SCHEMA, key
        )
        raw = parsed if isinstance(parsed, dict) else {}

        subfamilies: list[Record] = [
            {
                "id": f"{family['id']}__{generation.slugify(item.get('name'))}",
                "name": item.get("name"),
                "parentId": family["id"],
                "description": _or_none(item.get("description")),
                "taxonomicLevel": _or_default(item.get("taxonomicLevel"), "subfamily"),
                "region": _or_none(item.get("region")),
                "totalSpeakers": None,
                "languageCount": None,
                "source": "scraped",
            }
            for item in _mappable(raw.get("families"))
        ]

        by_name = {
            generation.normalize(sub["name"]): sub["id"] for sub in subfamilies
        }

        languages: list[Record] = []
        for item in _mappable(raw.get("languages")):
            family_id = family["id"]
            subfamily = item.get("subfamily")
            if js_truthy(subfamily):
                matched = by_name.get(generation.normalize(subfamily))
                if matched is not None:
                    family_id = matched
            iso2 = item.get("iso639_2")
            languages.append(
                {
                    "id": iso2
                    if js_truthy(iso2)
                    else generation.slugify(item.get("name")),
                    "name": item.get("name"),
                    "nativeName": _or_none(item.get("nativeName")),
                    "iso639_1": _or_none(item.get("iso639_1")),
                    "iso639_2": _or_none(iso2),
                    "familyId": family_id,
                    "parentLanguageId": None,
                    "region": _or_none(item.get("region")),
                    "countries": item.get("countries")
                    if isinstance(item.get("countries"), list)
                    else [],
                    "nativeSpeakers": _or_none(item.get("nativeSpeakers")),
                    "totalSpeakers": _or_none(item.get("totalSpeakers")),
                    "status": _or_default(item.get("status"), "living"),
                    "endangermentStatus": None,
                    "timeOrigin": None,
                    "timeEnd": None,
                    "classification": None,
                    "writingSystem": _or_none(item.get("writingSystem")),
                    "isHistoricalVariant": False,
                    "isDialect": False,
                    "chronologicalOrder": 0,
                    "historicalContext": None,
                    "coordinates": None,
                    "source": "scraped",
                }
            )
        return subfamilies, languages
    except Exception:  # noqa: BLE001 - the TypeScript swallows every failure here
        logger.exception("Failed to scrape family tree for %s", family.get("name"))
        return [], []


def scrape_language_families(
    lexicons: Path,
    *,
    clear_existing: bool = False,  # noqa: ARG001 - destructured and never read
    family_filter: Any = None,
    existing_families: list[Record] | None = None,
    job_id: str | None = None,
    progress: ProgressCallback | None = None,
) -> dict[str, list[Record]]:
    """Discover, expand, and **replace** `families.tsv` and `languages.tsv`."""
    global _scraping

    if not js_truthy(generation.api_key()):
        raise FamilyScrapeError(
            f"{generation.GEMINI_API_KEY_ENV} environment variable is required "
            "for scraping"
        )
    with _lock:
        if _scraping:
            raise FamilyScrapeError(
                "Language family scraping is already in progress"
            )
        _scraping = True

    try:
        _update_job(job_id, status="running", startedAt=iso_now())
        if progress:
            progress("progress", "Discovering language families...")

        families = discover_all_language_families(progress, existing_families or [])

        if progress:
            progress(
                "progress", f"Discovered {len(families)} language families"
            )

        all_families: list[Record] = []
        all_languages: list[Record] = []

        if js_truthy(family_filter):
            top_level = [f for f in families if f["id"] == family_filter]
        else:
            top_level = [f for f in families if not js_truthy(f["parentId"])]

        _update_job(job_id, totalWords=len(top_level))

        for index, family in enumerate(top_level):
            if progress:
                progress(
                    "progress",
                    f"Scraping family {index + 1}/{len(top_level)}: "
                    f"{family['name']}...",
                )
            try:
                sub_families, languages = scrape_family_tree(family)
                all_families.extend(sub_families)
                all_languages.extend(languages)
                _update_job(job_id, completedWords=index + 1)
            except Exception as error:  # noqa: BLE001 - unreachable; see the module docstring
                logger.exception("Failed to scrape family tree")
                if progress:
                    progress(
                        "error",
                        f"Failed to scrape {family['name']}: {_js_error(error)}",
                    )

        all_families.extend(families)

        if progress:
            progress("progress", "Writing to TSV files...")

        writer.write_language_family_tsv(all_families, lexicons / "families.tsv")
        writer.write_language_tsv(all_languages, lexicons / "languages.tsv")

        _update_job(
            job_id,
            status="completed",
            completedWords=len(top_level),
            completedAt=iso_now(),
        )
        if progress:
            progress("completed", "Scraping completed successfully!")

        return {"families": all_families, "languages": all_languages}
    except Exception as error:
        logger.exception("Error during language family scraping")
        _update_job(
            job_id,
            status="failed",
            errorMessage=str(error),
            completedAt=iso_now(),
        )
        if progress:
            progress("error", f"Scraping failed: {_js_error(error)}")
        raise
    finally:
        with _lock:
            _scraping = False


def _mappable(value: Any) -> list[Any]:
    """``(value || []).map(...)`` — a truthy non-array has no `.map` and throws.

    Python would happily iterate a string one character at a time, which is the
    trap `dataset/export.py`'s `includeFiles` note names from the other side.
    """
    if not js_truthy(value):
        return []
    if not isinstance(value, list):
        raise FamilyScrapeError(f"{value}.map is not a function")
    return value


def _or_none(value: Any) -> Any:
    """``value || null`` — truthy, so a blank string and a ``0`` become null."""
    return value if js_truthy(value) else None


def _or_default(value: Any, fallback: str) -> Any:
    """``value || "<fallback>"``."""
    return value if js_truthy(value) else fallback


def _js_error(error: BaseException) -> str:
    """``${error}`` on an `Error` — the class name, a colon, then the message.

    Both progress messages interpolate the caught value rather than its
    `.message`, so what a dashboard shows carries the prefix. Every throw in
    this file and its callee is a plain `Error`, so the prefix is constant.
    """
    return f"Error: {error}"


__all__ = [
    "DISCOVERY_SCHEMA",
    "TREE_SCHEMA",
    "FamilyScrapeError",
    "ProgressCallback",
    "build_discovery_prompt",
    "build_tree_prompt",
    "discover_all_language_families",
    "is_scraping",
    "reset",
    "scrape_family_tree",
    "scrape_language_families",
]
