"""Deities and myth motifs, generated by Gemini and written to the corpus.

The port of `server/services/mythology-scraper-tsv.ts`, started by
`POST /api/scraping/mythology` and, like its sibling
:mod:`pinakes.ingest.family_scraper`, abandoned by the response.

**It overwrites `deities.tsv` and `myth-motifs.tsv` in full**, with the same
consequence: the corpus's ~700 deities are replaced by whatever the model
answered. `loadExistingDeityIds` is not a merge — it is thirty ids pasted into
the prompt asking for *new information* about them, so a run that honours the
request writes a strictly smaller table.

Three passes, and only the first is failure-tolerant:

* **Per pantheon.** :func:`scrape_deities_for_pantheon` throws on failure and
  the loop catches it, reports it through the progress callback, and moves on —
  so a job can complete having lost a pantheon. The job's `completedWords` is
  stamped **outside** that catch, so a failed pantheon still counts as done.
* **Syncretism.** :func:`build_syncretism_links` is the one step that degrades:
  a model that answers without a `links` array warns and returns the deities
  unlinked. Any other failure propagates and fails the job.
* **Motifs.** :func:`scrape_myth_motifs` throws, and nothing catches it, so
  neither TSV is written. A corpus with deities and no motifs is not a state
  this generator can produce.

`totalWords` is ``len(pantheons) + 1`` — the pantheons plus one unit standing
for the syncretism and motif passes together, which is why `completedWords`
reaches the total only after both.
"""

from __future__ import annotations

import logging
import threading
from pathlib import Path
from typing import Any, Final

from pinakes.authoring._js import json_text
from pinakes.contributions.store import iso_now, js_truthy
from pinakes.ingest import generation, jobs
from pinakes.ingest.family_scraper import ProgressCallback
from pinakes.lexicons import writer

logger = logging.getLogger("pinakes.ingest.mythology_scraper")

Record = dict[str, Any]

#: The eighteen pantheons a request with no `pantheons` body field asks for, in
#: the order they are scraped and therefore the order deities are written in.
DEFAULT_PANTHEONS: Final[tuple[str, ...]] = (
    "greek",
    "roman",
    "norse",
    "egyptian",
    "hindu",
    "mesopotamian",
    "celtic",
    "japanese",
    "chinese",
    "aztec",
    "maya",
    "yoruba",
    "slavic",
    "polynesian",
    "inuit",
    "zoroastrian",
    "canaanite",
    "hittite",
)

#: `writeDeitiesToTsv`'s header.
DEITY_HEADERS: Final[tuple[str, ...]] = (
    "id",
    "name",
    "native_name",
    "pantheon",
    "domain",
    "gender",
    "syncretism_links",
    "associated_religion_ids",
    "associated_language_ids",
    "time_origin",
    "time_end",
    "coordinates",
    "description",
    "sources",
)

#: `writeMotifsToTsv`'s header.
MOTIF_HEADERS: Final[tuple[str, ...]] = (
    "id",
    "name",
    "motif_type",
    "atu_index",
    "description",
    "examples",
    "associated_religion_ids",
    "associated_deity_ids",
    "geographic_distribution",
    "time_depth",
    "sources",
)

#: `scrapeDeitiesForPantheon`'s `responseSchema`. Note `lat`/`lng` are **flat**
#: here and become a nested `coordinates` object in the mapping — the schema
#: cannot ask for a nullable object, which is why.
DEITY_SCHEMA: Final[dict[str, Any]] = {
    "type": "object",
    "properties": {
        "deities": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "id": {"type": "string"},
                    "name": {"type": "string"},
                    "nativeName": {"type": "string"},
                    "domain": {"type": "array", "items": {"type": "string"}},
                    "gender": {"type": "string"},
                    "associatedReligionIds": {
                        "type": "array",
                        "items": {"type": "string"},
                    },
                    "associatedLanguageIds": {
                        "type": "array",
                        "items": {"type": "string"},
                    },
                    "timeOrigin": {"type": "number", "nullable": True},
                    "timeEnd": {"type": "number", "nullable": True},
                    "lat": {"type": "number", "nullable": True},
                    "lng": {"type": "number", "nullable": True},
                    "description": {"type": "string"},
                    "sources": {"type": "array", "items": {"type": "string"}},
                },
                "required": ["id", "name", "domain", "gender", "description"],
            },
        }
    },
    "required": ["deities"],
}

#: `buildSyncretismLinks`'s `responseSchema`.
SYNCRETISM_SCHEMA: Final[dict[str, Any]] = {
    "type": "object",
    "properties": {
        "links": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "deityId": {"type": "string"},
                    "equivalents": {"type": "array", "items": {"type": "string"}},
                },
                "required": ["deityId", "equivalents"],
            },
        }
    },
    "required": ["links"],
}

#: `scrapeMythMotifs`'s `responseSchema`.
MOTIF_SCHEMA: Final[dict[str, Any]] = {
    "type": "object",
    "properties": {
        "motifs": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "id": {"type": "string"},
                    "name": {"type": "string"},
                    "motifType": {"type": "string"},
                    "atuIndex": {"type": "string", "nullable": True},
                    "description": {"type": "string"},
                    "examples": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "culture": {"type": "string"},
                                "narrative": {"type": "string"},
                            },
                            "required": ["culture", "narrative"],
                        },
                    },
                    "associatedReligionIds": {
                        "type": "array",
                        "items": {"type": "string"},
                    },
                    "associatedDeityIds": {
                        "type": "array",
                        "items": {"type": "string"},
                    },
                    "geographicDistribution": {
                        "type": "array",
                        "items": {"type": "string"},
                    },
                    "timeDepth": {"type": "number", "nullable": True},
                    "sources": {"type": "array", "items": {"type": "string"}},
                },
                "required": ["id", "name", "motifType", "description", "examples"],
            },
        }
    },
    "required": ["motifs"],
}

_lock = threading.Lock()
_scraping = False


class MythologyScrapeError(RuntimeError):
    """Anything the generator throws. Reaches a job's `errorMessage`."""


def is_scraping() -> bool:
    """Whether a run currently holds the guard. The test seam."""
    with _lock:
        return _scraping


def reset() -> None:
    """Release the guard. Called in teardown; nothing in the service calls it."""
    global _scraping
    with _lock:
        _scraping = False


def _update_job(job_id: str | None, **updates: Any) -> None:
    """`updateJobStatus` — a no-op with no id, and it swallows its own failure."""
    if not job_id:
        return
    try:
        jobs.update_job(job_id, **updates)
    except Exception:  # noqa: BLE001 - the TypeScript's own catch
        logger.exception("Failed to update job status")


def load_existing_deity_ids(lexicons: Path) -> list[str]:
    """The first column of `deities.tsv`, header skipped, blanks dropped.

    A `Set` over there, so the order is first-seen and duplicates collapse — the
    prompt slices thirty off the front of it, so which thirty depends on file
    order. A list is used here because that ordering is the observable part; the
    dedup is done explicitly. A missing or unreadable file is no ids at all.
    """
    path = lexicons / "deities.tsv"
    try:
        with open(path, encoding="utf-8", newline="") as handle:
            text = handle.read()
    except OSError:
        return []
    ids: list[str] = []
    seen: set[str] = set()
    for line in text.strip().split("\n")[1:]:
        identifier = line.split("\t")[0]
        if identifier and identifier not in seen:
            seen.add(identifier)
            ids.append(identifier)
    return ids


def build_deity_prompt(pantheon: str, existing_ids: list[str]) -> str:
    """The per-pantheon prompt, word for word. Thirty existing ids at most."""
    exclude = (
        "\nIMPORTANT: We already have these deity IDs, so only include them if "
        "you can add NEW information: " + ", ".join(existing_ids[:30])
        if existing_ids
        else ""
    )
    return f"""You are a comparative mythology scholar. Generate a comprehensive list of deities from the {pantheon} mythology/religion.{exclude}

For each deity provide:
- id: lowercase snake_case identifier (e.g., "zeus", "ra", "odin")
- name: English name
- nativeName: Name in original script/language if available
- domain: Array of domains/aspects (e.g., ["sky", "thunder", "kingship"])
- gender: "male", "female", or "non-binary"
- associatedReligionIds: Array of religion IDs (e.g., ["ancient-greek-religion"])
- associatedLanguageIds: Array of language IDs (e.g., ["ancient-greek"])
- timeOrigin: Approximate year worship began (negative for BCE)
- timeEnd: Approximate year worship ended (negative for BCE, null if still active)
- coordinates: Lat/lng of primary cult center {{lat, lng}}
- description: One sentence description
- sources: Array of scholarly sources

Include 10-20 major deities for this pantheon. Focus on the most important and well-documented figures."""  # noqa: E501 - a prompt is a contract


def build_syncretism_prompt(deities: list[Record]) -> str:
    """The syncretism prompt. The deity list is `id (pantheon): name - domains`."""
    summary = "\n".join(
        f"{deity['id']} ({deity['pantheon']}): {deity['name']} - "
        + ", ".join(deity["domain"])
        for deity in deities
    )
    return f"""You are a comparative mythology scholar. Given the following list of deities from multiple pantheons, identify cross-cultural equivalents (syncretism links).

DEITY LIST:
{summary}

For each deity that has equivalents in other pantheons, provide the links. A syncretism link means the deities share similar roles, domains, or were historically identified with each other (e.g., Zeus = Jupiter = Indra for sky/thunder gods).

Rules:
- Only link deities with genuine scholarly connections (interpretatio graeca/romana, shared PIE origins, documented syncretism)
- Links must be bidirectional (if A links to B, B must link to A)
- Use the exact deity IDs from the list above
- Focus on well-established connections, not speculative ones"""  # noqa: E501 - a prompt is a contract


def build_motif_prompt(deities: list[Record]) -> str:
    """The motif prompt. Deity ids are grouped by pantheon, first-seen order."""
    by_pantheon: dict[str, list[str]] = {}
    for deity in deities:
        by_pantheon.setdefault(deity["pantheon"], []).append(deity["id"])
    summary = "\n".join(
        f"{pantheon}: " + ", ".join(ids) for pantheon, ids in by_pantheon.items()
    )
    return f"""You are a comparative mythology scholar. Generate a comprehensive list of universal myth motifs found across multiple cultures.

Available deity IDs by pantheon:
{summary}

For each motif provide:
- id: lowercase hyphen-separated identifier (e.g., "flood-myth", "world-tree")
- name: Display name
- motifType: One of: cosmology, cataclysm, creation, hero, death-rebirth, archetype, fertility, transformation, underworld, celestial, culture-hero, eschatology
- atuIndex: Aarne-Thompson-Uther index if applicable, null otherwise
- description: One-sentence scholarly description
- examples: Array of {{culture, narrative}} objects showing how this motif appears in different traditions (at least 3 cultures each)
- associatedReligionIds: Array of religion IDs
- associatedDeityIds: Array of deity IDs from the list above that are associated with this motif
- geographicDistribution: Array of regions (e.g., ["Global"], ["Mediterranean", "Near East"])
- timeDepth: Approximate age in years BCE (negative number)
- sources: Array of scholarly sources

Generate 30-40 motifs covering diverse categories. Each motif MUST have cross-cultural examples from at least 3 different traditions."""  # noqa: E501 - a prompt is a contract


def scrape_deities_for_pantheon(
    pantheon: str, existing_ids: list[str]
) -> list[Record]:
    """One pantheon's deities. Raises on a model failure — the loop catches it."""
    key = generation.api_key()
    if not js_truthy(key):
        raise MythologyScrapeError(f"{generation.GEMINI_API_KEY_ENV} not set")

    parsed = generation.generate_json(
        build_deity_prompt(pantheon, existing_ids), DEITY_SCHEMA, key
    )
    deities = parsed.get("deities") if isinstance(parsed, dict) else None
    if not isinstance(deities, list):
        raise MythologyScrapeError(
            f"Invalid response structure for {pantheon} deities"
        )

    records: list[Record] = []
    for item in deities:
        lat = item.get("lat")
        lng = item.get("lng")
        records.append(
            {
                "id": generation.slugify(_or_value(item.get("id"), item.get("name"))),
                "name": item.get("name"),
                "nativeName": _or_default(item.get("nativeName"), ""),
                "pantheon": pantheon,
                "domain": _array(item.get("domain")),
                "gender": _or_default(item.get("gender"), "unknown"),
                "syncretismLinks": [],
                "associatedReligionIds": _array(item.get("associatedReligionIds")),
                "associatedLanguageIds": _array(item.get("associatedLanguageIds")),
                # `?? null` — *nullish*, so a `timeOrigin` of 0 survives where
                # `nativeName` of "" does not. Both spellings are in this map.
                "timeOrigin": item.get("timeOrigin"),
                "timeEnd": item.get("timeEnd"),
                "coordinates": {"lat": lat, "lng": lng}
                if lat is not None and lng is not None
                else None,
                "description": _or_default(item.get("description"), ""),
                "sources": _array(item.get("sources")),
            }
        )
    return records


def build_syncretism_links(deities: list[Record]) -> list[Record]:
    """Cross-pantheon equivalents, forced bidirectional and filtered to known ids.

    The one degrading step: an answer with no `links` array warns and hands the
    deities back unlinked, because an unlinked pantheon is still a pantheon.
    """
    key = generation.api_key()
    if not js_truthy(key):
        raise MythologyScrapeError(f"{generation.GEMINI_API_KEY_ENV} not set")

    parsed = generation.generate_json(
        build_syncretism_prompt(deities), SYNCRETISM_SCHEMA, key
    )
    links = parsed.get("links") if isinstance(parsed, dict) else None
    if not isinstance(links, list):
        logger.warning(
            "Could not parse syncretism links, returning deities without links"
        )
        return deities

    known: set[Any] = {deity["id"] for deity in deities}
    link_map: dict[Any, list[Any]] = {}
    for link in links:
        deity_id = link.get("deityId") if isinstance(link, dict) else None
        if deity_id not in known:
            continue
        link_map.setdefault(deity_id, [])
        for equivalent in link.get("equivalents") or []:
            if equivalent not in known:
                continue
            if equivalent not in link_map[deity_id]:
                link_map[deity_id].append(equivalent)
            partner = link_map.setdefault(equivalent, [])
            if deity_id not in partner:
                partner.append(deity_id)

    return [
        {**deity, "syncretismLinks": list(link_map.get(deity["id"], []))}
        for deity in deities
    ]


def scrape_myth_motifs(deities: list[Record]) -> list[Record]:
    """The universal motifs. Deity references not in *deities* are dropped."""
    key = generation.api_key()
    if not js_truthy(key):
        raise MythologyScrapeError(f"{generation.GEMINI_API_KEY_ENV} not set")

    parsed = generation.generate_json(
        build_motif_prompt(deities), MOTIF_SCHEMA, key
    )
    motifs = parsed.get("motifs") if isinstance(parsed, dict) else None
    if not isinstance(motifs, list):
        raise MythologyScrapeError("Invalid response structure for myth motifs")

    known = {deity["id"] for deity in deities}
    records: list[Record] = []
    for item in motifs:
        associated = item.get("associatedDeityIds")
        records.append(
            {
                # `slugify` writes underscores; this is the one place they are
                # translated back to hyphens, so `flood myth` is `flood-myth`.
                "id": generation.slugify(
                    _or_value(item.get("id"), item.get("name"))
                ).replace("_", "-"),
                "name": item.get("name"),
                "motifType": _or_default(item.get("motifType"), "archetype"),
                "atuIndex": _or_default(item.get("atuIndex"), None),
                "description": _or_default(item.get("description"), ""),
                "examples": _array(item.get("examples")),
                "associatedReligionIds": _array(item.get("associatedReligionIds")),
                "associatedDeityIds": [
                    identifier
                    for identifier in associated
                    if identifier in known
                ]
                if isinstance(associated, list)
                else [],
                "geographicDistribution": _array(
                    item.get("geographicDistribution")
                ),
                "timeDepth": item.get("timeDepth"),
                "sources": _array(item.get("sources")),
            }
        )
    return records


def write_deities_tsv(deities: list[Record], lexicons: Path) -> None:
    """`deities.tsv`. Every array column is a `JSON.stringify` cell."""
    rows = [
        [
            writer.cell(deity["id"]),
            writer.cell(deity["name"]),
            writer.cell(deity["nativeName"]),
            writer.cell(deity["pantheon"]),
            json_text(deity["domain"]),
            writer.cell(deity["gender"]),
            json_text(deity["syncretismLinks"]),
            json_text(deity["associatedReligionIds"]),
            json_text(deity["associatedLanguageIds"]),
            writer.cell(deity["timeOrigin"]),
            writer.cell(deity["timeEnd"]),
            json_text(deity["coordinates"])
            if deity["coordinates"] is not None
            else "",
            writer.cell(deity["description"]),
            json_text(deity["sources"]),
        ]
        for deity in deities
    ]
    writer.write_tsv(lexicons / "deities.tsv", list(DEITY_HEADERS), rows)


def write_motifs_tsv(motifs: list[Record], lexicons: Path) -> None:
    """`myth-motifs.tsv`."""
    rows = [
        [
            writer.cell(motif["id"]),
            writer.cell(motif["name"]),
            writer.cell(motif["motifType"]),
            writer.cell(motif["atuIndex"]),
            writer.cell(motif["description"]),
            json_text(motif["examples"]),
            json_text(motif["associatedReligionIds"]),
            json_text(motif["associatedDeityIds"]),
            json_text(motif["geographicDistribution"]),
            writer.cell(motif["timeDepth"]),
            json_text(motif["sources"]),
        ]
        for motif in motifs
    ]
    writer.write_tsv(lexicons / "myth-motifs.tsv", list(MOTIF_HEADERS), rows)


def scrape_mythology(
    lexicons: Path,
    *,
    pantheons: Any = None,
    job_id: str | None = None,
    progress: ProgressCallback | None = None,
) -> dict[str, list[Record]]:
    """Scrape every pantheon, link them, generate motifs, **replace** both TSVs."""
    global _scraping

    if not js_truthy(generation.api_key()):
        raise MythologyScrapeError(
            f"{generation.GEMINI_API_KEY_ENV} environment variable is required "
            "for scraping"
        )
    with _lock:
        if _scraping:
            raise MythologyScrapeError("Mythology scraping is already in progress")
        _scraping = True

    try:
        _update_job(job_id, status="running", startedAt=iso_now())
        if progress:
            progress("progress", "Loading existing deity data...")

        existing_ids = load_existing_deity_ids(lexicons)

        targets = _targets(pantheons)

        _update_job(job_id, totalWords=len(targets) + 1)
        if progress:
            progress(
                "progress", f"Scraping deities for {len(targets)} pantheons..."
            )

        all_deities: list[Record] = []
        for index, pantheon in enumerate(targets):
            if progress:
                progress(
                    "progress",
                    f"Scraping {pantheon} pantheon "
                    f"({index + 1}/{len(targets)})...",
                )
            try:
                all_deities.extend(
                    scrape_deities_for_pantheon(pantheon, existing_ids)
                )
            except Exception as error:  # noqa: BLE001 - a lost pantheon is not a lost job
                logger.exception("Failed to scrape %s pantheon", pantheon)
                if progress:
                    progress(
                        "error",
                        f"Failed to scrape {pantheon}: {_js_error(error)}",
                    )
            # Outside the catch: a pantheon that failed still counts as done.
            _update_job(job_id, completedWords=index + 1)

        if progress:
            progress("progress", "Building cross-cultural syncretism links...")
        linked = build_syncretism_links(all_deities)

        if progress:
            progress(
                "progress", "Scraping myth motifs with cross-cultural examples..."
            )
        motifs = scrape_myth_motifs(linked)

        _update_job(job_id, completedWords=len(targets) + 1)

        if progress:
            progress("progress", "Writing to TSV files...")

        write_deities_tsv(linked, lexicons)
        write_motifs_tsv(motifs, lexicons)

        _update_job(job_id, status="completed", completedAt=iso_now())
        if progress:
            progress(
                "completed",
                f"Scraping completed: {len(linked)} deities, "
                f"{len(motifs)} motifs",
            )

        return {"deities": linked, "motifs": motifs}
    except Exception as error:
        logger.exception("Error during mythology scraping")
        _update_job(
            job_id,
            status="failed",
            errorMessage=str(error),
            completedAt=iso_now(),
        )
        if progress:
            progress("error", f"Scraping failed: {_js_error(error)}")
        raise
    finally:
        with _lock:
            _scraping = False


def _targets(pantheons: Any) -> list[Any]:
    """``pantheons || DEFAULT_PANTHEONS``, with JavaScript's truthiness.

    **An empty list is not "no preference".** ``[]`` is truthy in JavaScript, so
    ``{"pantheons": []}`` really does scrape nothing at all and write two empty
    tables over the corpus — where Python's own truthiness would have quietly
    substituted the eighteen defaults. This is the whole reason for
    :func:`~pinakes.contributions.store.js_truthy` here.

    A string indexes like an array over there, so it is scraped character by
    character. Anything else truthy has no length and no indices, which makes
    the loop empty; the `totalWords` it stamps is `NaN` on Express and 1 here,
    the one place this function does not reproduce a body no client sends.
    """
    if not js_truthy(pantheons):
        return list(DEFAULT_PANTHEONS)
    if isinstance(pantheons, (list, str)):
        return list(pantheons)
    return []


def _array(value: Any) -> list[Any]:
    """``Array.isArray(v) ? v : []``."""
    return value if isinstance(value, list) else []


def _or_value(value: Any, fallback: Any) -> Any:
    """``value || fallback``, where the fallback is another field."""
    return value if js_truthy(value) else fallback


def _or_default(value: Any, fallback: Any) -> Any:
    """``value || <literal>``."""
    return value if js_truthy(value) else fallback


def _js_error(error: BaseException) -> str:
    """``${error}`` on an `Error` — the class name, a colon, then the message."""
    return f"Error: {error}"


__all__ = [
    "DEFAULT_PANTHEONS",
    "DEITY_HEADERS",
    "DEITY_SCHEMA",
    "MOTIF_HEADERS",
    "MOTIF_SCHEMA",
    "SYNCRETISM_SCHEMA",
    "MythologyScrapeError",
    "build_deity_prompt",
    "build_motif_prompt",
    "build_syncretism_prompt",
    "build_syncretism_links",
    "is_scraping",
    "load_existing_deity_ids",
    "reset",
    "scrape_deities_for_pantheon",
    "scrape_myth_motifs",
    "scrape_mythology",
    "write_deities_tsv",
    "write_motifs_tsv",
]
