// Generated by agora translation engine: incrementally MERGE canonical data into Neo4j.
// Idempotent — re-running does not duplicate nodes or relationships.
// Requires the APOC plugin. Run with: cypher-shell -f neo4j-load-csv.cypher

// node: nodes/CulturalArtifact.tsv
:param file => 'nodes/CulturalArtifact.tsv';
LOAD CSV WITH HEADERS FROM $file AS row FIELDTERMINATOR '\t'
MERGE (n:Entity {`csid`: row.`csid:ID`})
SET n += {
  `name`: row.`name`,
  `lang`: row.`lang`,
  `wikidata_qid`: row.`wikidata_qid`,
  `getty_id`: row.`getty_id`,
  `aliases`: split(row.`aliases`, ';'),
  `description`: row.`description`,
  `pinakes_id`: row.`pinakes_id`,
  `time_start`: toInteger(row.`time_start:int`),
  `time_end`: toInteger(row.`time_end:int`),
  `time_start_iso`: row.`time_start_iso`,
  `period`: row.`period`,
  `lat`: toFloat(row.`lat:float`),
  `lon`: toFloat(row.`lon:float`),
  `place_qid`: row.`place_qid`,
  `tgn_id`: row.`tgn_id`,
  `pleiades_id`: row.`pleiades_id`,
  `language_code`: row.`language_code`,
  `script`: row.`script`,
  `etymology`: row.`etymology`,
  `derived_from_csid`: row.`derived_from_csid`,
  `source`: row.`source`,
  `source_url`: row.`source_url`,
  `source_query`: row.`source_query`,
  `retrieved_at`: row.`retrieved_at`,
  `confidence`: toFloat(row.`confidence:float`),
  `license`: row.`license`
}
WITH n, row
CALL apoc.create.addLabels(n, split(row.`:LABEL`, ';')) YIELD node
RETURN count(node);

// node: nodes/Language.tsv
:param file => 'nodes/Language.tsv';
LOAD CSV WITH HEADERS FROM $file AS row FIELDTERMINATOR '\t'
MERGE (n:Entity {`csid`: row.`csid:ID`})
SET n += {
  `name`: row.`name`,
  `lang`: row.`lang`,
  `wikidata_qid`: row.`wikidata_qid`,
  `getty_id`: row.`getty_id`,
  `aliases`: split(row.`aliases`, ';'),
  `description`: row.`description`,
  `pinakes_id`: row.`pinakes_id`,
  `time_start`: toInteger(row.`time_start:int`),
  `time_end`: toInteger(row.`time_end:int`),
  `time_start_iso`: row.`time_start_iso`,
  `period`: row.`period`,
  `lat`: toFloat(row.`lat:float`),
  `lon`: toFloat(row.`lon:float`),
  `place_qid`: row.`place_qid`,
  `tgn_id`: row.`tgn_id`,
  `pleiades_id`: row.`pleiades_id`,
  `language_code`: row.`language_code`,
  `script`: row.`script`,
  `etymology`: row.`etymology`,
  `derived_from_csid`: row.`derived_from_csid`,
  `source`: row.`source`,
  `source_url`: row.`source_url`,
  `source_query`: row.`source_query`,
  `retrieved_at`: row.`retrieved_at`,
  `confidence`: toFloat(row.`confidence:float`),
  `license`: row.`license`
}
WITH n, row
CALL apoc.create.addLabels(n, split(row.`:LABEL`, ';')) YIELD node
RETURN count(node);

// node: nodes/Place.tsv
:param file => 'nodes/Place.tsv';
LOAD CSV WITH HEADERS FROM $file AS row FIELDTERMINATOR '\t'
MERGE (n:Entity {`csid`: row.`csid:ID`})
SET n += {
  `name`: row.`name`,
  `lang`: row.`lang`,
  `wikidata_qid`: row.`wikidata_qid`,
  `getty_id`: row.`getty_id`,
  `aliases`: split(row.`aliases`, ';'),
  `description`: row.`description`,
  `pinakes_id`: row.`pinakes_id`,
  `time_start`: toInteger(row.`time_start:int`),
  `time_end`: toInteger(row.`time_end:int`),
  `time_start_iso`: row.`time_start_iso`,
  `period`: row.`period`,
  `lat`: toFloat(row.`lat:float`),
  `lon`: toFloat(row.`lon:float`),
  `place_qid`: row.`place_qid`,
  `tgn_id`: row.`tgn_id`,
  `pleiades_id`: row.`pleiades_id`,
  `language_code`: row.`language_code`,
  `script`: row.`script`,
  `etymology`: row.`etymology`,
  `derived_from_csid`: row.`derived_from_csid`,
  `source`: row.`source`,
  `source_url`: row.`source_url`,
  `source_query`: row.`source_query`,
  `retrieved_at`: row.`retrieved_at`,
  `confidence`: toFloat(row.`confidence:float`),
  `license`: row.`license`
}
WITH n, row
CALL apoc.create.addLabels(n, split(row.`:LABEL`, ';')) YIELD node
RETURN count(node);

// edge: edges/DERIVED_FROM.tsv
:param file => 'edges/DERIVED_FROM.tsv';
LOAD CSV WITH HEADERS FROM $file AS row FIELDTERMINATOR '\t'
MATCH (start {csid: row.`:START_ID`})
MATCH (end {csid: row.`:END_ID`})
CALL apoc.merge.relationship(
  start, row.`:TYPE`, {}, {
  `weight`: toFloat(row.`weight:float`),
  `time_start`: toInteger(row.`time_start:int`),
  `time_end`: toInteger(row.`time_end:int`),
  `pinakes_id`: row.`pinakes_id`,
  `source`: row.`source`,
  `source_url`: row.`source_url`,
  `source_query`: row.`source_query`,
  `retrieved_at`: row.`retrieved_at`,
  `confidence`: toFloat(row.`confidence:float`),
  `license`: row.`license`
}, end, {
  `weight`: toFloat(row.`weight:float`),
  `time_start`: toInteger(row.`time_start:int`),
  `time_end`: toInteger(row.`time_end:int`),
  `pinakes_id`: row.`pinakes_id`,
  `source`: row.`source`,
  `source_url`: row.`source_url`,
  `source_query`: row.`source_query`,
  `retrieved_at`: row.`retrieved_at`,
  `confidence`: toFloat(row.`confidence:float`),
  `license`: row.`license`
}
) YIELD rel
RETURN count(rel);

// edge: edges/ORIGINATES_IN.tsv
:param file => 'edges/ORIGINATES_IN.tsv';
LOAD CSV WITH HEADERS FROM $file AS row FIELDTERMINATOR '\t'
MATCH (start {csid: row.`:START_ID`})
MATCH (end {csid: row.`:END_ID`})
CALL apoc.merge.relationship(
  start, row.`:TYPE`, {}, {
  `weight`: toFloat(row.`weight:float`),
  `time_start`: toInteger(row.`time_start:int`),
  `time_end`: toInteger(row.`time_end:int`),
  `pinakes_id`: row.`pinakes_id`,
  `source`: row.`source`,
  `source_url`: row.`source_url`,
  `source_query`: row.`source_query`,
  `retrieved_at`: row.`retrieved_at`,
  `confidence`: toFloat(row.`confidence:float`),
  `license`: row.`license`
}, end, {
  `weight`: toFloat(row.`weight:float`),
  `time_start`: toInteger(row.`time_start:int`),
  `time_end`: toInteger(row.`time_end:int`),
  `pinakes_id`: row.`pinakes_id`,
  `source`: row.`source`,
  `source_url`: row.`source_url`,
  `source_query`: row.`source_query`,
  `retrieved_at`: row.`retrieved_at`,
  `confidence`: toFloat(row.`confidence:float`),
  `license`: row.`license`
}
) YIELD rel
RETURN count(rel);
