"""The provenanced rules registry — the governance layer over every logic rule.

Facts already carry ``source``/``source_url``/``retrieved_at``/``confidence`` and
flow through a QA gate; rules did not. Three sources of rules had grown up
independently — the hand-written closures in :mod:`culturescrape.datalog.rules`
(``RULES``), the Wikidata P2302 property-constraint translations
(:mod:`culturescrape.datalog.constraints`, rules-layer US-002) and the canonical
schema's own from/to violation rules (:mod:`culturescrape.datalog.schema_constraints`,
rules-layer US-003) — each with its *own* draft registry TSV. This module (rules-layer
US-004) **wraps** all three into ONE provenanced registry with the same discipline
facts have: a rule id, the head/body clause text per dialect, source, source_url,
retrieved_at, confidence, version and a lifecycle status.

The registry is a **generated, committed artifact** (:data:`REGISTRY_TSV`), the
governance view of the whole rule corpus — the same "committed replay artifact"
pattern the taxonomy / constraint layers use. :func:`build_registry` aggregates the
three code sources deterministically; a test pins the committed TSV to it (regenerate
with ``culturescrape rules-registry --regenerate``). It carries:

* the curated closures (``source = curated``, ``version`` :data:`RULE_LIBRARY_VERSION`)
  — the hand-written rules migrated in, keeping their rich clauses; ``rules.py`` stays
  their clause source (its intent/example docstrings still drive the emitted programs'
  comment blocks), and this module wraps them with governance metadata;
* the Wikidata property-constraint rules (``source = wikidata``, ``version`` = the
  acquisition snapshot ``retrieved_at``);
* the canonical-schema violation rules (``source = canonical-schema``, ``version`` = the
  schema version).

**The QA gate.** :func:`validate_registry` checks the registry is *well-formed* —
every clause parses (balanced, a head and a body of ``pred(args)`` literals or
comparison guards), every predicate is *known* (a rule head, a declared dependency, or
a base projection predicate), and no predicate is used at two arities. A CI test runs
it over the committed registry (and the ``rules-registry`` CLI exposes it), so a
malformed or drifting rule fails the build the way a bad fact would.

**The lifecycle.** A rule's ``status`` moves ``proposed`` → ``active`` → ``retired``
(with ``redundant`` for a generated rule that duplicates a curated one — recorded but
not emitted). The exporter **consumes** the registry via :func:`active_curated_rules`:
a curated rule flipped to ``retired`` (or ``proposed``) in :data:`CURATED_RULE_META`
stops being attached to the program, without deleting its ``rules.py`` definition. The
constraint / schema layers already gate their own emission on ``status == "active"``;
this closes the same gate over the curated library. See ``docs/rules-registry.md``.
"""

from __future__ import annotations

import enum
import re
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path

from culturescrape.datalog.constraints import ConstraintRule, constraint_file_rules
from culturescrape.datalog.rules import RULES, Rule
from culturescrape.datalog.schema_constraints import (
    SchemaConstraintRule,
    schema_constraint_file_rules,
)
from culturescrape.schema.tsvio import encode_value, open_rows

#: The committed unified rules registry — the governance source of truth over every
#: rule (curated + property + schema). Generated by :func:`build_registry`, pinned by a
#: test, regenerated with ``culturescrape rules-registry --regenerate``.
REGISTRY_TSV = Path(__file__).resolve().parent / "rules_registry.tsv"

#: The semantic version of the hand-written closure library (bump when a curated
#: clause's *meaning* changes). It is every curated rule's registry ``version``.
RULE_LIBRARY_VERSION = "1.0.0"

#: Provenance of a curated (hand-written) rule.
CURATED_SOURCE = "curated"
CURATED_SOURCE_URL = "docs/datalog.md"

#: Governance layer tokens (the *generator* a rule came from), the registry ``layer``.
LAYER_CURATED = "curated"
LAYER_WIKIDATA_PROPERTY = "wikidata-property"
LAYER_CANONICAL_SCHEMA = "canonical-schema"

#: A generated Insimul world's own Prolog rules (insimul-bridge US-003, registry
#: entry 17). Unlike the three layers above, this one arrives as **data** — one
#: rule set per ingested ``CanonicalWorldExport`` — so it is deliberately NOT part
#: of :func:`build_registry` (which must stay a deterministic function of
#: code-resident sources, pinned byte-for-byte by a test). A world's entries are
#: built by :func:`culturescrape.acquire.insimul.world_rule_entries` and written
#: beside the corpus with :func:`write_registry`. They are always full-prolog:
#: ``clause_souffle`` is empty, so nothing here can leak into the Datalog programs.
LAYER_INSIMUL_WORLD = "insimul-world"

#: The registry columns, in order — the edge schema's provenance discipline applied to
#: rules. ``clause_prolog`` / ``clause_souffle`` hold the (space-joined) Horn clauses
#: for each dialect; a rule emitted to a single engine leaves the other blank, and a
#: dialect-neutral rule fills both identically. ``depends`` is the ``;``-joined base
#: predicates the body reads.
REGISTRY_COLUMNS: tuple[str, ...] = (
    "rule_id",
    "layer",
    "head",
    "clause_prolog",
    "clause_souffle",
    "depends",
    "source",
    "source_url",
    "retrieved_at",
    "confidence",
    "version",
    "status",
)

_DEPENDS_SEP = ";"


class RuleStatus(enum.Enum):
    """A rule's lifecycle position.

    ``PROPOSED`` — drafted, not yet attached to programs; ``ACTIVE`` — attached and
    emitted; ``RETIRED`` — withdrawn (kept for provenance, never emitted);
    ``REDUNDANT`` — a generated rule whose clause duplicates a curated one (recorded so
    the duplication is visible, but not emitted).
    """

    PROPOSED = "proposed"
    ACTIVE = "active"
    RETIRED = "retired"
    REDUNDANT = "redundant"


#: The status tokens a registry row may carry.
VALID_STATUSES: frozenset[str] = frozenset(s.value for s in RuleStatus)


class RegistryError(ValueError):
    """Raised when the rules registry is malformed or cannot be read."""


@dataclass(frozen=True)
class CuratedMeta:
    """Governance metadata for a curated rule (its clauses live in ``rules.py``).

    Kept in code (like ``RULES`` itself) so retiring a curated rule is a one-line
    edit here plus a registry regeneration — the rule's definition is never deleted.
    """

    source_url: str = CURATED_SOURCE_URL
    version: str = RULE_LIBRARY_VERSION
    status: str = RuleStatus.ACTIVE.value


#: Per-curated-rule governance overrides, keyed by the rule's head predicate. A rule
#: absent here takes :data:`_DEFAULT_CURATED_META` (active, current library version) —
#: so the default is "every curated rule is active". Flip an entry to
#: ``status=RuleStatus.RETIRED.value`` to withdraw a rule from the exported programs.
CURATED_RULE_META: dict[str, CuratedMeta] = {}

_DEFAULT_CURATED_META = CuratedMeta()


def curated_meta(name: str) -> CuratedMeta:
    """The governance metadata for the curated rule with head *name*."""
    return CURATED_RULE_META.get(name, _DEFAULT_CURATED_META)


@dataclass(frozen=True)
class RegistryEntry:
    """One rule's provenanced registry row (see :data:`REGISTRY_COLUMNS`)."""

    rule_id: str
    layer: str
    head: str
    clause_prolog: str
    clause_souffle: str
    depends: str
    source: str
    source_url: str
    retrieved_at: str
    confidence: float
    version: str
    status: str

    def to_row(self) -> dict[str, str]:
        """This entry as a registry TSV row (cells as strings)."""
        return {
            "rule_id": self.rule_id,
            "layer": self.layer,
            "head": self.head,
            "clause_prolog": self.clause_prolog,
            "clause_souffle": self.clause_souffle,
            "depends": self.depends,
            "source": self.source,
            "source_url": self.source_url,
            "retrieved_at": self.retrieved_at,
            "confidence": repr(float(self.confidence)),
            "version": self.version,
            "status": self.status,
        }


# --- aggregating the three rule sources -------------------------------------


def curated_entries(rules: tuple[Rule, ...] = RULES) -> tuple[RegistryEntry, ...]:
    """The curated closure library as provenanced registry entries.

    Each :class:`~culturescrape.datalog.rules.Rule` becomes one entry
    (``rule_id = "curated-<head>"``, ``source = curated``); its clauses are
    dialect-neutral, so ``clause_prolog`` and ``clause_souffle`` are the same joined
    text. Governance metadata (version, status, source_url) comes from
    :func:`curated_meta`.
    """
    entries: list[RegistryEntry] = []
    for rule in rules:
        meta = curated_meta(rule.name)
        clauses = " ".join(rule.clauses)
        entries.append(
            RegistryEntry(
                rule_id=f"curated-{rule.name}",
                layer=LAYER_CURATED,
                head=rule.name,
                clause_prolog=clauses,
                clause_souffle=clauses,
                depends=_DEPENDS_SEP.join(rule.depends),
                source=CURATED_SOURCE,
                source_url=meta.source_url,
                retrieved_at="",
                confidence=1.0,
                version=meta.version,
                status=meta.status,
            )
        )
    return tuple(entries)


def _property_entry(cr: ConstraintRule) -> RegistryEntry:
    return RegistryEntry(
        rule_id=cr.rule_id,
        layer=LAYER_WIKIDATA_PROPERTY,
        head=cr.head,
        clause_prolog=" ".join(cr.prolog_clauses),
        clause_souffle=" ".join(cr.souffle_clauses),
        depends=_DEPENDS_SEP.join(cr.depends),
        source=cr.source,
        source_url=cr.source_url,
        retrieved_at=cr.retrieved_at,
        confidence=cr.confidence,
        # An acquired axiom's "version" is the acquisition snapshot it was read at.
        version=cr.retrieved_at,
        status=cr.status,
    )


def property_entries() -> tuple[RegistryEntry, ...]:
    """The Wikidata property-constraint rules (US-002) as registry entries.

    Reads the committed replay artifact via
    :func:`~culturescrape.datalog.constraints.constraint_file_rules`; a missing
    artifact yields no entries. Every translated rule is included with its status
    (``active`` or ``redundant``), so the registry records the redundant-with-curated
    ones too.
    """
    translation = constraint_file_rules()
    return tuple(_property_entry(cr) for cr in translation.rules)


def _schema_entry(sr: SchemaConstraintRule) -> RegistryEntry:
    return RegistryEntry(
        rule_id=sr.rule_id,
        layer=LAYER_CANONICAL_SCHEMA,
        head=sr.head,
        clause_prolog="",  # schema rules are Soufflé-only (negation / inequality)
        clause_souffle=" ".join(sr.souffle_clauses),
        depends=_DEPENDS_SEP.join(sr.depends),
        source=sr.source,
        source_url=sr.source_url,
        retrieved_at="",
        confidence=sr.confidence,
        version=sr.schema_version,
        status=sr.status,
    )


def schema_entries() -> tuple[RegistryEntry, ...]:
    """The canonical-schema violation rules (US-003) as registry entries.

    Reads the committed schema edge-constraints artifact via
    :func:`~culturescrape.datalog.schema_constraints.schema_constraint_file_rules`; a
    missing artifact yields no entries.
    """
    return tuple(_schema_entry(sr) for sr in schema_constraint_file_rules())


def build_registry() -> tuple[RegistryEntry, ...]:
    """Aggregate every rule source into the unified registry, sorted by ``rule_id``.

    Deterministic and network-free (all three sources are committed artifacts or
    in-code constants), so the result is a stable, committable table.
    """
    entries = (
        list(curated_entries())
        + list(property_entries())
        + list(schema_entries())
    )
    return tuple(sorted(entries, key=lambda e: e.rule_id))


# --- serialising / reading the committed registry ---------------------------


def render_registry(entries: tuple[RegistryEntry, ...]) -> str:
    """Render *entries* as the registry TSV (header + rows), rows sorted by id."""
    ordered = sorted(entries, key=lambda e: e.rule_id)
    lines = ["\t".join(REGISTRY_COLUMNS)]
    for entry in ordered:
        cells = entry.to_row()
        lines.append("\t".join(encode_value(cells[c]) for c in REGISTRY_COLUMNS))
    return "\n".join(lines) + "\n"


def write_registry(
    entries: tuple[RegistryEntry, ...], path: str | Path = REGISTRY_TSV
) -> int:
    """Write *entries* to the registry TSV at *path*; return the row count."""
    out = Path(path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render_registry(entries), encoding="utf-8")
    return len(entries)


def _cell(row: dict[str, str | list[str]], key: str) -> str:
    value = row.get(key, "")
    if isinstance(value, list):
        raise RegistryError(f"column {key!r} is multi-valued, expected a scalar")
    return value


def load_registry(path: str | Path = REGISTRY_TSV) -> tuple[RegistryEntry, ...]:
    """Read the committed registry TSV at *path*.

    A missing file yields an empty tuple. Validates the header carries ``rule_id`` and
    parses ``confidence`` as a float.
    """
    file = Path(path)
    if not file.exists():
        return ()
    columns, rows = open_rows(file)
    names = {getattr(column, "name", "") for column in columns}
    if "rule_id" not in names:
        raise RegistryError(
            f"{file} is missing the 'rule_id' column "
            f"(have: {', '.join(sorted(names))})"
        )
    entries: list[RegistryEntry] = []
    for row in rows:
        confidence_cell = _cell(row, "confidence")
        try:
            confidence = float(confidence_cell) if confidence_cell else 1.0
        except ValueError as exc:
            raise RegistryError(
                f"registry row has a non-numeric confidence {confidence_cell!r}"
            ) from exc
        entries.append(
            RegistryEntry(
                rule_id=_cell(row, "rule_id"),
                layer=_cell(row, "layer"),
                head=_cell(row, "head"),
                clause_prolog=_cell(row, "clause_prolog"),
                clause_souffle=_cell(row, "clause_souffle"),
                depends=_cell(row, "depends"),
                source=_cell(row, "source"),
                source_url=_cell(row, "source_url"),
                retrieved_at=_cell(row, "retrieved_at"),
                confidence=confidence,
                version=_cell(row, "version"),
                status=_cell(row, "status"),
            )
        )
    return tuple(entries)


# --- the QA gate: well-formedness validation --------------------------------


@dataclass(frozen=True)
class RegistryProblem:
    """One well-formedness problem with a registry entry (empty list ⇒ clean)."""

    rule_id: str
    problem: str


#: Base projection predicates a rule body may always read (not rule heads): the entity
#: relation ``node`` and the two typing relations the closures/violations negate over.
_ALWAYS_KNOWN: frozenset[str] = frozenset({"node", "instance_of", "subclass_of"})

#: A ``pred(args)`` literal (predicate name + its parenthesised argument list).
_LITERAL_RE = re.compile(r"^([a-z][A-Za-z0-9_]*)\((.*)\)$")


def _split_top_level_commas(text: str) -> list[str]:
    """Split *text* on commas that are not inside parentheses."""
    parts: list[str] = []
    depth = 0
    current: list[str] = []
    for char in text:
        if char == "(":
            depth += 1
        elif char == ")":
            depth -= 1
        if char == "," and depth == 0:
            parts.append("".join(current))
            current = []
        else:
            current.append(char)
    parts.append("".join(current))
    return [p.strip() for p in parts]


def _split_clauses(cell: str) -> list[str]:
    """Split a registry clause cell into individual clauses (``.``-terminated).

    Registry clauses contain no ``.`` other than the terminator (variables, quoted
    ``:LABEL`` constants and csid variables carry none), so a plain split is safe.
    """
    return [clause.strip() for clause in cell.split(".") if clause.strip()]


def _literal_signature(literal: str) -> tuple[str, int] | None:
    """The ``(predicate, arity)`` of a body/head literal, or ``None`` for a comparison.

    Strips a leading Soufflé negation (``!``). A term with no parenthesised argument
    list (``Ex < Sy``, ``N != M``) is a comparison guard, not a predicate — ``None``.
    Raises :class:`RegistryError` on a malformed literal.
    """
    literal = literal.strip()
    if literal.startswith("!"):
        literal = literal[1:].strip()
    if "(" not in literal:
        return None  # a comparison / arithmetic guard, not a predicate goal
    match = _LITERAL_RE.match(literal)
    if not match:
        raise RegistryError(f"malformed literal {literal!r}")
    name, args = match.group(1), match.group(2).strip()
    arity = len(_split_top_level_commas(args)) if args else 0
    return name, arity


def _clause_signatures(clause: str) -> tuple[tuple[str, int], list[tuple[str, int]]]:
    """Parse *clause* into its head signature and its body predicate signatures.

    Comparison guards in the body are dropped (they carry no relation). Raises
    :class:`RegistryError` if the clause is unbalanced or a literal is malformed.
    """
    if clause.count("(") != clause.count(")"):
        raise RegistryError(f"unbalanced parentheses in clause {clause!r}")
    head_text, sep, body_text = clause.partition(":-")
    head_sig = _literal_signature(head_text.strip())
    if head_sig is None:
        raise RegistryError(f"clause head is not a predicate: {clause!r}")
    body_sigs: list[tuple[str, int]] = []
    if sep:
        for literal in _split_top_level_commas(body_text):
            if not literal:
                continue
            sig = _literal_signature(literal)
            if sig is not None:
                body_sigs.append(sig)
    return head_sig, body_sigs


def validate_registry(entries: tuple[RegistryEntry, ...]) -> list[RegistryProblem]:
    """Check the registry is well-formed; return the problems (empty ⇒ clean).

    The QA gate (rules-layer US-004). It verifies, over every entry:

    * **unique, non-empty rule ids** and a valid lifecycle ``status``;
    * **parseable clauses** — balanced, a head plus a body of ``pred(args)`` literals or
      comparison guards; a rule with no clause in either dialect is rejected;
    * **known predicates** — every body predicate is a rule head defined in the
      registry, a base projection predicate (``node``/``instance_of``/``subclass_of``),
      or one of the entry's own declared ``depends``; the head predicate matches the
      entry's ``head`` column;
    * **no arity conflicts** — no predicate appears at two different arities anywhere in
      the registry.
    """
    problems: list[RegistryProblem] = []
    from culturescrape.datalog.examples import KNOWN_PREDICATES

    heads = {e.head for e in entries}
    base_known = KNOWN_PREDICATES | _ALWAYS_KNOWN | heads
    arities: dict[str, int] = {}
    seen_ids: set[str] = set()

    for entry in entries:
        if not entry.rule_id:
            problems.append(RegistryProblem("", "blank rule_id"))
        elif entry.rule_id in seen_ids:
            problems.append(
                RegistryProblem(entry.rule_id, "duplicate rule_id")
            )
        seen_ids.add(entry.rule_id)

        if entry.status not in VALID_STATUSES:
            problems.append(
                RegistryProblem(
                    entry.rule_id,
                    f"invalid status {entry.status!r} "
                    f"(expected one of {', '.join(sorted(VALID_STATUSES))})",
                )
            )
        if not entry.head:
            problems.append(RegistryProblem(entry.rule_id, "blank head"))

        cells = [entry.clause_prolog, entry.clause_souffle]
        if not any(cell.strip() for cell in cells):
            problems.append(
                RegistryProblem(entry.rule_id, "rule has no clauses in either dialect")
            )

        allowed = base_known | set(
            d for d in entry.depends.split(_DEPENDS_SEP) if d
        )
        for cell in cells:
            for clause in _split_clauses(cell):
                try:
                    head_sig, body_sigs = _clause_signatures(clause)
                except RegistryError as exc:
                    problems.append(RegistryProblem(entry.rule_id, str(exc)))
                    continue
                if entry.head and head_sig[0] != entry.head:
                    problems.append(
                        RegistryProblem(
                            entry.rule_id,
                            f"clause head {head_sig[0]!r} does not match the "
                            f"registered head {entry.head!r}",
                        )
                    )
                for name, arity in [head_sig, *body_sigs]:
                    prev = arities.get(name)
                    if prev is not None and prev != arity:
                        problems.append(
                            RegistryProblem(
                                entry.rule_id,
                                f"predicate {name!r} used at arity {arity} and "
                                f"{prev} (arity conflict)",
                            )
                        )
                    else:
                        arities[name] = arity
                for name, _arity in body_sigs:
                    if name not in allowed:
                        problems.append(
                            RegistryProblem(
                                entry.rule_id,
                                f"unknown predicate {name!r} (not a rule head, base "
                                "relation, or declared dependency)",
                            )
                        )
    return problems


def assert_valid_registry(entries: tuple[RegistryEntry, ...]) -> None:
    """Raise :class:`RegistryError` if *entries* are not well-formed."""
    problems = validate_registry(entries)
    if problems:
        detail = "; ".join(f"{p.rule_id}: {p.problem}" for p in problems)
        raise RegistryError(f"{len(problems)} registry problem(s): {detail}")


# --- exporter consumption: the status gate ----------------------------------


def active_curated_rules(
    rules: tuple[Rule, ...] = RULES,
    *,
    status_of: Callable[[str], str] | None = None,
) -> tuple[Rule, ...]:
    """The curated rules the exporter should attach — those with status ``active``.

    The datalog exporter consumes the registry through this gate: a curated rule whose
    :data:`CURATED_RULE_META` status is not ``active`` (retired or still proposed) is
    dropped from the emitted program without deleting its ``rules.py`` definition. With
    the default (empty) overrides every curated rule is active, so the exported program
    is byte-for-byte unchanged. *status_of* overrides the status lookup (a callable
    ``name -> status``), used by tests to exercise retirement.
    """
    def default_status(name: str) -> str:
        return curated_meta(name).status

    lookup = status_of if status_of is not None else default_status
    return tuple(r for r in rules if lookup(r.name) == RuleStatus.ACTIVE.value)


__all__ = [
    "CURATED_RULE_META",
    "CURATED_SOURCE",
    "CURATED_SOURCE_URL",
    "LAYER_CANONICAL_SCHEMA",
    "LAYER_CURATED",
    "LAYER_WIKIDATA_PROPERTY",
    "REGISTRY_COLUMNS",
    "REGISTRY_TSV",
    "RULE_LIBRARY_VERSION",
    "VALID_STATUSES",
    "CuratedMeta",
    "RegistryEntry",
    "RegistryError",
    "RegistryProblem",
    "RuleStatus",
    "active_curated_rules",
    "assert_valid_registry",
    "build_registry",
    "curated_entries",
    "curated_meta",
    "load_registry",
    "property_entries",
    "render_registry",
    "schema_entries",
    "validate_registry",
    "write_registry",
]
