"""Generated Python bindings for the language-neutral `contracts/` sources.

@generated by scripts/gen-contract-bindings.ts — DO NOT EDIT.
Change a `contracts/*.json`, then run `npm run gen:contracts`.
"""

from __future__ import annotations

from pinakes_contracts import (
    canonical_schema,
    capability_manifest,
    confidence_rubric,
    lexicon_mapping,
    predicate_mapping,
)
from pinakes_contracts._documents import (
    CONTRACT_DOCUMENTS,
    CONTRACTS_DIR_ENV,
    ContractDocumentError,
    contract_path,
    contracts_dir,
    load_document,
)

__all__ = [
    "CONTRACTS_DIR_ENV",
    "CONTRACT_DOCUMENTS",
    "ContractDocumentError",
    "canonical_schema",
    "capability_manifest",
    "confidence_rubric",
    "contract_path",
    "contracts_dir",
    "lexicon_mapping",
    "load_document",
    "predicate_mapping",
]
