"""The canonical node/edge schema — the one data model pinakes_engine and the service share.

@generated by scripts/gen-contract-bindings.ts from ``contracts/canonical-schema.json`` — DO NOT EDIT.
Change the JSON, then run `npm run gen:contracts`. The drift gate fails a stale binding.
"""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from types import MappingProxyType
from typing import Final, Literal

#: A Neo4j-import property type; drives the header suffix.
ColumnType = Literal[
    "string",
    "int",
    "float",
]

#: What a column *is* in the canonical model.
ColumnRole = Literal[
    "id",
    "label",
    "core",
    "alias",
    "dimension",
    "provenance",
    "start_id",
    "end_id",
    "type",
]

#: A declared canonical node type ``name``.
NodeTypeName = Literal[
    "language",
    "language-family",
    "writing-system",
    "culture",
    "archaeological-culture",
    "urheimat-hypothesis",
    "religion",
    "deity",
    "myth-motif",
    "art-tradition",
    "literary-tradition",
    "cuisine",
    "ingredient",
    "trade-good",
    "battle",
    "place",
    "migration-route",
    "asset",
    "character",
    "building",
    "business",
]

#: A declared node ``:LABEL``.
NodeLabel = Literal[
    "Language",
    "LanguageFamily",
    "WritingSystem",
    "Culture",
    "ArchaeologicalCulture",
    "UrheimatHypothesis",
    "Religion",
    "Deity",
    "MythMotif",
    "ArtTradition",
    "LiteraryTradition",
    "Cuisine",
    "Ingredient",
    "TradeGood",
    "Battle",
    "Place",
    "MigrationRoute",
    "Asset",
    "Character",
    "Building",
    "Business",
]

#: A declared canonical edge type ``name``.
EdgeTypeName = Literal[
    "descended-from",
    "split-from",
    "merged-with",
    "influenced-by",
    "conquered-by",
    "absorbed-into",
    "spoken-in",
    "located-in",
    "contemporary-with",
    "part-of-period",
    "borrowed-from",
    "cognate-with",
    "derived-from",
    "syncretized-with",
    "depicts",
    "mentions",
    "parent-of",
    "spouse-of",
    "employed-by",
    "resides-in",
    "caused-by",
]

#: A declared edge ``:TYPE`` token.
EdgeTypeToken = Literal[
    "DESCENDS_FROM",
    "SPLIT_FROM",
    "MERGED_WITH",
    "INFLUENCED_BY",
    "CONQUERED_BY",
    "ABSORBED_INTO",
    "SPOKEN_IN",
    "LOCATED_IN",
    "CONTEMPORARY_WITH",
    "PART_OF_PERIOD",
    "BORROWED_FROM",
    "COGNATE_WITH",
    "DERIVED_FROM",
    "SYNCRETIZED_WITH",
    "DEPICTS",
    "MENTIONS",
    "PARENT_OF",
    "SPOUSE_OF",
    "EMPLOYED_BY",
    "RESIDES_IN",
    "CAUSED_BY",
]

@dataclass(frozen=True)
class CanonicalColumn:
    """One column of a node or edge header row."""

    #: Canonical field name (property name, or a structural token e.g. ``:LABEL``).
    field: str
    #: The exact TSV header cell, including any Neo4j type suffix.
    header: str
    type: ColumnType
    role: ColumnRole
    #: Whether every exported file of this family must carry the column.
    required: bool

@dataclass(frozen=True)
class CanonicalNodeType:
    """A canonical node type and its Neo4j ``:LABEL``."""

    name: str
    label: str
    description: str

@dataclass(frozen=True)
class CanonicalEdgeType:
    """A canonical edge type and its Neo4j ``:TYPE`` token.

    ``from``/``to`` are Python keywords, so the endpoint constraints are
    ``from_types``/``to_types`` here. An empty tuple means unconstrained.
    """

    name: str
    type: str
    description: str
    from_types: tuple[str, ...]
    to_types: tuple[str, ...]

#: The schema ``version`` these bindings were generated from.
VERSION: Final = "1.3.0"

#: The canonical TSV column delimiter.
DELIMITER: Final = "\t"

#: The node header columns, in schema order.
NODE_COLUMNS: Final[tuple[CanonicalColumn, ...]] = (
    CanonicalColumn(field="csid", header="csid:ID", type="string", role="id", required=True),
    CanonicalColumn(field=":LABEL", header=":LABEL", type="string", role="label", required=True),
    CanonicalColumn(field="name", header="name", type="string", role="core", required=True),
    CanonicalColumn(field="lang", header="lang", type="string", role="core", required=False),
    CanonicalColumn(field="wikidata_qid", header="wikidata_qid", type="string", role="core", required=False),
    CanonicalColumn(field="getty_id", header="getty_id", type="string", role="core", required=False),
    CanonicalColumn(field="aliases", header="aliases", type="string", role="core", required=False),
    CanonicalColumn(field="description", header="description", type="string", role="core", required=False),
    CanonicalColumn(field="pinakes_id", header="pinakes_id", type="string", role="alias", required=False),
    CanonicalColumn(field="time_start", header="time_start:int", type="int", role="dimension", required=False),
    CanonicalColumn(field="time_end", header="time_end:int", type="int", role="dimension", required=False),
    CanonicalColumn(field="time_start_iso", header="time_start_iso", type="string", role="dimension", required=False),
    CanonicalColumn(field="period", header="period", type="string", role="dimension", required=False),
    CanonicalColumn(field="lat", header="lat:float", type="float", role="dimension", required=False),
    CanonicalColumn(field="lon", header="lon:float", type="float", role="dimension", required=False),
    CanonicalColumn(field="place_qid", header="place_qid", type="string", role="dimension", required=False),
    CanonicalColumn(field="tgn_id", header="tgn_id", type="string", role="dimension", required=False),
    CanonicalColumn(field="pleiades_id", header="pleiades_id", type="string", role="dimension", required=False),
    CanonicalColumn(field="language_code", header="language_code", type="string", role="dimension", required=False),
    CanonicalColumn(field="script", header="script", type="string", role="dimension", required=False),
    CanonicalColumn(field="etymology", header="etymology", type="string", role="dimension", required=False),
    CanonicalColumn(field="derived_from_csid", header="derived_from_csid", type="string", role="dimension", required=False),
    CanonicalColumn(field="source", header="source", type="string", role="provenance", required=True),
    CanonicalColumn(field="source_url", header="source_url", type="string", role="provenance", required=True),
    CanonicalColumn(field="source_query", header="source_query", type="string", role="provenance", required=False),
    CanonicalColumn(field="retrieved_at", header="retrieved_at", type="string", role="provenance", required=True),
    CanonicalColumn(field="confidence", header="confidence:float", type="float", role="provenance", required=True),
    CanonicalColumn(field="license", header="license", type="string", role="provenance", required=True),
)

#: The edge header columns, in schema order.
EDGE_COLUMNS: Final[tuple[CanonicalColumn, ...]] = (
    CanonicalColumn(field=":START_ID", header=":START_ID", type="string", role="start_id", required=True),
    CanonicalColumn(field=":END_ID", header=":END_ID", type="string", role="end_id", required=True),
    CanonicalColumn(field=":TYPE", header=":TYPE", type="string", role="type", required=True),
    CanonicalColumn(field="weight", header="weight:float", type="float", role="dimension", required=False),
    CanonicalColumn(field="time_start", header="time_start:int", type="int", role="dimension", required=False),
    CanonicalColumn(field="time_end", header="time_end:int", type="int", role="dimension", required=False),
    CanonicalColumn(field="pinakes_id", header="pinakes_id", type="string", role="alias", required=False),
    CanonicalColumn(field="source", header="source", type="string", role="provenance", required=True),
    CanonicalColumn(field="source_url", header="source_url", type="string", role="provenance", required=True),
    CanonicalColumn(field="source_query", header="source_query", type="string", role="provenance", required=False),
    CanonicalColumn(field="retrieved_at", header="retrieved_at", type="string", role="provenance", required=True),
    CanonicalColumn(field="confidence", header="confidence:float", type="float", role="provenance", required=True),
    CanonicalColumn(field="license", header="license", type="string", role="provenance", required=True),
)

#: Provenance fields required on every node row.
NODE_PROVENANCE_COLUMNS: Final[tuple[str, ...]] = (
    "source",
    "source_url",
    "retrieved_at",
    "confidence",
    "license",
)

#: Provenance fields required on every edge row.
EDGE_PROVENANCE_COLUMNS: Final[tuple[str, ...]] = (
    "source",
    "source_url",
    "retrieved_at",
    "confidence",
    "license",
)

#: Every declared node type, in schema order.
NODE_TYPES: Final[tuple[CanonicalNodeType, ...]] = (
    CanonicalNodeType(name="language", label="Language", description="A natural language or genealogical language node."),
    CanonicalNodeType(name="language-family", label="LanguageFamily", description="A language family / stock / branch grouping."),
    CanonicalNodeType(name="writing-system", label="WritingSystem", description="A script or writing system (ISO 15924)."),
    CanonicalNodeType(name="culture", label="Culture", description="A living or historical culture / civilization."),
    CanonicalNodeType(name="archaeological-culture", label="ArchaeologicalCulture", description="A material-culture horizon attested archaeologically."),
    CanonicalNodeType(name="urheimat-hypothesis", label="UrheimatHypothesis", description="A proposed homeland hypothesis for a language family."),
    CanonicalNodeType(name="religion", label="Religion", description="A religion or religious tradition."),
    CanonicalNodeType(name="deity", label="Deity", description="A god, goddess, or divine figure."),
    CanonicalNodeType(name="myth-motif", label="MythMotif", description="A recurring narrative motif in myth."),
    CanonicalNodeType(name="art-tradition", label="ArtTradition", description="An artistic tradition or style lineage."),
    CanonicalNodeType(name="literary-tradition", label="LiteraryTradition", description="A literary tradition or corpus."),
    CanonicalNodeType(name="cuisine", label="Cuisine", description="A regional or cultural cuisine."),
    CanonicalNodeType(name="ingredient", label="Ingredient", description="A food ingredient or foodstuff."),
    CanonicalNodeType(name="trade-good", label="TradeGood", description="A commodity moved along trade networks."),
    CanonicalNodeType(name="battle", label="Battle", description="A military engagement or conflict event."),
    CanonicalNodeType(name="place", label="Place", description="A geographic place, settlement, or site."),
    CanonicalNodeType(name="migration-route", label="MigrationRoute", description="A route of human or cultural migration."),
    CanonicalNodeType(name="asset", label="Asset", description="A content-addressed media asset (csid local part = sha256 of the file bytes), ingested from a media-analysis producer's to_canonical projection. A personal-tier file node carrying technical properties (container/duration/codec/width/height, in overflow); the sha256: id-space of the predicate-mapping registry (v1.2 addition)."),
    CanonicalNodeType(name="character", label="Character", description="A person in a generated Insimul world (person/1 — first/last name, gender, birth year, occupation, alive flag). The canonical vocabulary's first person-family type; synthetic trust tier, world-scoped provenance (v1.3 addition, insimul-bridge US-003)."),
    CanonicalNodeType(name="building", label="Building", description="A built structure on a settlement lot in a generated Insimul world (lot/1, lot_building/2 — building type, address, occupants). Synthetic trust tier (v1.3 addition, insimul-bridge US-003)."),
    CanonicalNodeType(name="business", label="Business", description="A commercial establishment in a generated Insimul world (business/1, business_type/2 — owner, founder, founding year). Synthetic trust tier (v1.3 addition, insimul-bridge US-003)."),
)

#: Every declared edge type, in schema order.
EDGE_TYPES: Final[tuple[CanonicalEdgeType, ...]] = (
    CanonicalEdgeType(name="descended-from", type="DESCENDS_FROM", description="Genealogical descent (language→ancestor, culture→predecessor). Uses pinakes-engine's existing DESCENDS_FROM token.", from_types=("language", "language-family", "culture", "archaeological-culture",), to_types=("language", "language-family", "culture", "archaeological-culture",)),
    CanonicalEdgeType(name="split-from", type="SPLIT_FROM", description="Diverged from a common ancestor.", from_types=("language", "language-family", "culture",), to_types=("language", "language-family", "culture",)),
    CanonicalEdgeType(name="merged-with", type="MERGED_WITH", description="Merged with another lineage.", from_types=("culture", "language", "language-family",), to_types=("culture", "language", "language-family",)),
    CanonicalEdgeType(name="influenced-by", type="INFLUENCED_BY", description="Received influence from another entity.", from_types=(), to_types=()),
    CanonicalEdgeType(name="conquered-by", type="CONQUERED_BY", description="Militarily conquered by another polity.", from_types=("culture", "place",), to_types=("culture", "battle",)),
    CanonicalEdgeType(name="absorbed-into", type="ABSORBED_INTO", description="Absorbed into a successor culture/polity.", from_types=("culture", "archaeological-culture",), to_types=("culture", "archaeological-culture",)),
    CanonicalEdgeType(name="spoken-in", type="SPOKEN_IN", description="A language is spoken in a place.", from_types=("language",), to_types=("place",)),
    CanonicalEdgeType(name="located-in", type="LOCATED_IN", description="An entity is located within a place.", from_types=(), to_types=("place",)),
    CanonicalEdgeType(name="contemporary-with", type="CONTEMPORARY_WITH", description="Overlapping time spans.", from_types=(), to_types=()),
    CanonicalEdgeType(name="part-of-period", type="PART_OF_PERIOD", description="Falls within a named period.", from_types=(), to_types=()),
    CanonicalEdgeType(name="borrowed-from", type="BORROWED_FROM", description="A term/word borrowed from a source language.", from_types=("language",), to_types=("language",)),
    CanonicalEdgeType(name="cognate-with", type="COGNATE_WITH", description="Terms sharing a common ancestral form.", from_types=("language",), to_types=("language",)),
    CanonicalEdgeType(name="derived-from", type="DERIVED_FROM", description="A cultural artifact/style/dish derived from an ancestor.", from_types=(), to_types=()),
    CanonicalEdgeType(name="syncretized-with", type="SYNCRETIZED_WITH", description="Religious/deity syncretism between traditions.", from_types=("religion", "deity",), to_types=("religion", "deity",)),
    CanonicalEdgeType(name="depicts", type="DEPICTS", description="An asset visually depicts an entity (a media-analysis producer's vision caption / detected object; the object may carry an entity_ref csid once grounded). Personal tier (v1.2 addition).", from_types=("asset",), to_types=()),
    CanonicalEdgeType(name="mentions", type="MENTIONS", description="An asset textually mentions an entity (a media-analysis producer's transcript / text ingest). Personal tier (v1.2 addition).", from_types=("asset",), to_types=()),
    CanonicalEdgeType(name="parent-of", type="PARENT_OF", description="Genealogical parenthood, canonical order (parent, child) — Insimul parent_of/2 (childIds); child_of/2 is the same relation with the arguments swapped, never a second edge. Synthetic tier (v1.3 addition, insimul-bridge US-003).", from_types=("character",), to_types=("character",)),
    CanonicalEdgeType(name="spouse-of", type="SPOUSE_OF", description="Marriage, symmetric — Insimul married_to/2 (spouseId); the two stored directions collapse to one edge with sorted endpoints. Synthetic tier (v1.3 addition, insimul-bridge US-003).", from_types=("character",), to_types=("character",)),
    CanonicalEdgeType(name="employed-by", type="EMPLOYED_BY", description="A character works for a business — Insimul business_owner/2 / business_founder/2. Synthetic tier (v1.3 addition, insimul-bridge US-003).", from_types=("character",), to_types=("business",)),
    CanonicalEdgeType(name="resides-in", type="RESIDES_IN", description="A character dwells in a building — Insimul residence_resident/2 / residence_owner/2. Occupancy, distinct from located-in (positional containment). Synthetic tier (v1.3 addition, insimul-bridge US-003).", from_types=("character",), to_types=("building",)),
    CanonicalEdgeType(name="caused-by", type="CAUSED_BY", description="Event causality, canonical order (effect, cause) — Insimul truths' causesTruthIds/causedByTruthIds chains. Synthetic tier (v1.3 addition, insimul-bridge US-003).", from_types=(), to_types=()),
)

#: Every node type ``name``, in schema order.
NODE_TYPE_NAMES: Final[tuple[str, ...]] = (
    "language",
    "language-family",
    "writing-system",
    "culture",
    "archaeological-culture",
    "urheimat-hypothesis",
    "religion",
    "deity",
    "myth-motif",
    "art-tradition",
    "literary-tradition",
    "cuisine",
    "ingredient",
    "trade-good",
    "battle",
    "place",
    "migration-route",
    "asset",
    "character",
    "building",
    "business",
)

#: Every node ``:LABEL``, in schema order.
NODE_LABELS: Final[tuple[str, ...]] = (
    "Language",
    "LanguageFamily",
    "WritingSystem",
    "Culture",
    "ArchaeologicalCulture",
    "UrheimatHypothesis",
    "Religion",
    "Deity",
    "MythMotif",
    "ArtTradition",
    "LiteraryTradition",
    "Cuisine",
    "Ingredient",
    "TradeGood",
    "Battle",
    "Place",
    "MigrationRoute",
    "Asset",
    "Character",
    "Building",
    "Business",
)

#: Every edge type ``name``, in schema order.
EDGE_TYPE_NAMES: Final[tuple[str, ...]] = (
    "descended-from",
    "split-from",
    "merged-with",
    "influenced-by",
    "conquered-by",
    "absorbed-into",
    "spoken-in",
    "located-in",
    "contemporary-with",
    "part-of-period",
    "borrowed-from",
    "cognate-with",
    "derived-from",
    "syncretized-with",
    "depicts",
    "mentions",
    "parent-of",
    "spouse-of",
    "employed-by",
    "resides-in",
    "caused-by",
)

#: Every edge ``:TYPE`` token, in schema order.
EDGE_TYPE_TOKENS: Final[tuple[str, ...]] = (
    "DESCENDS_FROM",
    "SPLIT_FROM",
    "MERGED_WITH",
    "INFLUENCED_BY",
    "CONQUERED_BY",
    "ABSORBED_INTO",
    "SPOKEN_IN",
    "LOCATED_IN",
    "CONTEMPORARY_WITH",
    "PART_OF_PERIOD",
    "BORROWED_FROM",
    "COGNATE_WITH",
    "DERIVED_FROM",
    "SYNCRETIZED_WITH",
    "DEPICTS",
    "MENTIONS",
    "PARENT_OF",
    "SPOUSE_OF",
    "EMPLOYED_BY",
    "RESIDES_IN",
    "CAUSED_BY",
)

#: Node type ``name`` -> its Neo4j ``:LABEL``.
LABEL_BY_NODE_TYPE: Final[Mapping[str, str]] = MappingProxyType(
    {
        "language": "Language",
        "language-family": "LanguageFamily",
        "writing-system": "WritingSystem",
        "culture": "Culture",
        "archaeological-culture": "ArchaeologicalCulture",
        "urheimat-hypothesis": "UrheimatHypothesis",
        "religion": "Religion",
        "deity": "Deity",
        "myth-motif": "MythMotif",
        "art-tradition": "ArtTradition",
        "literary-tradition": "LiteraryTradition",
        "cuisine": "Cuisine",
        "ingredient": "Ingredient",
        "trade-good": "TradeGood",
        "battle": "Battle",
        "place": "Place",
        "migration-route": "MigrationRoute",
        "asset": "Asset",
        "character": "Character",
        "building": "Building",
        "business": "Business",
    }
)

#: Edge type ``name`` -> its Neo4j ``:TYPE`` token.
TOKEN_BY_EDGE_TYPE: Final[Mapping[str, str]] = MappingProxyType(
    {
        "descended-from": "DESCENDS_FROM",
        "split-from": "SPLIT_FROM",
        "merged-with": "MERGED_WITH",
        "influenced-by": "INFLUENCED_BY",
        "conquered-by": "CONQUERED_BY",
        "absorbed-into": "ABSORBED_INTO",
        "spoken-in": "SPOKEN_IN",
        "located-in": "LOCATED_IN",
        "contemporary-with": "CONTEMPORARY_WITH",
        "part-of-period": "PART_OF_PERIOD",
        "borrowed-from": "BORROWED_FROM",
        "cognate-with": "COGNATE_WITH",
        "derived-from": "DERIVED_FROM",
        "syncretized-with": "SYNCRETIZED_WITH",
        "depicts": "DEPICTS",
        "mentions": "MENTIONS",
        "parent-of": "PARENT_OF",
        "spouse-of": "SPOUSE_OF",
        "employed-by": "EMPLOYED_BY",
        "resides-in": "RESIDES_IN",
        "caused-by": "CAUSED_BY",
    }
)

#: The ordered node header row (``csid:ID<TAB>:LABEL<TAB>...``).
NODE_HEADER_ROW: Final = "csid:ID\t:LABEL\tname\tlang\twikidata_qid\tgetty_id\taliases\tdescription\tpinakes_id\ttime_start:int\ttime_end:int\ttime_start_iso\tperiod\tlat:float\tlon:float\tplace_qid\ttgn_id\tpleiades_id\tlanguage_code\tscript\tetymology\tderived_from_csid\tsource\tsource_url\tsource_query\tretrieved_at\tconfidence:float\tlicense"

#: The ordered edge header row (``:START_ID<TAB>:END_ID<TAB>:TYPE<TAB>...``).
EDGE_HEADER_ROW: Final = ":START_ID\t:END_ID\t:TYPE\tweight:float\ttime_start:int\ttime_end:int\tpinakes_id\tsource\tsource_url\tsource_query\tretrieved_at\tconfidence:float\tlicense"

_NODE_TYPE_BY_NAME: Final[Mapping[str, CanonicalNodeType]] = MappingProxyType(
    {node_type.name: node_type for node_type in NODE_TYPES}
)
_EDGE_TYPE_BY_NAME: Final[Mapping[str, CanonicalEdgeType]] = MappingProxyType(
    {edge_type.name: edge_type for edge_type in EDGE_TYPES}
)
_EDGE_TYPE_BY_TOKEN: Final[Mapping[str, CanonicalEdgeType]] = MappingProxyType(
    {edge_type.type: edge_type for edge_type in EDGE_TYPES}
)


def node_type_by_name(name: str) -> CanonicalNodeType | None:
    """The node type declared under *name*, or ``None``."""
    return _NODE_TYPE_BY_NAME.get(name)


def edge_type_by_name(name: str) -> CanonicalEdgeType | None:
    """The edge type declared under *name*, or ``None``."""
    return _EDGE_TYPE_BY_NAME.get(name)


def edge_type_by_token(token: str) -> CanonicalEdgeType | None:
    """The edge type whose Neo4j ``:TYPE`` token is *token*, or ``None``."""
    return _EDGE_TYPE_BY_TOKEN.get(token)
