"""The Koine capability-bus manifest Pinakes publishes.

@generated by scripts/gen-contract-bindings.ts from ``contracts/capability-manifest.json`` — DO NOT EDIT.
Change the JSON, then run `npm run gen:contracts`. The drift gate fails a stale binding.
"""

from __future__ import annotations

from typing import Any, Final, Literal

from pinakes_contracts._documents import load_document

#: A capability the manifest advertises.
CapabilityName = Literal[
    "resolve",
    "reconcile",
    "query",
    "finetune",
]

#: The ``kcb_version`` the manifest declares.
KCB_VERSION: Final = "0.2.0"

#: The authority provider identity Pinakes publishes under.
PROVIDER_IDENTITY: Final = "pinakes:agent:resolver"

#: Every advertised capability, in manifest order.
CAPABILITY_NAMES: Final[tuple[str, ...]] = (
    "resolve",
    "reconcile",
    "query",
    "finetune",
)


#: The neutral source document these bindings were generated from.
DOCUMENT_NAME: Final = "capability-manifest.json"

def document() -> dict[str, Any]:
    """The whole parsed source document.

    Read from ``contracts/`` at call time (see
    :func:`pinakes_contracts.contract_path`) — the constants above are embedded,
    the document is not, so this needs the repo checkout.
    """
    return load_document(DOCUMENT_NAME)
