"""The lexicon -> canonical mapping: which source TSV becomes which canonical family.

@generated by scripts/gen-contract-bindings.ts from ``contracts/lexicon-mapping.json`` — DO NOT EDIT.
Change the JSON, then run `npm run gen:contracts`. The drift gate fails a stale binding.
"""

from __future__ import annotations

from typing import Any, Final, Literal

from pinakes_contracts._documents import load_document

#: A mapped ``data/source/lexicons/*.tsv`` file.
LexiconFileName = Literal[
    "archaeological-cultures.tsv",
    "archaeological-sites.tsv",
    "architectural-styles.tsv",
    "art-style-evolutions.tsv",
    "art-traditions.tsv",
    "battles.tsv",
    "building-types.tsv",
    "city-layouts.tsv",
    "civilization-boundaries.tsv",
    "civilizations.tsv",
    "cooking-techniques.tsv",
    "cuisine-items.tsv",
    "cuisines.tsv",
    "cultural-lineages.tsv",
    "culture-events.tsv",
    "culture-profiles.tsv",
    "daily-life.tsv",
    "dance-traditions.tsv",
    "deities.tsv",
    "empires-timeline.tsv",
    "etymology-relations.tsv",
    "families.tsv",
    "foodway-events.tsv",
    "genai-prompts.tsv",
    "grammar-features.tsv",
    "haplogroups.tsv",
    "ingredient-origins.tsv",
    "innovations.tsv",
    "kinship-systems.tsv",
    "language-contacts.tsv",
    "language-range-polygons.tsv",
    "language-ranges.tsv",
    "languages.tsv",
    "literary-traditions.tsv",
    "literary-works.tsv",
    "material-culture.tsv",
    "media-assets.tsv",
    "migration-routes.tsv",
    "music-traditions.tsv",
    "musical-instruments.tsv",
    "myth-motifs.tsv",
    "narratives.tsv",
    "phonological-inventories.tsv",
    "religions.tsv",
    "rivers-and-waters.tsv",
    "sample-texts.tsv",
    "settlements.tsv",
    "social-organization.tsv",
    "social-structures.tsv",
    "sound-changes.tsv",
    "trade-goods.tsv",
    "trade-routes.tsv",
    "urheimat-hypotheses.tsv",
    "verb-paradigms.tsv",
    "words.tsv",
    "words-base.tsv",
    "writing-systems.tsv",
]

#: The mapping ``version`` these bindings were generated from.
VERSION: Final = "1.0.0"

#: Every mapped lexicon file, in mapping order.
LEXICON_FILES: Final[tuple[str, ...]] = (
    "archaeological-cultures.tsv",
    "archaeological-sites.tsv",
    "architectural-styles.tsv",
    "art-style-evolutions.tsv",
    "art-traditions.tsv",
    "battles.tsv",
    "building-types.tsv",
    "city-layouts.tsv",
    "civilization-boundaries.tsv",
    "civilizations.tsv",
    "cooking-techniques.tsv",
    "cuisine-items.tsv",
    "cuisines.tsv",
    "cultural-lineages.tsv",
    "culture-events.tsv",
    "culture-profiles.tsv",
    "daily-life.tsv",
    "dance-traditions.tsv",
    "deities.tsv",
    "empires-timeline.tsv",
    "etymology-relations.tsv",
    "families.tsv",
    "foodway-events.tsv",
    "genai-prompts.tsv",
    "grammar-features.tsv",
    "haplogroups.tsv",
    "ingredient-origins.tsv",
    "innovations.tsv",
    "kinship-systems.tsv",
    "language-contacts.tsv",
    "language-range-polygons.tsv",
    "language-ranges.tsv",
    "languages.tsv",
    "literary-traditions.tsv",
    "literary-works.tsv",
    "material-culture.tsv",
    "media-assets.tsv",
    "migration-routes.tsv",
    "music-traditions.tsv",
    "musical-instruments.tsv",
    "myth-motifs.tsv",
    "narratives.tsv",
    "phonological-inventories.tsv",
    "religions.tsv",
    "rivers-and-waters.tsv",
    "sample-texts.tsv",
    "settlements.tsv",
    "social-organization.tsv",
    "social-structures.tsv",
    "sound-changes.tsv",
    "trade-goods.tsv",
    "trade-routes.tsv",
    "urheimat-hypotheses.tsv",
    "verb-paradigms.tsv",
    "words.tsv",
    "words-base.tsv",
    "writing-systems.tsv",
)

#: Lexicon files that project canonical nodes.
NODE_FILES: Final[tuple[str, ...]] = (
    "archaeological-cultures.tsv",
    "archaeological-sites.tsv",
    "architectural-styles.tsv",
    "art-traditions.tsv",
    "battles.tsv",
    "civilizations.tsv",
    "cuisine-items.tsv",
    "cuisines.tsv",
    "culture-profiles.tsv",
    "dance-traditions.tsv",
    "deities.tsv",
    "families.tsv",
    "ingredient-origins.tsv",
    "languages.tsv",
    "literary-traditions.tsv",
    "migration-routes.tsv",
    "music-traditions.tsv",
    "myth-motifs.tsv",
    "religions.tsv",
    "rivers-and-waters.tsv",
    "settlements.tsv",
    "trade-goods.tsv",
    "urheimat-hypotheses.tsv",
    "writing-systems.tsv",
)

#: Lexicon files that project canonical edges.
EDGE_FILES: Final[tuple[str, ...]] = (
    "art-style-evolutions.tsv",
    "cultural-lineages.tsv",
    "etymology-relations.tsv",
    "language-contacts.tsv",
)


#: The neutral source document these bindings were generated from.
DOCUMENT_NAME: Final = "lexicon-mapping.json"

def document() -> dict[str, Any]:
    """The whole parsed source document.

    Read from ``contracts/`` at call time (see
    :func:`pinakes_contracts.contract_path`) — the constants above are embedded,
    the document is not, so this needs the repo checkout.
    """
    return load_document(DOCUMENT_NAME)
