"""The vendored koine predicate registry. The JSON is a MIRROR of koine's authoritative copy -- re-vendor it with ``npm run regen:registry-mirror``, never hand-edit.

@generated by scripts/gen-contract-bindings.ts from ``contracts/predicate-mapping.json`` — DO NOT EDIT.
Change the JSON, then run `npm run gen:contracts`. The drift gate fails a stale binding.
"""

from __future__ import annotations

from typing import Any, Final, Literal

from pinakes_contracts._documents import load_document

#: A project the registry bridges.
ProjectName = Literal[
    "analyzer",
    "insimul",
]

#: The koine ``registryVersion`` the vendored mirror is at.
REGISTRY_VERSION: Final = "0.4.2"

#: Every bridged project, in registry order.
PROJECTS: Final[tuple[str, ...]] = (
    "analyzer",
    "insimul",
)


#: The neutral source document these bindings were generated from.
DOCUMENT_NAME: Final = "predicate-mapping.json"

def document() -> dict[str, Any]:
    """The whole parsed source document.

    Read from ``contracts/`` at call time (see
    :func:`pinakes_contracts.contract_path`) — the constants above are embedded,
    the document is not, so this needs the repo checkout.
    """
    return load_document(DOCUMENT_NAME)
