/**
 * Corpus trust-tier report (US-004): breaks the curated corpus down by trust
 * tier and tracks **auto-admission readiness** over time — how much of the
 * human-curated lexicon corpus is independently QID-anchored + reference-backed
 * (and would auto-admit to the shared graph on its own merits).
 *
 * Every pinakes lexicon row is human-curated, so in the shared graph the
 * whole app corpus is the `curated` tier (auto-admission never writes
 * `data/source/lexicons/*.tsv`). The readiness breakdown is the growth metric: as US-003's
 * QID backfill converges the corpus with the global identity space, the
 * auto-admitted share rises.
 *
 * Emits two committed artifacts so the composition is diffable + reviewable:
 *   - docs/corpus-tier-report.json  (deterministic; asserted against the live corpus by a test)
 *   - docs/corpus-tier-report.md    (human-readable table)
 *
 * The classification + aggregation live in the shared data-quality-scorer service
 * (scripts/lib/data-quality-scorer.ts) so `/api/data-quality` — now served by the
 * Python `analytics/quality.py` — and this report stay one statement about the corpus. Run after any data change that moves a node lexicon's
 * QID/source_url coverage:
 *   npx tsx scripts/corpus-tier-report.ts
 */
import fs from "node:fs";
import path from "node:path";
import {
  buildCorpusTierReport,
  type CorpusTierReport,
} from "./lib/data-quality-scorer";
import { trustTierMeta } from "@contracts/trust-tier";

const REPO_ROOT = path.resolve(import.meta.dirname, "..");
const LEXICONS_DIR = path.join(REPO_ROOT, "data", "source", "lexicons");
const JSON_OUT = path.join(REPO_ROOT, "docs", "corpus-tier-report.json");
const MD_OUT = path.join(REPO_ROOT, "docs", "corpus-tier-report.md");

/** Pure: renders the tier report as a Markdown document (deterministic). */
export function renderMarkdown(report: CorpusTierReport): string {
  const lines: string[] = [];
  lines.push("# Corpus Trust-Tier Report");
  lines.push("");
  lines.push(
    "Trust-tier composition of the corpus (US-004). Generated by " +
      "`scripts/corpus-tier-report.ts`; kept in sync with " +
      "`scripts/lib/data-quality-scorer.ts` (surfaced live at `/api/data-quality`).",
  );
  lines.push("");
  lines.push(
    `Every lexicon row is human-curated, so in the shared graph the whole app ` +
      `corpus occupies the **${trustTierMeta(report.graphTier).label}** tier — ` +
      `auto-admission never writes \`data/source/lexicons/*.tsv\`. The breakdown below is ` +
      `**auto-admission readiness**: how each curated node row would classify by ` +
      `its own provenance.`,
  );
  lines.push("");
  lines.push(
    `**${report.totalNodeRows} node rows; ` +
      `${Math.round(report.autoAdmissionReadyRate * 1000) / 10}% ` +
      `auto-admission-ready (QID-anchored + reference-backed).**`,
  );
  lines.push("");
  lines.push(
    "| Tier | Node rows | w/ QID | w/ source_url | fully provenanced | avg confidence |",
  );
  lines.push("|---|---:|---:|---:|---:|---:|");
  for (const b of report.byTier) {
    const avg = b.avgConfidence === null ? "—" : `${Math.round(b.avgConfidence * 100)}%`;
    lines.push(
      `| ${trustTierMeta(b.tier).label} | ${b.nodeRows} | ${b.withWikidataQid} | ` +
        `${b.withSourceUrl} | ${b.fullyProvenanced} | ${avg} |`,
    );
  }
  lines.push("");
  lines.push("## Per node-file readiness");
  lines.push("");
  lines.push("| File | Node type | Rows | Auto-admission ready |");
  lines.push("|---|---|---:|---:|");
  for (const f of report.files) {
    lines.push(
      `| ${f.file} | ${f.node} | ${f.nodeRows} | ${f.autoAdmissionReady} |`,
    );
  }
  lines.push("");
  lines.push(
    "*Tiers use the shared classifier (`contracts/trust-tier.ts`), the TS mirror of " +
      "pinakes-engine's `orchestrate/tiers.py` `classify_tier`. See the JSON report " +
      "for the machine-readable form.*",
  );
  lines.push("");
  return lines.join("\n");
}

export function buildReport(lexiconsDir: string): CorpusTierReport {
  return buildCorpusTierReport(lexiconsDir);
}

export function writeReport(report: CorpusTierReport): void {
  fs.writeFileSync(JSON_OUT, `${JSON.stringify(report, null, 2)}\n`, "utf-8");
  fs.writeFileSync(MD_OUT, renderMarkdown(report), "utf-8");
}

// Run-as-CLI guard.
if (
  process.argv[1] &&
  import.meta.url.endsWith(process.argv[1].replace(/^file:\/\//, ""))
) {
  const report = buildReport(LEXICONS_DIR);
  writeReport(report);
  const readyPct = Math.round(report.autoAdmissionReadyRate * 1000) / 10;
  console.log(
    `corpus-tier-report: ${report.totalNodeRows} node rows, ${readyPct}% auto-admission-ready`,
  );
  console.log(`  wrote ${path.relative(REPO_ROOT, JSON_OUT)} + ${path.relative(REPO_ROOT, MD_OUT)}`);
}
