/**
 * Coverage report (US-008): compares actual lexicon row counts against the roadmap /
 * data-population targets per domain and flags any domain still under target.
 *
 * Emits two committed artifacts so the report is diffable + reviewable:
 *   - docs/coverage-report.json  (deterministic; asserted against the live corpus by a test)
 *   - docs/coverage-report.md    (human-readable table)
 *
 * The comparison logic + targets live in the shared data-quality-scorer service
 * (server/services/data-quality-scorer.ts), so `/api/data-quality` and this report
 * are one source of truth. Run after any data change that moves a target domain's count:
 *   npx tsx scripts/coverage-report.ts
 */
import fs from "node:fs";
import path from "node:path";
import {
  buildCoverageReport,
  type CoverageReport,
} from "../server/services/data-quality-scorer";

const REPO_ROOT = path.resolve(import.meta.dirname, "..");
const LEXICONS_DIR = path.join(REPO_ROOT, "lexicons");
const JSON_OUT = path.join(REPO_ROOT, "docs", "coverage-report.json");
const MD_OUT = path.join(REPO_ROOT, "docs", "coverage-report.md");

/** Pure: renders the coverage report as a Markdown document (deterministic). */
export function renderMarkdown(report: CoverageReport): string {
  const lines: string[] = [];
  lines.push("# Data Coverage Report");
  lines.push("");
  lines.push(
    "Actual lexicon row counts vs the roadmap / data-population targets per domain. " +
      "Generated by `scripts/coverage-report.ts`; kept in sync with " +
      "`server/services/data-quality-scorer.ts` (surfaced live at `/api/data-quality`).",
  );
  lines.push("");
  lines.push(
    report.allMet
      ? `**All ${report.domains.length} tracked domains meet their target.**`
      : `**${report.domainsMet}/${report.domains.length} domains meet their target; ` +
          `${report.domainsUnderTarget} under target: ${report.underTarget.join(", ")}.**`,
  );
  lines.push("");
  lines.push("| Domain | Actual | Target | % of target | Status | Target source |");
  lines.push("|---|---:|---|---:|:---:|---|");
  for (const d of report.domains) {
    const pct = `${Math.round(d.percentOfTarget * 100)}%`;
    const status = d.met ? "✅ met" : "⚠️ under";
    lines.push(
      `| ${d.domain} | ${d.actual} | ${d.targetLabel} | ${pct} | ${status} | ${d.source} |`,
    );
  }
  lines.push("");
  lines.push(
    "*Targets marked from the roadmap (`kind: roadmap`) are the hard §8/§15 numbers; " +
      "the newer cultural domains (`kind: breadth`) use the credible-breadth goals the " +
      "data-population stories set where the roadmap is qualitative. See the JSON report " +
      "for the machine-readable form.*",
  );
  lines.push("");
  return lines.join("\n");
}

export function buildReport(lexiconsDir: string): CoverageReport {
  return buildCoverageReport(lexiconsDir);
}

export function writeReport(report: CoverageReport): void {
  fs.writeFileSync(JSON_OUT, `${JSON.stringify(report, null, 2)}\n`, "utf-8");
  fs.writeFileSync(MD_OUT, renderMarkdown(report), "utf-8");
}

// Run-as-CLI guard.
if (
  process.argv[1] &&
  import.meta.url.endsWith(process.argv[1].replace(/^file:\/\//, ""))
) {
  const report = buildReport(LEXICONS_DIR);
  writeReport(report);
  const summary = report.allMet
    ? `all ${report.domains.length} domains met`
    : `${report.domainsUnderTarget} under target: ${report.underTarget.join(", ")}`;
  console.log(`coverage-report: ${summary}`);
  console.log(`  wrote ${path.relative(REPO_ROOT, JSON_OUT)} + ${path.relative(REPO_ROOT, MD_OUT)}`);
}
