import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, it, expect } from "vitest";
import {
  buildBindings,
  readContractDocuments,
  staleBindings,
  runCheck,
  CONTRACT_SOURCES,
  REGEN_REMEDY,
  REPO_ROOT,
  TS_OUT_DIR,
  PY_OUT_DIR,
  type ContractDocuments,
} from "./gen-contract-bindings.ts";

/**
 * A minimal but structurally complete set of source documents — enough for every emitter,
 * small enough to read. In-memory, so these tests need no temp dirs (the generator's core
 * is pure over parsed documents; only `readContractDocuments`/`writeBindings` touch disk).
 */
const FIXTURE_DOCUMENTS: ContractDocuments = {
  "canonical-schema.json": {
    version: "9.9",
    delimiter: "\t",
    node: {
      columns: [
        { field: "csid", header: "csid:ID", type: "string", role: "identity", required: true },
        { field: ":LABEL", header: ":LABEL", type: "label", role: "structural", required: true },
        { field: "license", header: "license", type: "string", role: "provenance", required: true },
      ],
    },
    edge: {
      columns: [
        { field: ":START_ID", header: ":START_ID", type: "string", role: "structural", required: true },
        { field: ":END_ID", header: ":END_ID", type: "string", role: "structural", required: true },
        { field: "time_start", header: "time_start:int", type: "int", role: "temporal", required: false },
      ],
    },
    provenanceColumns: { node: ["license"], edge: [] },
    nodeTypes: [
      { name: "language", label: "Language", description: "A language." },
      { name: "culture", label: "Culture", description: "A culture." },
    ],
    edgeTypes: [
      {
        name: "descended-from",
        type: "DESCENDED_FROM",
        description: "Descent.",
        from: ["language"],
        to: ["language"],
      },
      { name: "related-to", type: "RELATED_TO", description: "Unconstrained.", from: [], to: [] },
    ],
  },
  "capability-manifest.json": {
    kcb_version: "0.1",
    identity: "pinakes",
    capabilities: [{ name: "corpus.query" }, { name: "corpus.ground" }],
  },
  "confidence-rubric.json": {
    version: "1.0",
    order: ["qid-anchored", "stub-needs-curation"],
    classes: {
      // A prior of exactly `1` is the interesting case: it must survive as a Python float.
      "qid-anchored": { prior: 1, rationale: "Anchored on a QID." },
      "stub-needs-curation": { prior: 0.25, rationale: "Minted to recover an edge." },
    },
  },
  "lexicon-mapping.json": {
    version: "2.0",
    files: [
      { file: "languages.tsv", kind: "node" },
      { file: "etymology-relations.tsv", kind: "edge" },
      { file: "trade-routes.tsv", kind: "attribute" },
    ],
  },
  "predicate-mapping.json": {
    registryVersion: "0.4.2",
    projects: { insimul: {}, argos: {} },
  },
};

describe("gen-contract-bindings — the pure core", () => {
  it("emits one TS and one Python binding per source, plus both entry points", () => {
    const paths = [...buildBindings(FIXTURE_DOCUMENTS).keys()];
    // Every source is bound on BOTH sides — neither language may hand-maintain a copy.
    for (const source of CONTRACT_SOURCES) {
      const stem = source.replace(/\.json$/, "");
      expect(paths, source).toContain(`${TS_OUT_DIR}/${stem}.ts`);
      expect(paths, source).toContain(`${PY_OUT_DIR}/${stem.replace(/-/g, "_")}.py`);
    }
    expect(paths).toContain(`${TS_OUT_DIR}/index.ts`);
    expect(paths).toContain(`${PY_OUT_DIR}/__init__.py`);
    expect(paths).toHaveLength(CONTRACT_SOURCES.length * 2 + 2);
  });

  it("is deterministic — two builds from the same documents are byte-identical", () => {
    // What the whole drift gate rests on: no wall-clock, no set/hash iteration order.
    expect(buildBindings(FIXTURE_DOCUMENTS)).toEqual(buildBindings(FIXTURE_DOCUMENTS));
  });

  it("marks every generated file DO NOT EDIT and names the one remedy", () => {
    for (const [path, content] of buildBindings(FIXTURE_DOCUMENTS)) {
      expect(content, path).toContain("@generated by scripts/gen-contract-bindings.ts");
      expect(content, path).toContain("DO NOT EDIT");
      expect(content, path).toContain(REGEN_REMEDY);
    }
  });

  it("carries the source vocabulary into both languages", () => {
    const bindings = buildBindings(FIXTURE_DOCUMENTS);
    const ts = bindings.get(`${TS_OUT_DIR}/canonical-schema.ts`) ?? "";
    const py = bindings.get(`${PY_OUT_DIR}/canonical_schema.py`) ?? "";
    for (const source of [ts, py]) {
      expect(source).toContain('"DESCENDED_FROM"');
      expect(source).toContain('"Language"');
      // The header row is joined on the contract's own delimiter, not a hard-coded tab.
      expect(source).toContain(String.raw`"csid:ID\t:LABEL\tlicense"`);
    }
  });

  it("emits an integer prior as a Python float (a `1` prior must stay a float)", () => {
    const py = buildBindings(FIXTURE_DOCUMENTS).get(`${PY_OUT_DIR}/confidence_rubric.py`) ?? "";
    expect(py).toContain('"qid-anchored": 1.0,');
    expect(py).not.toContain('"qid-anchored": 1,');
  });
});

describe("gen-contract-bindings — drift gate (US-2)", () => {
  // The load-bearing test: regenerate from `contracts/*.json` and byte-compare against the
  // bindings committed in this tree. Editing a source without `npm run gen:contracts`, or
  // hand-editing a generated file, fails HERE — the same drift-fails-CI discipline as the
  // koine registry mirror. Unlike that one this needs no sibling checkout, so it never skips.
  const bindings = buildBindings(readContractDocuments());

  it.each([...bindings.keys()])("committed %s matches a fresh generation byte-for-byte", (path) => {
    const committed = readFileSync(join(REPO_ROOT, path), "utf8");
    expect(committed, `${path} is stale — run \`${REGEN_REMEDY}\` and commit the result`).toBe(
      bindings.get(path),
    );
  });

  it("reports no stale binding at all (Python and TypeScript)", () => {
    expect(staleBindings()).toEqual([]);
  });

  it("check:contracts exits 0 here and writes nothing", () => {
    const before = [...bindings.keys()].map((path) => readFileSync(join(REPO_ROOT, path), "utf8"));
    expect(runCheck()).toBe(0);
    // Read-only by contract: `--check` is what the merge gate runs, and a gate that mutates
    // the tree it is checking would turn every drifted branch into a silently-fixed one.
    expect([...bindings.keys()].map((path) => readFileSync(join(REPO_ROOT, path), "utf8"))).toEqual(
      before,
    );
  });

  it("detects a stale binding rather than passing on a wrong root", () => {
    // Negative control: point the staleness check at a tree with no bindings in it and every
    // file must come back stale — otherwise a green `staleBindings()` above proves nothing.
    expect(staleBindings(bindings, join(REPO_ROOT, "does-not-exist"))).toEqual([...bindings.keys()]);
  });
});
