import { db } from "../db";
import { baseWords } from "@shared/schema";

export class VocabularyExpander {
  
  async expandBaseVocabulary(): Promise<void> {
    console.log("Starting base vocabulary expansion to 2000 words...");

    // Core vocabulary categories with high-frequency words
    const vocabularyCategories = this.getCoreVocabularyData();
    
    let totalAdded = 0;
    let position = 1000; // Start from 1000 to avoid conflicts with existing words
    
    for (const [category, words] of Object.entries(vocabularyCategories)) {
      console.log(`Adding ${category} vocabulary (${words.length} words)...`);
      
      for (const wordData of words) {
        try {
          await db.insert(baseWords).values({
            word: wordData.word.toLowerCase(),
            position: position,
            category: category,
            frequency: wordData.frequency ? wordData.frequency.toString() : "1.0",
            difficulty: wordData.difficulty || 1,
            pos: wordData.pos || 'noun',
            notes: wordData.notes || null
          }).onConflictDoNothing(); // Avoid duplicates
          
          totalAdded++;
          position++;
        } catch (error) {
          console.error(`Error adding word "${wordData.word}":`, error);
        }
      }
    }
    
    console.log(`Base vocabulary expansion completed. Added ${totalAdded} new words.`);
  }

  private getCoreVocabularyData() {
    return {
      // Basic Personal & Family (50 words)
      personal_family: [
        { word: "person", pos: "noun", frequency: 0.95, difficulty: 1 },
        { word: "man", pos: "noun", frequency: 0.95, difficulty: 1 },
        { word: "woman", pos: "noun", frequency: 0.95, difficulty: 1 },
        { word: "child", pos: "noun", frequency: 0.90, difficulty: 1 },
        { word: "boy", pos: "noun", frequency: 0.85, difficulty: 1 },
        { word: "girl", pos: "noun", frequency: 0.85, difficulty: 1 },
        { word: "baby", pos: "noun", frequency: 0.80, difficulty: 1 },
        { word: "mother", pos: "noun", frequency: 0.90, difficulty: 1 },
        { word: "father", pos: "noun", frequency: 0.90, difficulty: 1 },
        { word: "parent", pos: "noun", frequency: 0.75, difficulty: 2 },
        { word: "son", pos: "noun", frequency: 0.80, difficulty: 1 },
        { word: "daughter", pos: "noun", frequency: 0.80, difficulty: 1 },
        { word: "brother", pos: "noun", frequency: 0.75, difficulty: 1 },
        { word: "sister", pos: "noun", frequency: 0.75, difficulty: 1 },
        { word: "family", pos: "noun", frequency: 0.85, difficulty: 1 },
        { word: "friend", pos: "noun", frequency: 0.85, difficulty: 1 },
        { word: "husband", pos: "noun", frequency: 0.70, difficulty: 1 },
        { word: "wife", pos: "noun", frequency: 0.70, difficulty: 1 },
        { word: "grandfather", pos: "noun", frequency: 0.60, difficulty: 1 },
        { word: "grandmother", pos: "noun", frequency: 0.60, difficulty: 1 },
        { word: "uncle", pos: "noun", frequency: 0.55, difficulty: 1 },
        { word: "aunt", pos: "noun", frequency: 0.55, difficulty: 1 },
        { word: "cousin", pos: "noun", frequency: 0.50, difficulty: 1 },
        { word: "nephew", pos: "noun", frequency: 0.45, difficulty: 2 },
        { word: "niece", pos: "noun", frequency: 0.45, difficulty: 2 },
        { word: "name", pos: "noun", frequency: 0.90, difficulty: 1 },
        { word: "age", pos: "noun", frequency: 0.80, difficulty: 1 },
        { word: "birth", pos: "noun", frequency: 0.65, difficulty: 1 },
        { word: "death", pos: "noun", frequency: 0.65, difficulty: 1 },
        { word: "life", pos: "noun", frequency: 0.90, difficulty: 1 }
      ],

      // Body Parts (60 words)
      body_parts: [
        { word: "body", pos: "noun", frequency: 0.85, difficulty: 1 },
        { word: "head", pos: "noun", frequency: 0.85, difficulty: 1 },
        { word: "face", pos: "noun", frequency: 0.85, difficulty: 1 },
        { word: "eye", pos: "noun", frequency: 0.90, difficulty: 1 },
        { word: "nose", pos: "noun", frequency: 0.80, difficulty: 1 },
        { word: "mouth", pos: "noun", frequency: 0.80, difficulty: 1 },
        { word: "ear", pos: "noun", frequency: 0.75, difficulty: 1 },
        { word: "tooth", pos: "noun", frequency: 0.70, difficulty: 1 },
        { word: "tongue", pos: "noun", frequency: 0.65, difficulty: 1 },
        { word: "lip", pos: "noun", frequency: 0.60, difficulty: 1 },
        { word: "hair", pos: "noun", frequency: 0.80, difficulty: 1 },
        { word: "neck", pos: "noun", frequency: 0.70, difficulty: 1 },
        { word: "shoulder", pos: "noun", frequency: 0.70, difficulty: 1 },
        { word: "arm", pos: "noun", frequency: 0.85, difficulty: 1 },
        { word: "hand", pos: "noun", frequency: 0.95, difficulty: 1 },
        { word: "finger", pos: "noun", frequency: 0.75, difficulty: 1 },
        { word: "thumb", pos: "noun", frequency: 0.60, difficulty: 1 },
        { word: "chest", pos: "noun", frequency: 0.70, difficulty: 1 },
        { word: "back", pos: "noun", frequency: 0.85, difficulty: 1 },
        { word: "stomach", pos: "noun", frequency: 0.70, difficulty: 1 },
        { word: "leg", pos: "noun", frequency: 0.85, difficulty: 1 },
        { word: "foot", pos: "noun", frequency: 0.85, difficulty: 1 },
        { word: "knee", pos: "noun", frequency: 0.70, difficulty: 1 },
        { word: "toe", pos: "noun", frequency: 0.65, difficulty: 1 },
        { word: "skin", pos: "noun", frequency: 0.75, difficulty: 1 },
        { word: "blood", pos: "noun", frequency: 0.80, difficulty: 1 },
        { word: "bone", pos: "noun", frequency: 0.70, difficulty: 1 },
        { word: "heart", pos: "noun", frequency: 0.85, difficulty: 1 },
        { word: "brain", pos: "noun", frequency: 0.80, difficulty: 1 },
        { word: "muscle", pos: "noun", frequency: 0.65, difficulty: 2 }
      ],

      // Colors (20 words)
      colors: [
        { word: "color", pos: "noun", frequency: 0.80, difficulty: 1 },
        { word: "red", pos: "adjective", frequency: 0.85, difficulty: 1 },
        { word: "blue", pos: "adjective", frequency: 0.85, difficulty: 1 },
        { word: "green", pos: "adjective", frequency: 0.85, difficulty: 1 },
        { word: "yellow", pos: "adjective", frequency: 0.80, difficulty: 1 },
        { word: "black", pos: "adjective", frequency: 0.90, difficulty: 1 },
        { word: "white", pos: "adjective", frequency: 0.90, difficulty: 1 },
        { word: "brown", pos: "adjective", frequency: 0.75, difficulty: 1 },
        { word: "orange", pos: "adjective", frequency: 0.70, difficulty: 1 },
        { word: "purple", pos: "adjective", frequency: 0.65, difficulty: 1 },
        { word: "pink", pos: "adjective", frequency: 0.65, difficulty: 1 },
        { word: "gray", pos: "adjective", frequency: 0.70, difficulty: 1 },
        { word: "silver", pos: "adjective", frequency: 0.55, difficulty: 1 },
        { word: "gold", pos: "adjective", frequency: 0.60, difficulty: 1 },
        { word: "dark", pos: "adjective", frequency: 0.80, difficulty: 1 },
        { word: "light", pos: "adjective", frequency: 0.85, difficulty: 1 },
        { word: "bright", pos: "adjective", frequency: 0.70, difficulty: 1 },
        { word: "pale", pos: "adjective", frequency: 0.55, difficulty: 2 },
        { word: "clear", pos: "adjective", frequency: 0.75, difficulty: 1 },
        { word: "transparent", pos: "adjective", frequency: 0.45, difficulty: 3 }
      ],

      // Numbers & Time (80 words)
      numbers_time: [
        { word: "number", pos: "noun", frequency: 0.85, difficulty: 1 },
        { word: "zero", pos: "noun", frequency: 0.70, difficulty: 1 },
        { word: "one", pos: "number", frequency: 0.95, difficulty: 1 },
        { word: "two", pos: "number", frequency: 0.95, difficulty: 1 },
        { word: "three", pos: "number", frequency: 0.90, difficulty: 1 },
        { word: "four", pos: "number", frequency: 0.90, difficulty: 1 },
        { word: "five", pos: "number", frequency: 0.90, difficulty: 1 },
        { word: "six", pos: "number", frequency: 0.85, difficulty: 1 },
        { word: "seven", pos: "number", frequency: 0.85, difficulty: 1 },
        { word: "eight", pos: "number", frequency: 0.85, difficulty: 1 },
        { word: "nine", pos: "number", frequency: 0.85, difficulty: 1 },
        { word: "ten", pos: "number", frequency: 0.90, difficulty: 1 },
        { word: "eleven", pos: "number", frequency: 0.75, difficulty: 1 },
        { word: "twelve", pos: "number", frequency: 0.75, difficulty: 1 },
        { word: "thirteen", pos: "number", frequency: 0.70, difficulty: 1 },
        { word: "fourteen", pos: "number", frequency: 0.70, difficulty: 1 },
        { word: "fifteen", pos: "number", frequency: 0.70, difficulty: 1 },
        { word: "sixteen", pos: "number", frequency: 0.65, difficulty: 1 },
        { word: "seventeen", pos: "number", frequency: 0.65, difficulty: 1 },
        { word: "eighteen", pos: "number", frequency: 0.65, difficulty: 1 },
        { word: "nineteen", pos: "number", frequency: 0.65, difficulty: 1 },
        { word: "twenty", pos: "number", frequency: 0.80, difficulty: 1 },
        { word: "thirty", pos: "number", frequency: 0.75, difficulty: 1 },
        { word: "forty", pos: "number", frequency: 0.70, difficulty: 1 },
        { word: "fifty", pos: "number", frequency: 0.70, difficulty: 1 },
        { word: "sixty", pos: "number", frequency: 0.65, difficulty: 1 },
        { word: "seventy", pos: "number", frequency: 0.65, difficulty: 1 },
        { word: "eighty", pos: "number", frequency: 0.60, difficulty: 1 },
        { word: "ninety", pos: "number", frequency: 0.60, difficulty: 1 },
        { word: "hundred", pos: "number", frequency: 0.80, difficulty: 1 },
        { word: "thousand", pos: "number", frequency: 0.80, difficulty: 1 },
        { word: "million", pos: "number", frequency: 0.75, difficulty: 1 },
        { word: "first", pos: "ordinal", frequency: 0.90, difficulty: 1 },
        { word: "second", pos: "ordinal", frequency: 0.85, difficulty: 1 },
        { word: "third", pos: "ordinal", frequency: 0.80, difficulty: 1 },
        { word: "fourth", pos: "ordinal", frequency: 0.70, difficulty: 1 },
        { word: "fifth", pos: "ordinal", frequency: 0.65, difficulty: 1 },
        { word: "last", pos: "ordinal", frequency: 0.85, difficulty: 1 },
        { word: "time", pos: "noun", frequency: 0.95, difficulty: 1 },
        { word: "year", pos: "noun", frequency: 0.95, difficulty: 1 },
        { word: "month", pos: "noun", frequency: 0.85, difficulty: 1 },
        { word: "week", pos: "noun", frequency: 0.85, difficulty: 1 },
        { word: "day", pos: "noun", frequency: 0.95, difficulty: 1 },
        { word: "hour", pos: "noun", frequency: 0.85, difficulty: 1 },
        { word: "minute", pos: "noun", frequency: 0.85, difficulty: 1 },
        { word: "second", pos: "noun", frequency: 0.80, difficulty: 1 },
        { word: "moment", pos: "noun", frequency: 0.75, difficulty: 1 },
        { word: "today", pos: "adverb", frequency: 0.90, difficulty: 1 },
        { word: "yesterday", pos: "adverb", frequency: 0.80, difficulty: 1 },
        { word: "tomorrow", pos: "adverb", frequency: 0.80, difficulty: 1 },
        { word: "now", pos: "adverb", frequency: 0.95, difficulty: 1 },
        { word: "then", pos: "adverb", frequency: 0.90, difficulty: 1 },
        { word: "soon", pos: "adverb", frequency: 0.80, difficulty: 1 },
        { word: "late", pos: "adjective", frequency: 0.85, difficulty: 1 },
        { word: "early", pos: "adjective", frequency: 0.80, difficulty: 1 },
        { word: "morning", pos: "noun", frequency: 0.85, difficulty: 1 },
        { word: "afternoon", pos: "noun", frequency: 0.75, difficulty: 1 },
        { word: "evening", pos: "noun", frequency: 0.75, difficulty: 1 },
        { word: "night", pos: "noun", frequency: 0.90, difficulty: 1 },
        { word: "midnight", pos: "noun", frequency: 0.60, difficulty: 1 },
        { word: "noon", pos: "noun", frequency: 0.65, difficulty: 1 }
      ],

      // Common Verbs (150 words)
      common_verbs: [
        { word: "be", pos: "verb", frequency: 1.0, difficulty: 1 },
        { word: "have", pos: "verb", frequency: 1.0, difficulty: 1 },
        { word: "do", pos: "verb", frequency: 1.0, difficulty: 1 },
        { word: "say", pos: "verb", frequency: 0.95, difficulty: 1 },
        { word: "get", pos: "verb", frequency: 0.95, difficulty: 1 },
        { word: "make", pos: "verb", frequency: 0.95, difficulty: 1 },
        { word: "go", pos: "verb", frequency: 0.95, difficulty: 1 },
        { word: "know", pos: "verb", frequency: 0.95, difficulty: 1 },
        { word: "take", pos: "verb", frequency: 0.90, difficulty: 1 },
        { word: "see", pos: "verb", frequency: 0.90, difficulty: 1 },
        { word: "come", pos: "verb", frequency: 0.90, difficulty: 1 },
        { word: "think", pos: "verb", frequency: 0.90, difficulty: 1 },
        { word: "look", pos: "verb", frequency: 0.90, difficulty: 1 },
        { word: "want", pos: "verb", frequency: 0.90, difficulty: 1 },
        { word: "give", pos: "verb", frequency: 0.85, difficulty: 1 },
        { word: "use", pos: "verb", frequency: 0.85, difficulty: 1 },
        { word: "find", pos: "verb", frequency: 0.85, difficulty: 1 },
        { word: "tell", pos: "verb", frequency: 0.85, difficulty: 1 },
        { word: "ask", pos: "verb", frequency: 0.85, difficulty: 1 },
        { word: "work", pos: "verb", frequency: 0.85, difficulty: 1 },
        { word: "seem", pos: "verb", frequency: 0.80, difficulty: 1 },
        { word: "feel", pos: "verb", frequency: 0.80, difficulty: 1 },
        { word: "try", pos: "verb", frequency: 0.80, difficulty: 1 },
        { word: "leave", pos: "verb", frequency: 0.80, difficulty: 1 },
        { word: "call", pos: "verb", frequency: 0.80, difficulty: 1 },
        { word: "move", pos: "verb", frequency: 0.75, difficulty: 1 },
        { word: "live", pos: "verb", frequency: 0.80, difficulty: 1 },
        { word: "believe", pos: "verb", frequency: 0.75, difficulty: 1 },
        { word: "hold", pos: "verb", frequency: 0.75, difficulty: 1 },
        { word: "bring", pos: "verb", frequency: 0.75, difficulty: 1 },
        { word: "happen", pos: "verb", frequency: 0.75, difficulty: 1 },
        { word: "write", pos: "verb", frequency: 0.75, difficulty: 1 },
        { word: "provide", pos: "verb", frequency: 0.70, difficulty: 2 },
        { word: "sit", pos: "verb", frequency: 0.80, difficulty: 1 },
        { word: "stand", pos: "verb", frequency: 0.80, difficulty: 1 },
        { word: "lose", pos: "verb", frequency: 0.75, difficulty: 1 },
        { word: "pay", pos: "verb", frequency: 0.75, difficulty: 1 },
        { word: "meet", pos: "verb", frequency: 0.75, difficulty: 1 },
        { word: "include", pos: "verb", frequency: 0.70, difficulty: 2 },
        { word: "continue", pos: "verb", frequency: 0.70, difficulty: 2 },
        { word: "set", pos: "verb", frequency: 0.80, difficulty: 1 },
        { word: "learn", pos: "verb", frequency: 0.80, difficulty: 1 },
        { word: "change", pos: "verb", frequency: 0.80, difficulty: 1 },
        { word: "lead", pos: "verb", frequency: 0.75, difficulty: 1 },
        { word: "understand", pos: "verb", frequency: 0.80, difficulty: 1 },
        { word: "watch", pos: "verb", frequency: 0.80, difficulty: 1 },
        { word: "follow", pos: "verb", frequency: 0.75, difficulty: 1 },
        { word: "stop", pos: "verb", frequency: 0.80, difficulty: 1 },
        { word: "create", pos: "verb", frequency: 0.75, difficulty: 1 },
        { word: "speak", pos: "verb", frequency: 0.75, difficulty: 1 },
        { word: "read", pos: "verb", frequency: 0.80, difficulty: 1 },
        { word: "allow", pos: "verb", frequency: 0.75, difficulty: 2 },
        { word: "add", pos: "verb", frequency: 0.70, difficulty: 1 },
        { word: "spend", pos: "verb", frequency: 0.75, difficulty: 1 },
        { word: "grow", pos: "verb", frequency: 0.75, difficulty: 1 },
        { word: "open", pos: "verb", frequency: 0.80, difficulty: 1 },
        { word: "walk", pos: "verb", frequency: 0.80, difficulty: 1 },
        { word: "win", pos: "verb", frequency: 0.75, difficulty: 1 },
        { word: "offer", pos: "verb", frequency: 0.70, difficulty: 2 },
        { word: "remember", pos: "verb", frequency: 0.80, difficulty: 1 },
        { word: "love", pos: "verb", frequency: 0.85, difficulty: 1 },
        { word: "consider", pos: "verb", frequency: 0.70, difficulty: 2 },
        { word: "appear", pos: "verb", frequency: 0.70, difficulty: 2 },
        { word: "buy", pos: "verb", frequency: 0.80, difficulty: 1 },
        { word: "wait", pos: "verb", frequency: 0.80, difficulty: 1 },
        { word: "serve", pos: "verb", frequency: 0.70, difficulty: 1 },
        { word: "die", pos: "verb", frequency: 0.75, difficulty: 1 },
        { word: "send", pos: "verb", frequency: 0.75, difficulty: 1 },
        { word: "expect", pos: "verb", frequency: 0.75, difficulty: 1 },
        { word: "build", pos: "verb", frequency: 0.75, difficulty: 1 },
        { word: "stay", pos: "verb", frequency: 0.80, difficulty: 1 },
        { word: "fall", pos: "verb", frequency: 0.75, difficulty: 1 },
        { word: "cut", pos: "verb", frequency: 0.75, difficulty: 1 },
        { word: "reach", pos: "verb", frequency: 0.70, difficulty: 1 },
        { word: "kill", pos: "verb", frequency: 0.70, difficulty: 1 },
        { word: "remain", pos: "verb", frequency: 0.70, difficulty: 2 },
        { word: "suggest", pos: "verb", frequency: 0.65, difficulty: 2 },
        { word: "raise", pos: "verb", frequency: 0.70, difficulty: 1 },
        { word: "pass", pos: "verb", frequency: 0.75, difficulty: 1 },
        { word: "sell", pos: "verb", frequency: 0.70, difficulty: 1 },
        { word: "require", pos: "verb", frequency: 0.65, difficulty: 2 },
        { word: "report", pos: "verb", frequency: 0.65, difficulty: 2 },
        { word: "decide", pos: "verb", frequency: 0.75, difficulty: 1 },
        { word: "pull", pos: "verb", frequency: 0.70, difficulty: 1 },
        { word: "break", pos: "verb", frequency: 0.75, difficulty: 1 },
        { word: "pick", pos: "verb", frequency: 0.70, difficulty: 1 },
        { word: "carry", pos: "verb", frequency: 0.70, difficulty: 1 },
        { word: "catch", pos: "verb", frequency: 0.70, difficulty: 1 },
        { word: "drive", pos: "verb", frequency: 0.75, difficulty: 1 },
        { word: "throw", pos: "verb", frequency: 0.70, difficulty: 1 },
        { word: "save", pos: "verb", frequency: 0.70, difficulty: 1 },
        { word: "show", pos: "verb", frequency: 0.80, difficulty: 1 },
        { word: "help", pos: "verb", frequency: 0.85, difficulty: 1 },
        { word: "hear", pos: "verb", frequency: 0.80, difficulty: 1 },
        { word: "play", pos: "verb", frequency: 0.80, difficulty: 1 },
        { word: "run", pos: "verb", frequency: 0.80, difficulty: 1 },
        { word: "move", pos: "verb", frequency: 0.75, difficulty: 1 },
        { word: "like", pos: "verb", frequency: 0.90, difficulty: 1 },
        { word: "need", pos: "verb", frequency: 0.90, difficulty: 1 },
        { word: "turn", pos: "verb", frequency: 0.80, difficulty: 1 },
        { word: "start", pos: "verb", frequency: 0.80, difficulty: 1 },
        { word: "put", pos: "verb", frequency: 0.85, difficulty: 1 },
        { word: "end", pos: "verb", frequency: 0.75, difficulty: 1 },
        { word: "why", pos: "adverb", frequency: 0.90, difficulty: 1 },
        { word: "let", pos: "verb", frequency: 0.80, difficulty: 1 },
        { word: "keep", pos: "verb", frequency: 0.80, difficulty: 1 },
        { word: "begin", pos: "verb", frequency: 0.75, difficulty: 1 },
        { word: "close", pos: "verb", frequency: 0.75, difficulty: 1 }
      ],

      // Food & Drink (100 words) 
      food_drink: [
        { word: "food", pos: "noun", frequency: 0.85, difficulty: 1 },
        { word: "eat", pos: "verb", frequency: 0.90, difficulty: 1 },
        { word: "drink", pos: "verb", frequency: 0.85, difficulty: 1 },
        { word: "water", pos: "noun", frequency: 0.90, difficulty: 1 },
        { word: "bread", pos: "noun", frequency: 0.75, difficulty: 1 },
        { word: "meat", pos: "noun", frequency: 0.80, difficulty: 1 },
        { word: "fish", pos: "noun", frequency: 0.75, difficulty: 1 },
        { word: "chicken", pos: "noun", frequency: 0.70, difficulty: 1 },
        { word: "beef", pos: "noun", frequency: 0.65, difficulty: 1 },
        { word: "pork", pos: "noun", frequency: 0.60, difficulty: 1 },
        { word: "egg", pos: "noun", frequency: 0.75, difficulty: 1 },
        { word: "milk", pos: "noun", frequency: 0.75, difficulty: 1 },
        { word: "cheese", pos: "noun", frequency: 0.70, difficulty: 1 },
        { word: "butter", pos: "noun", frequency: 0.65, difficulty: 1 },
        { word: "rice", pos: "noun", frequency: 0.70, difficulty: 1 },
        { word: "potato", pos: "noun", frequency: 0.70, difficulty: 1 },
        { word: "vegetable", pos: "noun", frequency: 0.70, difficulty: 1 },
        { word: "fruit", pos: "noun", frequency: 0.75, difficulty: 1 },
        { word: "apple", pos: "noun", frequency: 0.70, difficulty: 1 },
        { word: "orange", pos: "noun", frequency: 0.65, difficulty: 1 },
        { word: "banana", pos: "noun", frequency: 0.65, difficulty: 1 },
        { word: "grape", pos: "noun", frequency: 0.60, difficulty: 1 },
        { word: "lemon", pos: "noun", frequency: 0.60, difficulty: 1 },
        { word: "tomato", pos: "noun", frequency: 0.65, difficulty: 1 },
        { word: "onion", pos: "noun", frequency: 0.60, difficulty: 1 },
        { word: "carrot", pos: "noun", frequency: 0.55, difficulty: 1 },
        { word: "bean", pos: "noun", frequency: 0.55, difficulty: 1 },
        { word: "salt", pos: "noun", frequency: 0.70, difficulty: 1 },
        { word: "sugar", pos: "noun", frequency: 0.70, difficulty: 1 },
        { word: "oil", pos: "noun", frequency: 0.65, difficulty: 1 },
        { word: "tea", pos: "noun", frequency: 0.75, difficulty: 1 },
        { word: "coffee", pos: "noun", frequency: 0.80, difficulty: 1 },
        { word: "beer", pos: "noun", frequency: 0.70, difficulty: 1 },
        { word: "wine", pos: "noun", frequency: 0.70, difficulty: 1 },
        { word: "juice", pos: "noun", frequency: 0.65, difficulty: 1 },
        { word: "soup", pos: "noun", frequency: 0.65, difficulty: 1 },
        { word: "cake", pos: "noun", frequency: 0.65, difficulty: 1 },
        { word: "cookie", pos: "noun", frequency: 0.60, difficulty: 1 },
        { word: "chocolate", pos: "noun", frequency: 0.65, difficulty: 1 },
        { word: "ice", pos: "noun", frequency: 0.70, difficulty: 1 }
      ],

      // Home & Daily Life (120 words)
      home_daily: [
        { word: "home", pos: "noun", frequency: 0.90, difficulty: 1 },
        { word: "house", pos: "noun", frequency: 0.85, difficulty: 1 },
        { word: "room", pos: "noun", frequency: 0.80, difficulty: 1 },
        { word: "door", pos: "noun", frequency: 0.80, difficulty: 1 },
        { word: "window", pos: "noun", frequency: 0.75, difficulty: 1 },
        { word: "wall", pos: "noun", frequency: 0.75, difficulty: 1 },
        { word: "floor", pos: "noun", frequency: 0.70, difficulty: 1 },
        { word: "ceiling", pos: "noun", frequency: 0.60, difficulty: 1 },
        { word: "kitchen", pos: "noun", frequency: 0.70, difficulty: 1 },
        { word: "bathroom", pos: "noun", frequency: 0.65, difficulty: 1 },
        { word: "bedroom", pos: "noun", frequency: 0.65, difficulty: 1 },
        { word: "bed", pos: "noun", frequency: 0.80, difficulty: 1 },
        { word: "chair", pos: "noun", frequency: 0.75, difficulty: 1 },
        { word: "table", pos: "noun", frequency: 0.80, difficulty: 1 },
        { word: "desk", pos: "noun", frequency: 0.70, difficulty: 1 },
        { word: "sofa", pos: "noun", frequency: 0.60, difficulty: 1 },
        { word: "television", pos: "noun", frequency: 0.70, difficulty: 1 },
        { word: "phone", pos: "noun", frequency: 0.80, difficulty: 1 },
        { word: "computer", pos: "noun", frequency: 0.75, difficulty: 1 },
        { word: "book", pos: "noun", frequency: 0.85, difficulty: 1 },
        { word: "paper", pos: "noun", frequency: 0.75, difficulty: 1 },
        { word: "pen", pos: "noun", frequency: 0.70, difficulty: 1 },
        { word: "pencil", pos: "noun", frequency: 0.65, difficulty: 1 },
        { word: "key", pos: "noun", frequency: 0.70, difficulty: 1 },
        { word: "money", pos: "noun", frequency: 0.85, difficulty: 1 },
        { word: "bag", pos: "noun", frequency: 0.75, difficulty: 1 },
        { word: "box", pos: "noun", frequency: 0.75, difficulty: 1 },
        { word: "bottle", pos: "noun", frequency: 0.70, difficulty: 1 },
        { word: "cup", pos: "noun", frequency: 0.70, difficulty: 1 },
        { word: "plate", pos: "noun", frequency: 0.65, difficulty: 1 },
        { word: "knife", pos: "noun", frequency: 0.65, difficulty: 1 },
        { word: "spoon", pos: "noun", frequency: 0.60, difficulty: 1 },
        { word: "fork", pos: "noun", frequency: 0.60, difficulty: 1 },
        { word: "glass", pos: "noun", frequency: 0.70, difficulty: 1 },
        { word: "clothes", pos: "noun", frequency: 0.75, difficulty: 1 },
        { word: "shirt", pos: "noun", frequency: 0.70, difficulty: 1 },
        { word: "pants", pos: "noun", frequency: 0.65, difficulty: 1 },
        { word: "dress", pos: "noun", frequency: 0.65, difficulty: 1 },
        { word: "shoes", pos: "noun", frequency: 0.75, difficulty: 1 },
        { word: "hat", pos: "noun", frequency: 0.60, difficulty: 1 }
      ],

      // Nature & Environment (80 words)
      nature_environment: [
        { word: "nature", pos: "noun", frequency: 0.70, difficulty: 1 },
        { word: "world", pos: "noun", frequency: 0.90, difficulty: 1 },
        { word: "earth", pos: "noun", frequency: 0.80, difficulty: 1 },
        { word: "land", pos: "noun", frequency: 0.80, difficulty: 1 },
        { word: "country", pos: "noun", frequency: 0.85, difficulty: 1 },
        { word: "city", pos: "noun", frequency: 0.85, difficulty: 1 },
        { word: "town", pos: "noun", frequency: 0.75, difficulty: 1 },
        { word: "village", pos: "noun", frequency: 0.65, difficulty: 1 },
        { word: "street", pos: "noun", frequency: 0.80, difficulty: 1 },
        { word: "road", pos: "noun", frequency: 0.80, difficulty: 1 },
        { word: "river", pos: "noun", frequency: 0.70, difficulty: 1 },
        { word: "lake", pos: "noun", frequency: 0.65, difficulty: 1 },
        { word: "sea", pos: "noun", frequency: 0.75, difficulty: 1 },
        { word: "ocean", pos: "noun", frequency: 0.70, difficulty: 1 },
        { word: "mountain", pos: "noun", frequency: 0.70, difficulty: 1 },
        { word: "hill", pos: "noun", frequency: 0.65, difficulty: 1 },
        { word: "forest", pos: "noun", frequency: 0.65, difficulty: 1 },
        { word: "tree", pos: "noun", frequency: 0.80, difficulty: 1 },
        { word: "flower", pos: "noun", frequency: 0.70, difficulty: 1 },
        { word: "grass", pos: "noun", frequency: 0.65, difficulty: 1 },
        { word: "plant", pos: "noun", frequency: 0.70, difficulty: 1 },
        { word: "animal", pos: "noun", frequency: 0.80, difficulty: 1 },
        { word: "bird", pos: "noun", frequency: 0.75, difficulty: 1 },
        { word: "dog", pos: "noun", frequency: 0.85, difficulty: 1 },
        { word: "cat", pos: "noun", frequency: 0.80, difficulty: 1 },
        { word: "horse", pos: "noun", frequency: 0.70, difficulty: 1 },
        { word: "cow", pos: "noun", frequency: 0.65, difficulty: 1 },
        { word: "sheep", pos: "noun", frequency: 0.60, difficulty: 1 },
        { word: "pig", pos: "noun", frequency: 0.60, difficulty: 1 },
        { word: "sun", pos: "noun", frequency: 0.85, difficulty: 1 },
        { word: "moon", pos: "noun", frequency: 0.75, difficulty: 1 },
        { word: "star", pos: "noun", frequency: 0.75, difficulty: 1 },
        { word: "sky", pos: "noun", frequency: 0.75, difficulty: 1 },
        { word: "cloud", pos: "noun", frequency: 0.70, difficulty: 1 },
        { word: "rain", pos: "noun", frequency: 0.75, difficulty: 1 },
        { word: "snow", pos: "noun", frequency: 0.70, difficulty: 1 },
        { word: "wind", pos: "noun", frequency: 0.70, difficulty: 1 },
        { word: "fire", pos: "noun", frequency: 0.75, difficulty: 1 },
        { word: "stone", pos: "noun", frequency: 0.65, difficulty: 1 },
        { word: "rock", pos: "noun", frequency: 0.70, difficulty: 1 }
      ],

      // Transportation (50 words)
      transportation: [
        { word: "car", pos: "noun", frequency: 0.90, difficulty: 1 },
        { word: "bus", pos: "noun", frequency: 0.75, difficulty: 1 },
        { word: "train", pos: "noun", frequency: 0.75, difficulty: 1 },
        { word: "plane", pos: "noun", frequency: 0.70, difficulty: 1 },
        { word: "ship", pos: "noun", frequency: 0.65, difficulty: 1 },
        { word: "boat", pos: "noun", frequency: 0.65, difficulty: 1 },
        { word: "bicycle", pos: "noun", frequency: 0.60, difficulty: 1 },
        { word: "truck", pos: "noun", frequency: 0.65, difficulty: 1 },
        { word: "taxi", pos: "noun", frequency: 0.60, difficulty: 1 },
        { word: "motorcycle", pos: "noun", frequency: 0.55, difficulty: 2 },
        { word: "wheel", pos: "noun", frequency: 0.65, difficulty: 1 },
        { word: "engine", pos: "noun", frequency: 0.60, difficulty: 1 },
        { word: "fuel", pos: "noun", frequency: 0.55, difficulty: 2 },
        { word: "gas", pos: "noun", frequency: 0.70, difficulty: 1 },
        { word: "oil", pos: "noun", frequency: 0.65, difficulty: 1 },
        { word: "road", pos: "noun", frequency: 0.80, difficulty: 1 },
        { word: "bridge", pos: "noun", frequency: 0.65, difficulty: 1 },
        { word: "station", pos: "noun", frequency: 0.70, difficulty: 1 },
        { word: "airport", pos: "noun", frequency: 0.65, difficulty: 1 },
        { word: "ticket", pos: "noun", frequency: 0.65, difficulty: 1 },
        { word: "travel", pos: "verb", frequency: 0.75, difficulty: 1 },
        { word: "trip", pos: "noun", frequency: 0.70, difficulty: 1 },
        { word: "journey", pos: "noun", frequency: 0.60, difficulty: 2 },
        { word: "visit", pos: "verb", frequency: 0.75, difficulty: 1 },
        { word: "arrive", pos: "verb", frequency: 0.70, difficulty: 1 },
        { word: "depart", pos: "verb", frequency: 0.60, difficulty: 2 },
        { word: "return", pos: "verb", frequency: 0.75, difficulty: 1 },
        { word: "fast", pos: "adjective", frequency: 0.80, difficulty: 1 },
        { word: "slow", pos: "adjective", frequency: 0.75, difficulty: 1 },
        { word: "speed", pos: "noun", frequency: 0.70, difficulty: 1 }
      ],

      // Education & Work (100 words)
      education_work: [
        { word: "school", pos: "noun", frequency: 0.85, difficulty: 1 },
        { word: "student", pos: "noun", frequency: 0.80, difficulty: 1 },
        { word: "teacher", pos: "noun", frequency: 0.80, difficulty: 1 },
        { word: "class", pos: "noun", frequency: 0.80, difficulty: 1 },
        { word: "lesson", pos: "noun", frequency: 0.70, difficulty: 1 },
        { word: "homework", pos: "noun", frequency: 0.65, difficulty: 1 },
        { word: "test", pos: "noun", frequency: 0.70, difficulty: 1 },
        { word: "exam", pos: "noun", frequency: 0.65, difficulty: 1 },
        { word: "grade", pos: "noun", frequency: 0.65, difficulty: 1 },
        { word: "university", pos: "noun", frequency: 0.70, difficulty: 1 },
        { word: "college", pos: "noun", frequency: 0.70, difficulty: 1 },
        { word: "degree", pos: "noun", frequency: 0.60, difficulty: 2 },
        { word: "education", pos: "noun", frequency: 0.70, difficulty: 2 },
        { word: "knowledge", pos: "noun", frequency: 0.75, difficulty: 1 },
        { word: "study", pos: "verb", frequency: 0.80, difficulty: 1 },
        { word: "learn", pos: "verb", frequency: 0.80, difficulty: 1 },
        { word: "teach", pos: "verb", frequency: 0.75, difficulty: 1 },
        { word: "work", pos: "noun", frequency: 0.90, difficulty: 1 },
        { word: "job", pos: "noun", frequency: 0.85, difficulty: 1 },
        { word: "career", pos: "noun", frequency: 0.65, difficulty: 2 },
        { word: "profession", pos: "noun", frequency: 0.60, difficulty: 2 },
        { word: "office", pos: "noun", frequency: 0.75, difficulty: 1 },
        { word: "company", pos: "noun", frequency: 0.80, difficulty: 1 },
        { word: "business", pos: "noun", frequency: 0.80, difficulty: 1 },
        { word: "manager", pos: "noun", frequency: 0.70, difficulty: 1 },
        { word: "employee", pos: "noun", frequency: 0.65, difficulty: 2 },
        { word: "worker", pos: "noun", frequency: 0.70, difficulty: 1 },
        { word: "boss", pos: "noun", frequency: 0.70, difficulty: 1 },
        { word: "salary", pos: "noun", frequency: 0.60, difficulty: 2 },
        { word: "money", pos: "noun", frequency: 0.85, difficulty: 1 },
        { word: "pay", pos: "noun", frequency: 0.75, difficulty: 1 },
        { word: "buy", pos: "verb", frequency: 0.80, difficulty: 1 },
        { word: "sell", pos: "verb", frequency: 0.70, difficulty: 1 },
        { word: "cost", pos: "noun", frequency: 0.75, difficulty: 1 },
        { word: "price", pos: "noun", frequency: 0.75, difficulty: 1 },
        { word: "cheap", pos: "adjective", frequency: 0.70, difficulty: 1 },
        { word: "expensive", pos: "adjective", frequency: 0.70, difficulty: 1 },
        { word: "free", pos: "adjective", frequency: 0.80, difficulty: 1 },
        { word: "store", pos: "noun", frequency: 0.75, difficulty: 1 },
        { word: "shop", pos: "noun", frequency: 0.75, difficulty: 1 },
        { word: "market", pos: "noun", frequency: 0.70, difficulty: 1 },
        { word: "bank", pos: "noun", frequency: 0.70, difficulty: 1 },
        { word: "hospital", pos: "noun", frequency: 0.70, difficulty: 1 },
        { word: "doctor", pos: "noun", frequency: 0.80, difficulty: 1 },
        { word: "nurse", pos: "noun", frequency: 0.65, difficulty: 1 },
        { word: "medicine", pos: "noun", frequency: 0.65, difficulty: 1 },
        { word: "health", pos: "noun", frequency: 0.75, difficulty: 1 },
        { word: "sick", pos: "adjective", frequency: 0.75, difficulty: 1 },
        { word: "well", pos: "adjective", frequency: 0.85, difficulty: 1 },
        { word: "police", pos: "noun", frequency: 0.70, difficulty: 1 }
      ],

      // Common Adjectives (150 words)  
      common_adjectives: [
        { word: "good", pos: "adjective", frequency: 0.95, difficulty: 1 },
        { word: "bad", pos: "adjective", frequency: 0.85, difficulty: 1 },
        { word: "big", pos: "adjective", frequency: 0.85, difficulty: 1 },
        { word: "small", pos: "adjective", frequency: 0.85, difficulty: 1 },
        { word: "old", pos: "adjective", frequency: 0.90, difficulty: 1 },
        { word: "new", pos: "adjective", frequency: 0.90, difficulty: 1 },
        { word: "young", pos: "adjective", frequency: 0.80, difficulty: 1 },
        { word: "long", pos: "adjective", frequency: 0.85, difficulty: 1 },
        { word: "short", pos: "adjective", frequency: 0.80, difficulty: 1 },
        { word: "high", pos: "adjective", frequency: 0.80, difficulty: 1 },
        { word: "low", pos: "adjective", frequency: 0.75, difficulty: 1 },
        { word: "hot", pos: "adjective", frequency: 0.80, difficulty: 1 },
        { word: "cold", pos: "adjective", frequency: 0.80, difficulty: 1 },
        { word: "warm", pos: "adjective", frequency: 0.75, difficulty: 1 },
        { word: "cool", pos: "adjective", frequency: 0.75, difficulty: 1 },
        { word: "wet", pos: "adjective", frequency: 0.70, difficulty: 1 },
        { word: "dry", pos: "adjective", frequency: 0.70, difficulty: 1 },
        { word: "clean", pos: "adjective", frequency: 0.75, difficulty: 1 },
        { word: "dirty", pos: "adjective", frequency: 0.70, difficulty: 1 },
        { word: "full", pos: "adjective", frequency: 0.80, difficulty: 1 },
        { word: "empty", pos: "adjective", frequency: 0.75, difficulty: 1 },
        { word: "heavy", pos: "adjective", frequency: 0.70, difficulty: 1 },
        { word: "light", pos: "adjective", frequency: 0.80, difficulty: 1 },
        { word: "hard", pos: "adjective", frequency: 0.80, difficulty: 1 },
        { word: "soft", pos: "adjective", frequency: 0.70, difficulty: 1 },
        { word: "strong", pos: "adjective", frequency: 0.75, difficulty: 1 },
        { word: "weak", pos: "adjective", frequency: 0.70, difficulty: 1 },
        { word: "fast", pos: "adjective", frequency: 0.80, difficulty: 1 },
        { word: "slow", pos: "adjective", frequency: 0.75, difficulty: 1 },
        { word: "easy", pos: "adjective", frequency: 0.85, difficulty: 1 },
        { word: "difficult", pos: "adjective", frequency: 0.70, difficulty: 2 },
        { word: "simple", pos: "adjective", frequency: 0.75, difficulty: 1 },
        { word: "complex", pos: "adjective", frequency: 0.60, difficulty: 2 },
        { word: "beautiful", pos: "adjective", frequency: 0.80, difficulty: 1 },
        { word: "ugly", pos: "adjective", frequency: 0.60, difficulty: 1 },
        { word: "nice", pos: "adjective", frequency: 0.85, difficulty: 1 },
        { word: "bad", pos: "adjective", frequency: 0.85, difficulty: 1 },
        { word: "happy", pos: "adjective", frequency: 0.85, difficulty: 1 },
        { word: "sad", pos: "adjective", frequency: 0.80, difficulty: 1 },
        { word: "angry", pos: "adjective", frequency: 0.70, difficulty: 1 },
        { word: "afraid", pos: "adjective", frequency: 0.70, difficulty: 1 },
        { word: "surprised", pos: "adjective", frequency: 0.65, difficulty: 1 },
        { word: "excited", pos: "adjective", frequency: 0.65, difficulty: 1 },
        { word: "tired", pos: "adjective", frequency: 0.75, difficulty: 1 },
        { word: "hungry", pos: "adjective", frequency: 0.70, difficulty: 1 },
        { word: "thirsty", pos: "adjective", frequency: 0.60, difficulty: 1 },
        { word: "sick", pos: "adjective", frequency: 0.75, difficulty: 1 },
        { word: "healthy", pos: "adjective", frequency: 0.70, difficulty: 1 },
        { word: "rich", pos: "adjective", frequency: 0.70, difficulty: 1 },
        { word: "poor", pos: "adjective", frequency: 0.75, difficulty: 1 },
        { word: "smart", pos: "adjective", frequency: 0.75, difficulty: 1 },
        { word: "stupid", pos: "adjective", frequency: 0.65, difficulty: 1 },
        { word: "kind", pos: "adjective", frequency: 0.70, difficulty: 1 },
        { word: "mean", pos: "adjective", frequency: 0.65, difficulty: 1 },
        { word: "funny", pos: "adjective", frequency: 0.75, difficulty: 1 },
        { word: "serious", pos: "adjective", frequency: 0.70, difficulty: 1 },
        { word: "quiet", pos: "adjective", frequency: 0.75, difficulty: 1 },
        { word: "loud", pos: "adjective", frequency: 0.70, difficulty: 1 },
        { word: "busy", pos: "adjective", frequency: 0.75, difficulty: 1 },
        { word: "free", pos: "adjective", frequency: 0.80, difficulty: 1 },
        { word: "open", pos: "adjective", frequency: 0.75, difficulty: 1 },
        { word: "closed", pos: "adjective", frequency: 0.70, difficulty: 1 },
        { word: "safe", pos: "adjective", frequency: 0.75, difficulty: 1 },
        { word: "dangerous", pos: "adjective", frequency: 0.65, difficulty: 2 },
        { word: "important", pos: "adjective", frequency: 0.80, difficulty: 1 },
        { word: "interesting", pos: "adjective", frequency: 0.75, difficulty: 2 },
        { word: "boring", pos: "adjective", frequency: 0.65, difficulty: 1 },
        { word: "special", pos: "adjective", frequency: 0.75, difficulty: 1 },
        { word: "normal", pos: "adjective", frequency: 0.70, difficulty: 1 },
        { word: "strange", pos: "adjective", frequency: 0.65, difficulty: 1 },
        { word: "different", pos: "adjective", frequency: 0.80, difficulty: 1 },
        { word: "same", pos: "adjective", frequency: 0.85, difficulty: 1 },
        { word: "similar", pos: "adjective", frequency: 0.65, difficulty: 2 },
        { word: "opposite", pos: "adjective", frequency: 0.60, difficulty: 2 },
        { word: "right", pos: "adjective", frequency: 0.90, difficulty: 1 },
        { word: "wrong", pos: "adjective", frequency: 0.80, difficulty: 1 },
        { word: "correct", pos: "adjective", frequency: 0.70, difficulty: 1 },
        { word: "true", pos: "adjective", frequency: 0.80, difficulty: 1 },
        { word: "false", pos: "adjective", frequency: 0.65, difficulty: 1 },
        { word: "real", pos: "adjective", frequency: 0.80, difficulty: 1 },
        { word: "fake", pos: "adjective", frequency: 0.60, difficulty: 1 }
      ],

      // Common Prepositions & Adverbs (80 words)
      prepositions_adverbs: [
        { word: "in", pos: "preposition", frequency: 1.0, difficulty: 1 },
        { word: "on", pos: "preposition", frequency: 0.95, difficulty: 1 },
        { word: "at", pos: "preposition", frequency: 0.95, difficulty: 1 },
        { word: "to", pos: "preposition", frequency: 1.0, difficulty: 1 },
        { word: "for", pos: "preposition", frequency: 0.95, difficulty: 1 },
        { word: "of", pos: "preposition", frequency: 1.0, difficulty: 1 },
        { word: "with", pos: "preposition", frequency: 0.95, difficulty: 1 },
        { word: "by", pos: "preposition", frequency: 0.90, difficulty: 1 },
        { word: "from", pos: "preposition", frequency: 0.90, difficulty: 1 },
        { word: "up", pos: "adverb", frequency: 0.85, difficulty: 1 },
        { word: "down", pos: "adverb", frequency: 0.85, difficulty: 1 },
        { word: "out", pos: "adverb", frequency: 0.90, difficulty: 1 },
        { word: "off", pos: "adverb", frequency: 0.80, difficulty: 1 },
        { word: "over", pos: "adverb", frequency: 0.85, difficulty: 1 },
        { word: "under", pos: "preposition", frequency: 0.75, difficulty: 1 },
        { word: "above", pos: "preposition", frequency: 0.70, difficulty: 1 },
        { word: "below", pos: "preposition", frequency: 0.65, difficulty: 1 },
        { word: "between", pos: "preposition", frequency: 0.75, difficulty: 1 },
        { word: "among", pos: "preposition", frequency: 0.60, difficulty: 2 },
        { word: "through", pos: "preposition", frequency: 0.75, difficulty: 1 },
        { word: "during", pos: "preposition", frequency: 0.70, difficulty: 1 },
        { word: "before", pos: "preposition", frequency: 0.80, difficulty: 1 },
        { word: "after", pos: "preposition", frequency: 0.80, difficulty: 1 },
        { word: "since", pos: "preposition", frequency: 0.70, difficulty: 1 },
        { word: "until", pos: "preposition", frequency: 0.70, difficulty: 1 },
        { word: "while", pos: "conjunction", frequency: 0.75, difficulty: 1 },
        { word: "where", pos: "adverb", frequency: 0.85, difficulty: 1 },
        { word: "when", pos: "adverb", frequency: 0.90, difficulty: 1 },
        { word: "how", pos: "adverb", frequency: 0.90, difficulty: 1 },
        { word: "what", pos: "pronoun", frequency: 0.95, difficulty: 1 },
        { word: "who", pos: "pronoun", frequency: 0.90, difficulty: 1 },
        { word: "which", pos: "pronoun", frequency: 0.80, difficulty: 1 },
        { word: "whose", pos: "pronoun", frequency: 0.65, difficulty: 2 },
        { word: "why", pos: "adverb", frequency: 0.90, difficulty: 1 },
        { word: "here", pos: "adverb", frequency: 0.90, difficulty: 1 },
        { word: "there", pos: "adverb", frequency: 0.95, difficulty: 1 },
        { word: "everywhere", pos: "adverb", frequency: 0.60, difficulty: 2 },
        { word: "somewhere", pos: "adverb", frequency: 0.65, difficulty: 1 },
        { word: "nowhere", pos: "adverb", frequency: 0.55, difficulty: 2 },
        { word: "always", pos: "adverb", frequency: 0.85, difficulty: 1 },
        { word: "never", pos: "adverb", frequency: 0.85, difficulty: 1 },
        { word: "sometimes", pos: "adverb", frequency: 0.80, difficulty: 1 },
        { word: "often", pos: "adverb", frequency: 0.75, difficulty: 1 },
        { word: "usually", pos: "adverb", frequency: 0.70, difficulty: 1 },
        { word: "rarely", pos: "adverb", frequency: 0.60, difficulty: 2 },
        { word: "already", pos: "adverb", frequency: 0.80, difficulty: 1 },
        { word: "still", pos: "adverb", frequency: 0.85, difficulty: 1 },
        { word: "yet", pos: "adverb", frequency: 0.75, difficulty: 1 },
        { word: "just", pos: "adverb", frequency: 0.90, difficulty: 1 },
        { word: "only", pos: "adverb", frequency: 0.90, difficulty: 1 },
        { word: "also", pos: "adverb", frequency: 0.85, difficulty: 1 },
        { word: "too", pos: "adverb", frequency: 0.85, difficulty: 1 },
        { word: "very", pos: "adverb", frequency: 0.90, difficulty: 1 },
        { word: "quite", pos: "adverb", frequency: 0.70, difficulty: 1 },
        { word: "rather", pos: "adverb", frequency: 0.60, difficulty: 2 },
        { word: "enough", pos: "adverb", frequency: 0.80, difficulty: 1 },
        { word: "much", pos: "adverb", frequency: 0.85, difficulty: 1 },
        { word: "many", pos: "determiner", frequency: 0.85, difficulty: 1 },
        { word: "few", pos: "determiner", frequency: 0.75, difficulty: 1 },
        { word: "little", pos: "adjective", frequency: 0.85, difficulty: 1 },
        { word: "more", pos: "adverb", frequency: 0.90, difficulty: 1 },
        { word: "less", pos: "adverb", frequency: 0.75, difficulty: 1 },
        { word: "most", pos: "adverb", frequency: 0.85, difficulty: 1 },
        { word: "least", pos: "adverb", frequency: 0.60, difficulty: 2 },
        { word: "all", pos: "determiner", frequency: 0.95, difficulty: 1 },
        { word: "some", pos: "determiner", frequency: 0.90, difficulty: 1 },
        { word: "any", pos: "determiner", frequency: 0.85, difficulty: 1 },
        { word: "no", pos: "determiner", frequency: 0.95, difficulty: 1 },
        { word: "every", pos: "determiner", frequency: 0.80, difficulty: 1 },
        { word: "each", pos: "determiner", frequency: 0.75, difficulty: 1 },
        { word: "other", pos: "adjective", frequency: 0.90, difficulty: 1 },
        { word: "another", pos: "determiner", frequency: 0.75, difficulty: 1 }
      ],

      // Technology & Communication (60 words)
      technology_communication: [
        { word: "computer", pos: "noun", frequency: 0.75, difficulty: 1 },
        { word: "internet", pos: "noun", frequency: 0.70, difficulty: 1 },
        { word: "website", pos: "noun", frequency: 0.65, difficulty: 1 },
        { word: "email", pos: "noun", frequency: 0.70, difficulty: 1 },
        { word: "phone", pos: "noun", frequency: 0.80, difficulty: 1 },
        { word: "mobile", pos: "adjective", frequency: 0.65, difficulty: 1 },
        { word: "call", pos: "verb", frequency: 0.80, difficulty: 1 },
        { word: "text", pos: "noun", frequency: 0.75, difficulty: 1 },
        { word: "message", pos: "noun", frequency: 0.75, difficulty: 1 },
        { word: "send", pos: "verb", frequency: 0.75, difficulty: 1 },
        { word: "receive", pos: "verb", frequency: 0.70, difficulty: 1 },
        { word: "answer", pos: "verb", frequency: 0.80, difficulty: 1 },
        { word: "talk", pos: "verb", frequency: 0.85, difficulty: 1 },
        { word: "speak", pos: "verb", frequency: 0.75, difficulty: 1 },
        { word: "listen", pos: "verb", frequency: 0.75, difficulty: 1 },
        { word: "hear", pos: "verb", frequency: 0.80, difficulty: 1 },
        { word: "sound", pos: "noun", frequency: 0.80, difficulty: 1 },
        { word: "voice", pos: "noun", frequency: 0.75, difficulty: 1 },
        { word: "word", pos: "noun", frequency: 0.90, difficulty: 1 },
        { word: "language", pos: "noun", frequency: 0.75, difficulty: 1 },
        { word: "translate", pos: "verb", frequency: 0.60, difficulty: 2 },
        { word: "mean", pos: "verb", frequency: 0.85, difficulty: 1 },
        { word: "explain", pos: "verb", frequency: 0.75, difficulty: 1 },
        { word: "understand", pos: "verb", frequency: 0.80, difficulty: 1 },
        { word: "communicate", pos: "verb", frequency: 0.65, difficulty: 2 },
        { word: "information", pos: "noun", frequency: 0.75, difficulty: 2 },
        { word: "news", pos: "noun", frequency: 0.75, difficulty: 1 },
        { word: "television", pos: "noun", frequency: 0.70, difficulty: 1 },
        { word: "radio", pos: "noun", frequency: 0.65, difficulty: 1 },
        { word: "newspaper", pos: "noun", frequency: 0.60, difficulty: 1 },
        { word: "magazine", pos: "noun", frequency: 0.60, difficulty: 1 },
        { word: "book", pos: "noun", frequency: 0.85, difficulty: 1 },
        { word: "page", pos: "noun", frequency: 0.70, difficulty: 1 },
        { word: "story", pos: "noun", frequency: 0.80, difficulty: 1 },
        { word: "picture", pos: "noun", frequency: 0.80, difficulty: 1 },
        { word: "photo", pos: "noun", frequency: 0.70, difficulty: 1 },
        { word: "video", pos: "noun", frequency: 0.70, difficulty: 1 },
        { word: "movie", pos: "noun", frequency: 0.75, difficulty: 1 },
        { word: "music", pos: "noun", frequency: 0.80, difficulty: 1 },
        { word: "song", pos: "noun", frequency: 0.75, difficulty: 1 }
      ],

      // Health & Emotions (70 words)
      health_emotions: [
        { word: "feel", pos: "verb", frequency: 0.90, difficulty: 1 },
        { word: "emotion", pos: "noun", frequency: 0.60, difficulty: 2 },
        { word: "happy", pos: "adjective", frequency: 0.85, difficulty: 1 },
        { word: "sad", pos: "adjective", frequency: 0.80, difficulty: 1 },
        { word: "angry", pos: "adjective", frequency: 0.70, difficulty: 1 },
        { word: "excited", pos: "adjective", frequency: 0.65, difficulty: 1 },
        { word: "nervous", pos: "adjective", frequency: 0.60, difficulty: 1 },
        { word: "worried", pos: "adjective", frequency: 0.65, difficulty: 1 },
        { word: "afraid", pos: "adjective", frequency: 0.70, difficulty: 1 },
        { word: "scared", pos: "adjective", frequency: 0.65, difficulty: 1 },
        { word: "surprised", pos: "adjective", frequency: 0.65, difficulty: 1 },
        { word: "confused", pos: "adjective", frequency: 0.60, difficulty: 1 },
        { word: "tired", pos: "adjective", frequency: 0.75, difficulty: 1 },
        { word: "sleepy", pos: "adjective", frequency: 0.60, difficulty: 1 },
        { word: "awake", pos: "adjective", frequency: 0.65, difficulty: 1 },
        { word: "sleep", pos: "verb", frequency: 0.85, difficulty: 1 },
        { word: "dream", pos: "noun", frequency: 0.70, difficulty: 1 },
        { word: "health", pos: "noun", frequency: 0.75, difficulty: 1 },
        { word: "healthy", pos: "adjective", frequency: 0.70, difficulty: 1 },
        { word: "sick", pos: "adjective", frequency: 0.75, difficulty: 1 },
        { word: "ill", pos: "adjective", frequency: 0.65, difficulty: 1 },
        { word: "disease", pos: "noun", frequency: 0.60, difficulty: 2 },
        { word: "pain", pos: "noun", frequency: 0.70, difficulty: 1 },
        { word: "hurt", pos: "verb", frequency: 0.75, difficulty: 1 },
        { word: "injury", pos: "noun", frequency: 0.60, difficulty: 2 },
        { word: "medicine", pos: "noun", frequency: 0.65, difficulty: 1 },
        { word: "doctor", pos: "noun", frequency: 0.80, difficulty: 1 },
        { word: "hospital", pos: "noun", frequency: 0.70, difficulty: 1 },
        { word: "nurse", pos: "noun", frequency: 0.65, difficulty: 1 },
        { word: "treatment", pos: "noun", frequency: 0.60, difficulty: 2 },
        { word: "cure", pos: "noun", frequency: 0.60, difficulty: 1 },
        { word: "recover", pos: "verb", frequency: 0.60, difficulty: 2 },
        { word: "exercise", pos: "noun", frequency: 0.65, difficulty: 1 },
        { word: "sport", pos: "noun", frequency: 0.70, difficulty: 1 },
        { word: "game", pos: "noun", frequency: 0.80, difficulty: 1 },
        { word: "play", pos: "verb", frequency: 0.85, difficulty: 1 },
        { word: "win", pos: "verb", frequency: 0.75, difficulty: 1 },
        { word: "lose", pos: "verb", frequency: 0.75, difficulty: 1 },
        { word: "team", pos: "noun", frequency: 0.75, difficulty: 1 },
        { word: "player", pos: "noun", frequency: 0.70, difficulty: 1 }
      ],

      // Weather & Seasons (50 words) 
      weather_seasons: [
        { word: "weather", pos: "noun", frequency: 0.75, difficulty: 1 },
        { word: "season", pos: "noun", frequency: 0.65, difficulty: 1 },
        { word: "spring", pos: "noun", frequency: 0.65, difficulty: 1 },
        { word: "summer", pos: "noun", frequency: 0.70, difficulty: 1 },
        { word: "autumn", pos: "noun", frequency: 0.60, difficulty: 1 },
        { word: "fall", pos: "noun", frequency: 0.65, difficulty: 1 },
        { word: "winter", pos: "noun", frequency: 0.70, difficulty: 1 },
        { word: "sun", pos: "noun", frequency: 0.85, difficulty: 1 },
        { word: "sunny", pos: "adjective", frequency: 0.70, difficulty: 1 },
        { word: "sunshine", pos: "noun", frequency: 0.60, difficulty: 1 },
        { word: "cloud", pos: "noun", frequency: 0.70, difficulty: 1 },
        { word: "cloudy", pos: "adjective", frequency: 0.65, difficulty: 1 },
        { word: "rain", pos: "noun", frequency: 0.75, difficulty: 1 },
        { word: "rainy", pos: "adjective", frequency: 0.65, difficulty: 1 },
        { word: "snow", pos: "noun", frequency: 0.70, difficulty: 1 },
        { word: "snowy", pos: "adjective", frequency: 0.60, difficulty: 1 },
        { word: "wind", pos: "noun", frequency: 0.70, difficulty: 1 },
        { word: "windy", pos: "adjective", frequency: 0.65, difficulty: 1 },
        { word: "storm", pos: "noun", frequency: 0.65, difficulty: 1 },
        { word: "thunder", pos: "noun", frequency: 0.60, difficulty: 1 },
        { word: "lightning", pos: "noun", frequency: 0.55, difficulty: 1 },
        { word: "hot", pos: "adjective", frequency: 0.80, difficulty: 1 },
        { word: "cold", pos: "adjective", frequency: 0.80, difficulty: 1 },
        { word: "warm", pos: "adjective", frequency: 0.75, difficulty: 1 },
        { word: "cool", pos: "adjective", frequency: 0.75, difficulty: 1 },
        { word: "temperature", pos: "noun", frequency: 0.65, difficulty: 2 },
        { word: "degree", pos: "noun", frequency: 0.65, difficulty: 1 },
        { word: "ice", pos: "noun", frequency: 0.70, difficulty: 1 },
        { word: "frozen", pos: "adjective", frequency: 0.60, difficulty: 1 },
        { word: "melt", pos: "verb", frequency: 0.55, difficulty: 1 }
      ],

      // Clothing & Appearance (60 words)
      clothing_appearance: [
        { word: "clothes", pos: "noun", frequency: 0.75, difficulty: 1 },
        { word: "clothing", pos: "noun", frequency: 0.65, difficulty: 1 },
        { word: "wear", pos: "verb", frequency: 0.80, difficulty: 1 },
        { word: "dress", pos: "verb", frequency: 0.70, difficulty: 1 },
        { word: "shirt", pos: "noun", frequency: 0.70, difficulty: 1 },
        { word: "pants", pos: "noun", frequency: 0.65, difficulty: 1 },
        { word: "dress", pos: "noun", frequency: 0.65, difficulty: 1 },
        { word: "skirt", pos: "noun", frequency: 0.60, difficulty: 1 },
        { word: "jacket", pos: "noun", frequency: 0.65, difficulty: 1 },
        { word: "coat", pos: "noun", frequency: 0.65, difficulty: 1 },
        { word: "sweater", pos: "noun", frequency: 0.60, difficulty: 1 },
        { word: "shoes", pos: "noun", frequency: 0.75, difficulty: 1 },
        { word: "boots", pos: "noun", frequency: 0.60, difficulty: 1 },
        { word: "socks", pos: "noun", frequency: 0.60, difficulty: 1 },
        { word: "hat", pos: "noun", frequency: 0.60, difficulty: 1 },
        { word: "cap", pos: "noun", frequency: 0.55, difficulty: 1 },
        { word: "gloves", pos: "noun", frequency: 0.55, difficulty: 1 },
        { word: "belt", pos: "noun", frequency: 0.55, difficulty: 1 },
        { word: "tie", pos: "noun", frequency: 0.55, difficulty: 1 },
        { word: "jewelry", pos: "noun", frequency: 0.55, difficulty: 2 },
        { word: "watch", pos: "noun", frequency: 0.65, difficulty: 1 },
        { word: "glasses", pos: "noun", frequency: 0.60, difficulty: 1 },
        { word: "appearance", pos: "noun", frequency: 0.60, difficulty: 2 },
        { word: "look", pos: "verb", frequency: 0.90, difficulty: 1 },
        { word: "see", pos: "verb", frequency: 0.90, difficulty: 1 },
        { word: "beautiful", pos: "adjective", frequency: 0.80, difficulty: 1 },
        { word: "handsome", pos: "adjective", frequency: 0.60, difficulty: 1 },
        { word: "pretty", pos: "adjective", frequency: 0.70, difficulty: 1 },
        { word: "ugly", pos: "adjective", frequency: 0.60, difficulty: 1 },
        { word: "tall", pos: "adjective", frequency: 0.75, difficulty: 1 },
        { word: "short", pos: "adjective", frequency: 0.80, difficulty: 1 },
        { word: "fat", pos: "adjective", frequency: 0.60, difficulty: 1 },
        { word: "thin", pos: "adjective", frequency: 0.65, difficulty: 1 },
        { word: "size", pos: "noun", frequency: 0.75, difficulty: 1 },
        { word: "weight", pos: "noun", frequency: 0.65, difficulty: 1 }
      ],

      // Recreation & Entertainment (60 words)
      recreation_entertainment: [
        { word: "fun", pos: "noun", frequency: 0.80, difficulty: 1 },
        { word: "enjoy", pos: "verb", frequency: 0.75, difficulty: 1 },
        { word: "entertainment", pos: "noun", frequency: 0.60, difficulty: 2 },
        { word: "hobby", pos: "noun", frequency: 0.60, difficulty: 2 },
        { word: "interest", pos: "noun", frequency: 0.70, difficulty: 1 },
        { word: "activity", pos: "noun", frequency: 0.70, difficulty: 2 },
        { word: "game", pos: "noun", frequency: 0.80, difficulty: 1 },
        { word: "play", pos: "verb", frequency: 0.85, difficulty: 1 },
        { word: "sport", pos: "noun", frequency: 0.70, difficulty: 1 },
        { word: "football", pos: "noun", frequency: 0.65, difficulty: 1 },
        { word: "basketball", pos: "noun", frequency: 0.60, difficulty: 1 },
        { word: "baseball", pos: "noun", frequency: 0.60, difficulty: 1 },
        { word: "soccer", pos: "noun", frequency: 0.60, difficulty: 1 },
        { word: "tennis", pos: "noun", frequency: 0.55, difficulty: 1 },
        { word: "swimming", pos: "noun", frequency: 0.60, difficulty: 1 },
        { word: "running", pos: "noun", frequency: 0.65, difficulty: 1 },
        { word: "dancing", pos: "noun", frequency: 0.60, difficulty: 1 },
        { word: "music", pos: "noun", frequency: 0.80, difficulty: 1 },
        { word: "song", pos: "noun", frequency: 0.75, difficulty: 1 },
        { word: "sing", pos: "verb", frequency: 0.70, difficulty: 1 },
        { word: "dance", pos: "verb", frequency: 0.65, difficulty: 1 },
        { word: "movie", pos: "noun", frequency: 0.75, difficulty: 1 },
        { word: "film", pos: "noun", frequency: 0.65, difficulty: 1 },
        { word: "theater", pos: "noun", frequency: 0.55, difficulty: 1 },
        { word: "concert", pos: "noun", frequency: 0.55, difficulty: 1 },
        { word: "party", pos: "noun", frequency: 0.70, difficulty: 1 },
        { word: "celebration", pos: "noun", frequency: 0.60, difficulty: 2 },
        { word: "festival", pos: "noun", frequency: 0.55, difficulty: 2 },
        { word: "holiday", pos: "noun", frequency: 0.70, difficulty: 1 },
        { word: "vacation", pos: "noun", frequency: 0.65, difficulty: 1 },
        { word: "travel", pos: "verb", frequency: 0.75, difficulty: 1 },
        { word: "visit", pos: "verb", frequency: 0.75, difficulty: 1 },
        { word: "tour", pos: "noun", frequency: 0.60, difficulty: 1 },
        { word: "tourist", pos: "noun", frequency: 0.55, difficulty: 1 },
        { word: "hotel", pos: "noun", frequency: 0.65, difficulty: 1 },
        { word: "restaurant", pos: "noun", frequency: 0.70, difficulty: 1 },
        { word: "bar", pos: "noun", frequency: 0.65, difficulty: 1 },
        { word: "club", pos: "noun", frequency: 0.65, difficulty: 1 },
        { word: "park", pos: "noun", frequency: 0.70, difficulty: 1 },
        { word: "beach", pos: "noun", frequency: 0.65, difficulty: 1 }
      ],

      // Social & Relationships (70 words)
      social_relationships: [
        { word: "people", pos: "noun", frequency: 0.95, difficulty: 1 },
        { word: "person", pos: "noun", frequency: 0.95, difficulty: 1 },
        { word: "friend", pos: "noun", frequency: 0.85, difficulty: 1 },
        { word: "friendship", pos: "noun", frequency: 0.60, difficulty: 2 },
        { word: "relationship", pos: "noun", frequency: 0.70, difficulty: 2 },
        { word: "love", pos: "noun", frequency: 0.85, difficulty: 1 },
        { word: "marry", pos: "verb", frequency: 0.65, difficulty: 1 },
        { word: "marriage", pos: "noun", frequency: 0.60, difficulty: 2 },
        { word: "wedding", pos: "noun", frequency: 0.55, difficulty: 1 },
        { word: "couple", pos: "noun", frequency: 0.65, difficulty: 1 },
        { word: "single", pos: "adjective", frequency: 0.70, difficulty: 1 },
        { word: "alone", pos: "adjective", frequency: 0.75, difficulty: 1 },
        { word: "together", pos: "adverb", frequency: 0.80, difficulty: 1 },
        { word: "group", pos: "noun", frequency: 0.75, difficulty: 1 },
        { word: "team", pos: "noun", frequency: 0.75, difficulty: 1 },
        { word: "community", pos: "noun", frequency: 0.65, difficulty: 2 },
        { word: "society", pos: "noun", frequency: 0.60, difficulty: 2 },
        { word: "public", pos: "adjective", frequency: 0.75, difficulty: 1 },
        { word: "private", pos: "adjective", frequency: 0.70, difficulty: 1 },
        { word: "social", pos: "adjective", frequency: 0.65, difficulty: 2 },
        { word: "meet", pos: "verb", frequency: 0.80, difficulty: 1 },
        { word: "introduce", pos: "verb", frequency: 0.60, difficulty: 2 },
        { word: "greet", pos: "verb", frequency: 0.55, difficulty: 1 },
        { word: "welcome", pos: "verb", frequency: 0.65, difficulty: 1 },
        { word: "invite", pos: "verb", frequency: 0.65, difficulty: 1 },
        { word: "visit", pos: "verb", frequency: 0.75, difficulty: 1 },
        { word: "guest", pos: "noun", frequency: 0.60, difficulty: 1 },
        { word: "host", pos: "noun", frequency: 0.55, difficulty: 1 },
        { word: "neighbor", pos: "noun", frequency: 0.60, difficulty: 1 },
        { word: "stranger", pos: "noun", frequency: 0.60, difficulty: 1 },
        { word: "kind", pos: "adjective", frequency: 0.70, difficulty: 1 },
        { word: "nice", pos: "adjective", frequency: 0.85, difficulty: 1 },
        { word: "friendly", pos: "adjective", frequency: 0.65, difficulty: 1 },
        { word: "polite", pos: "adjective", frequency: 0.60, difficulty: 1 },
        { word: "rude", pos: "adjective", frequency: 0.60, difficulty: 1 },
        { word: "help", pos: "verb", frequency: 0.85, difficulty: 1 },
        { word: "support", pos: "verb", frequency: 0.70, difficulty: 1 },
        { word: "care", pos: "verb", frequency: 0.80, difficulty: 1 },
        { word: "share", pos: "verb", frequency: 0.70, difficulty: 1 },
        { word: "give", pos: "verb", frequency: 0.85, difficulty: 1 },
        { word: "receive", pos: "verb", frequency: 0.70, difficulty: 1 },
        { word: "gift", pos: "noun", frequency: 0.65, difficulty: 1 },
        { word: "present", pos: "noun", frequency: 0.65, difficulty: 1 },
        { word: "thank", pos: "verb", frequency: 0.75, difficulty: 1 },
        { word: "please", pos: "interjection", frequency: 0.85, difficulty: 1 },
        { word: "sorry", pos: "interjection", frequency: 0.80, difficulty: 1 },
        { word: "excuse", pos: "verb", frequency: 0.65, difficulty: 1 },
        { word: "forgive", pos: "verb", frequency: 0.60, difficulty: 1 },
        { word: "trust", pos: "verb", frequency: 0.65, difficulty: 1 },
        { word: "promise", pos: "verb", frequency: 0.65, difficulty: 1 }
      ]
    };
  }
}