"""Generate and apply the Neo4j schema constraints that anchor ``csid`` identity.

Every culture-scrape node carries the shared :data:`ENTITY_LABEL` label in
addition to its per-type labels (``Dish``, ``Sculpture``, ...), because ``csid``
is a *global* primary key — "unique across all nodes" (``docs/data-model.md``) —
and Neo4j uniqueness constraints and indexes always attach to a single label.
Anchoring identity on one base label lets a single constraint enforce ``csid``
uniqueness across the whole graph and lets a single index back the
``MERGE (n:Entity {csid})`` the incremental loader (``load_csv.py``) runs, so
re-imports are index lookups rather than full scans.

This module emits three idempotent statements — a ``csid`` uniqueness constraint
and supporting indexes on ``wikidata_qid`` and ``name`` — to a runnable
``cypher-shell`` script (no live database required), and offers
:func:`apply_constraints` to run them against a connected database via the
optional driver (see :mod:`culturescrape.neo4j`). ``IF NOT EXISTS`` makes every
statement safe to re-run.
"""

from __future__ import annotations

from collections.abc import Mapping
from pathlib import Path
from typing import TYPE_CHECKING, Any

from culturescrape.neo4j import connect

if TYPE_CHECKING:
    from neo4j import Driver

#: Shared base label every node carries; the anchor for the ``csid`` constraint.
ENTITY_LABEL = "Entity"

#: Name of the ``csid`` uniqueness constraint.
CSID_CONSTRAINT = "csid_unique"

#: Name of the ``wikidata_qid`` lookup index.
WIKIDATA_QID_INDEX = "entity_wikidata_qid"

#: Name of the ``name`` lookup index.
NAME_INDEX = "entity_name"

#: Filename of the emitted Cypher script.
SCRIPT_NAME = "neo4j-constraints.cypher"


def constraint_statements() -> tuple[str, ...]:
    """Return the idempotent constraint and index statements, in apply order.

    The uniqueness constraint comes first (it also creates a backing index for
    ``csid``); the explicit ``wikidata_qid`` and ``name`` indexes follow. Every
    statement uses ``IF NOT EXISTS`` so re-running is a no-op.
    """
    return (
        f"CREATE CONSTRAINT {CSID_CONSTRAINT} IF NOT EXISTS\n"
        f"FOR (n:{ENTITY_LABEL}) REQUIRE n.csid IS UNIQUE;",
        f"CREATE INDEX {WIKIDATA_QID_INDEX} IF NOT EXISTS\n"
        f"FOR (n:{ENTITY_LABEL}) ON (n.wikidata_qid);",
        f"CREATE INDEX {NAME_INDEX} IF NOT EXISTS\n"
        f"FOR (n:{ENTITY_LABEL}) ON (n.name);",
    )


def render_script(statements: tuple[str, ...]) -> str:
    """Render *statements* as a runnable ``cypher-shell`` script."""
    return (
        "// Generated by culturescrape: schema constraints and indexes for Neo4j.\n"
        "// Idempotent — IF NOT EXISTS makes re-running a no-op.\n"
        f"// Run with: cypher-shell -f {SCRIPT_NAME}\n\n"
        + "\n\n".join(statements)
        + "\n"
    )


def generate_constraints_script(
    out_dir: str | Path,
    *,
    script_path: str | Path | None = None,
) -> Path:
    """Write the constraint/index Cypher to a runnable script and return its path.

    No live database is touched. The statements are dataset-independent: they
    describe the canonical schema, not a particular set of files.

    Args:
        out_dir: Directory the script is written to.
        script_path: Explicit script path (default: ``<out_dir>/<SCRIPT_NAME>``).
    """
    out_path = Path(out_dir)
    script = Path(script_path) if script_path is not None else out_path / SCRIPT_NAME
    script.parent.mkdir(parents=True, exist_ok=True)
    script.write_text(render_script(constraint_statements()), encoding="utf-8")
    return script


def apply_constraints(
    config: Mapping[str, Any] | None = None,
    *,
    env: Mapping[str, str] | None = None,
    driver: Driver | None = None,
) -> tuple[str, ...]:
    """Apply the constraint/index statements to a connected database.

    Runs each statement from :func:`constraint_statements` in its own session.
    When *driver* is given it is used as-is (and left open for the caller);
    otherwise a driver is opened from *config*/*env* via
    :func:`culturescrape.neo4j.connect` and closed before returning.

    Returns:
        The statements that were executed, in order.
    """
    statements = constraint_statements()
    owned = driver is None
    handle = connect(config, env=env) if driver is None else driver
    try:
        with handle.session() as session:
            for statement in statements:
                session.run(statement)
    finally:
        if owned:
            handle.close()
    return statements


__all__ = [
    "CSID_CONSTRAINT",
    "ENTITY_LABEL",
    "NAME_INDEX",
    "SCRIPT_NAME",
    "WIKIDATA_QID_INDEX",
    "apply_constraints",
    "constraint_statements",
    "generate_constraints_script",
    "render_script",
]
