import { describe, it, expect } from "vitest";

import { parseDnaFile } from "./dna-parser";

const TWENTYTHREE_AND_ME = [
  "# This data file generated by 23andMe at: Sun Jan 01 2023",
  "# rsid\tchromosome\tposition\tgenotype",
  "rs4477212\t1\t82154\tAA",
  "rs3908\tY\t2657176\tGG",
  "rs9786153\tY\t2887824\tCC",
  "rs2032658\tY\t2734393\tTT",
  "rs2032658b\tY\t2734500\tGG",
  "rs2032631\tY\t2900000\tAA",
  "rsMT1\tMT\t100\tA",
  "rsNoCall\t2\t500\t--",
].join("\n");

const ANCESTRY_DNA = [
  "#AncestryDNA raw data download",
  "#This file is intended for personal use only.",
  "rsid\tchromosome\tposition\tallele1\tallele2",
  "rs4477212\t1\t82154\tA\tA",
  "rs9786153\t24\t2887824\tC\tC",
  "rs2032658\t24\t2734393\tT\tT",
  "rs2032631\t24\t2900000\tA\tA",
  "rsMitochondrial\t26\t100\tA\t0",
  "rsMissing\t2\t500\t0\t0",
].join("\r\n");

describe("parseDnaFile", () => {
  it("detects and parses the 23andMe format", () => {
    const parsed = parseDnaFile(TWENTYTHREE_AND_ME);
    expect(parsed.format).toBe("23andme");
    expect(parsed.byRsid.get("rs4477212")?.genotype).toBe("AA");
    expect(parsed.byRsid.get("rs3908")?.chromosome).toBe("Y");
    expect(parsed.counts.yChromosome).toBe(5);
    expect(parsed.counts.mtDna).toBe(1);
  });

  it("drops no-call genotypes to an empty string but keeps the row", () => {
    const parsed = parseDnaFile(TWENTYTHREE_AND_ME);
    expect(parsed.byRsid.get("rsNoCall")?.genotype).toBe("");
  });

  it("detects and parses the AncestryDNA format, skipping its header row", () => {
    const parsed = parseDnaFile(ANCESTRY_DNA);
    expect(parsed.format).toBe("ancestrydna");
    // Header row (`rsid ...`) must not become an SNP.
    expect(parsed.byRsid.has("rsid")).toBe(false);
    // Two allele columns concatenate.
    expect(parsed.byRsid.get("rs9786153")?.genotype).toBe("CC");
    // Chromosome 24 → Y, 26 → MT.
    expect(parsed.byRsid.get("rs9786153")?.chromosome).toBe("Y");
    expect(parsed.byRsid.get("rsMitochondrial")?.chromosome).toBe("MT");
    // Missing allele "0" is dropped from the genotype.
    expect(parsed.byRsid.get("rsMitochondrial")?.genotype).toBe("A");
  });

  it("returns unknown format and no snps for empty / comment-only input", () => {
    const parsed = parseDnaFile("# only a comment\n\n");
    expect(parsed.format).toBe("unknown");
    expect(parsed.snps).toHaveLength(0);
    expect(parsed.counts.total).toBe(0);
  });
});
